<?php
/**
 * @category Trans
 * @package  Trans_CustomerMyProfile
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 *
 * @author   Dwi Septha Kurniawan <septha.kurniawan@transdigital.co.id>
 *
 * Copyright © 2019 PT Trans Digital. All rights reserved.
 * http://www.ctcorpora.com
 */

/** @var \Magento\Customer\Block\Widget\Telephone $block */
?>

<div class="field telephone required">
    <label for="telephone" class="label">
        <span>
            <?= $block->escapeHtml(__('Phone Number')) ?>
        </span>
    </label>
    <div class="control">
        <input type="text"
               name="telephone"
               id="telephone"
               value="<?= $block->escapeHtmlAttr($block->getTelephone()) ?>"
               title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
               class="input-text required-entry minimum-length-8 maximum-length-15 validate-mobile-number"
               data-validate="{required:true, 'validate-number':true, 'validate-length':true}"
        >
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*" : {
             "validatemobilenumberjs": {}
        }
    }
</script>