<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if ($crumbs && is_array($crumbs)) : ?>
    <div class="breadcrumbs ">
        <div class="breadcrumbs-compare">
            <div class="breadcrumb-pdp">
                <ul class="items">
                    <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                        <li class="item <?= $block->escapeHtmlAttr($crumbName) ?>">
                            <?php if ($crumbInfo['link']) : ?>
                                <a href="<?= $block->escapeUrl($crumbInfo['link']) ?>"
                                   title="<?= $block->escapeHtmlAttr($crumbInfo['title']) ?>">
                                    <?= $block->escapeHtml($crumbInfo['label']) ?>
                                </a>
                            <?php elseif ($crumbInfo['last']) : ?>
                                <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
                            <?php else : ?>
                                <?= $block->escapeHtml($crumbInfo['label']) ?>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>

            <?= $block->getChildHtml('comparelink') ?>
        </div>

    </div>
<?php endif; ?>
