<?php


namespace SM\Sales\Block\Order;

use SM\Sales\Block\AbstractDetail;

/**
 * Class VoucherDetail
 * @package SM\Sales\Block\Order
 */
class VoucherDetail extends AbstractDetail
{
    const VOUCHER_DETAIL_TEMPLATE = "SM_Sales::order/detail/voucher-detail.phtml";

    protected function _prepareLayout()
    {
        $this->setTemplate(self::VOUCHER_DETAIL_TEMPLATE);
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}
