<?php
/**
 * @project    ct-corp-transmart
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author     Duc Nguyen Hoang <ducnh2@smartosc.com>
 * @copyright  Copyright © 2020 SmartOSC. All rights reserved.
 * @url        http://www.smartosc.com
 */

/** @var \Mirasvit\Blog\Block\Post\PostList\Toolbar $block */
?>
<?php $widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getWidgetOptionsJson());
$widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['sortInspirePost']);
?>
<div class="inspire-me post-toolbar" id="inspire-me-listing"
     data-mage-init='{"sortInspirePost":<?= /* @noEscape */ $widgetOptions ?>}'>
    <?= $block->getChildHtml('blog.sidebar.search') ?>
    <?= $block->getChildHtml('blog.sidebar.category.tree') ?>
    <?php include ($block->getTemplateFile('SM_InspireMe::post/head/sort-by.phtml')) ?>
</div>
