<?php
/**
 * @project    ct-corp-transmart
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author     Duc Nguyen Hoang <ducnh2@smartosc.com>
 * @copyright  Copyright © 2020 SmartOSC. All rights reserved.
 * @url        http://www.smartosc.com
 */

/** @var \Mirasvit\Blog\Block\Post\PostList $block */
$postCollection = $block->getPostCollection();
/** @var \SM\InspireMe\Helper\Data $helper */
$helper = $this->helper(\SM\InspireMe\Helper\Data::class);

$GTMViewModel = $block->getData('gtm_view_model');
?>
<?= $block->getChildHtml('blog.post.list.head') ?>

<?php if ($postCollection->getSize()): ?>
<div class="inspire-post-listing">
    <div class="inspire-listing-items-grid">
        <div class="row">
        <? /** @var \Mirasvit\Blog\Model\Post $post */?>
        <?php foreach ($postCollection as $post): ?>
        <?php $data = $GTMViewModel ? $GTMViewModel->getGtm($post) : null ?>
            <div class="col-xs-12 col-sm-6 col-md-4">
                <div class="post-item-content">

                    <?php if ($post->getFeaturedImage()): ?>
                    <div class="post-image">
                        <a class="fade-img" href="<?= $block->escapeUrl($post->getUrl()) ?>"
                           title="<?= $block->escapeHtml($post->getName()) ?>"
                           <?php if ($data) : ?>
                           data-gtm-event="<?= \SM\InspireMe\Helper\Data::GTM_POST_EVENT_CLICK_NAME ?>"
                           data-gtm='<?= $block->escapeHtml($data) ?>'
                           data-gtm-name="<?= \SM\InspireMe\Helper\Data::GTM_POST_DATA_NAME ?>"
                           <?php endif; ?>>
                        <img class="lazy-loaded" loading="lazy" width="470" height="260"
                             src="<?= $block->escapeUrl($helper->getImageResize($post->getFeaturedImage(), 470, 260)) ?>"
                             alt="<?= $block->escapeHtml($post->getName()) ?>">
                        </a>
                    </div>
                    <?php endif ?>
                    <div class="post-info">
                        <div class="post-info-date">
                            <?php $topics = $post->getCategories()->excludeRoot() ?>
                            <?php if ($topics->getSize()): ?>
                                <?php /** @var \Mirasvit\Blog\Model\Category $firstTopic */?>
                                <?php $firstTopic = $topics->getFirstItem() ?>
                                <span class="post-tag"><?= $block->escapeHtml($firstTopic->getName()) ?></span>
                            <?php endif; ?>
                            <span class="post-created-date"><?= $block->escapeHtml($block->getFormatDate($post->getCreatedAt())) ?></span>

                        </div>

                        <a href="<?= $block->escapeUrl($post->getUrl()) ?>"
                           title="<?= $block->escapeHtml($post->getName()) ?>"
                           class="post-title"
                           <?php if ($data) : ?>
                           data-gtm-event="<?= \SM\InspireMe\Helper\Data::GTM_POST_EVENT_CLICK_NAME ?>"
                           data-gtm='<?= $block->escapeHtml($data) ?>'
                           data-gtm-name="<?= \SM\InspireMe\Helper\Data::GTM_POST_DATA_NAME ?>"
                           <?php endif; ?>>
                            <h3 ><?= $block->escapeHtml($post->getName()) ?></h3>
                        </a>
                        <p class="post-description"><?= $block->escapeHtml($post->getShortContent()) ?></p>
                        <a href="<?= $block->escapeUrl($post->getUrl()) ?>"
                           title="<?= $block->escapeHtml($post->getName()) ?>"
                           class="post-readmore"
                           <?php if ($data) : ?>
                           data-gtm-event="<?= \SM\InspireMe\Helper\Data::GTM_POST_EVENT_CLICK_NAME ?>"
                           data-gtm='<?= $block->escapeHtml($GTMViewModel->getGtm($post)) ?>'
                           data-gtm-name="<?= \SM\InspireMe\Helper\Data::GTM_POST_DATA_NAME ?>"
                           <?php endif; ?>>
                            <?= $block->escapeHtml(__('Read More'))?>
                        </a>
                    </div>



                </div>
            </div>
        <?php endforeach; ?>
        </div>
    </div>

    <?= $block->getToolbarHtml() ?>
</div>
<?php endif; ?>
