<?php
/**
 * @project    ct-corp-transmart
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author     Duc Nguyen Hoang <ducnh2@smartosc.com>
 * @copyright  Copyright © 2020 SmartOSC. All rights reserved.
 * @url        http://www.smartosc.com
 */

/** @var \Mirasvit\Blog\Block\Post\View $block */
$post = $block->getPost();
$helper = $this->helper(\SM\InspireMe\Helper\Data::class);
?>

<div class="inspire-post-view">


    <div class="inspire-post-wapper">
        <?php if ($post->getFeaturedImageUrl()) : ?>
            <div class="post-image-large">
                <img
                     src="<?= $block->escapeUrl($helper->getImageResize($post->getFeaturedImage(), 1055, 680)) ?>"
                     alt="<?= $block->escapeHtml($post->getName()) ?>">
            </div>
        <?php endif; ?>

        <div class="inspire-post--heading">
            <h2 class="post-title"><?= $block->escapeHtml($post->getName()) ?></h2>
            <span class="post-created-date"><?= $block->escapeHtml($block->getFormatDate($post->getCreatedAt())) ?></span>

        </div>

        <div class="inspire-post-content">
            <?= /* @noEscape */ $block->getPostContent() ?>
        </div>
        <div class="inspire-post-footer gridRow-100">
            <?= $this->getChildHtml('social.sharing') ?>

            <?php $tags = $post->getTags() ?>

            <?php if ($tags->getSize()) : ?>
                <div class="inspire-tags">
                    <h3><?= $block->escapeHtml(__('Tags')) ?></h3>
                    <?php /** @var \Mirasvit\Blog\Model\Tag $tag */ ?>
                    <?php foreach ($tags as $tag) : ?>
                        <a href="<?= $block->escapeUrl($tag->getUrl())?>" class="tag-item">
                            <?= $block->escapeHtml($tag->getName()) ?>
                        </a>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

        </div>

    </div>


    <?= $this->getChildHtml('blog.post.related.products') ?>
    <?= $this->getChildHtml('blog.post.most.popular') ?>
</div>
