<?php
/** @var \SM\FlashSale\Helper\Quantity $helper */
$helper = $this->helper(\SM\FlashSale\Helper\Quantity::class);
?>

<script type="text/javascript">
    require(["jquery", "domReady!"], function ($) {
        $(document).ready(function () {
            var customurl = "<?php echo $helper->getFlashsaleUrl() ?>";
            var categoryId = <?php echo ($helper->getEventCategory() != null) ? $helper->getEventCategory()->getId() : 0 ?>;
            var loaded = false;
            if (categoryId > 0 && !loaded) {
                $.ajax({
                    url: customurl,
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        categoryId: categoryId
                    },
                    complete: function (response) {
                        if(response.responseJSON && typeof response.responseJSON.available_qty !== 'undefined') {
                            $(".product-stock").css("display", "none");
                            var availableQty = response.responseJSON.available_qty;
                            for (var i = 0; i < availableQty.length; i++) {
                                if (availableQty[i]['saleQty'] >= 0) {
                                    $(".popular-sale-count-" + availableQty[i]['productId']).text(availableQty[i]['saleQty'] + ' ' + '<?php echo __("left")?>');
                                    $(".popular-sale-count-" + availableQty[i]['productId']).css("display", "block");
                                }
                            }
                            loaded = true;
                        }
                    },
                    error: function (xhr, status, errorThrown) {

                    }
                });
            }

        });
    });
</script>