<?php
/**
 * @category    SM
 * @package     SM_Customer
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 * @author      Logan Ta <phuongtt2@smartosc.com>
 *
 * @copyright   Copyright (c) SmartOSC. All rights reserved.
 * @url http://www.smartosc.com/
 */
/** @var \SM\Customer\Block\Form\ForgotPassword $block */
if (!$block->isLoggedIn()) {
    $login = 'false';
} else {
    $login = 'true';
}
?>
<div class="block-container-lock-reset" id="tab-lock-reset" style="display: none;">

        <div class="notify-email-notification-field" id="notify-email-success-field"></div>
        <div class="block-content" aria-labelledby="block-customer-notify-email-heading">
            <fieldset class="fieldset notify-email">
                <?php if ($login == 'true'): ?>
                    <div class="txt-reset" selector="title"><?= __('Hi, %1! Your account is back.', $block->getCustomerName()) ?></div>
                    <p><?= __('We strongly suggest for you to change your password to avoid getting locked again.');?> </p>
                    <button selector="change-password"><?= __('Change Password');?></button>
                    <button selector="next" class="action primary"><?= __('Maybe Next Time');?></button>
                <?php else: ?>
                    <p selector="title"><?= __('The recovery token is expired. Reset and try again.'); ?></p>
                <?php endif; ?>
            </fieldset>
        </div>

</div>
<script type="text/x-magento-init">
    {
        "*": {
            "SM_Customer/js/lock-reset": {
                "tabLockResetSelector": "#tab-lock-reset",
                "login": "<?= $login; ?>"
            }
        }
    }
</script>

