<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<div class="help-pages">
    <!------site content------>
    <div class="help-content">
        <div class="help-search">
            <div class="control">
                <a href="#"><span class="apl-ic_search"></span></a>
                <input id="search" type="text" name="q" value=""
                       placeholder="<?= $block->escapeHtml(__('Type your topic here (example: refund)'))?>"
                       class="input-text" maxlength="128" role="combobox" aria-haspopup="false"
                       aria-autocomplete="both" autocomplete="off" aria-expanded="true"/>
            </div>
        </div>
        <div class="breadcrumbs">
            <ul class="items">
                <li class="item home">
                    <a href="#" title="Go to Home Page"><?= $block->escapeHtml(__('Home'))?></a>
                </li>
                <li class="item home">
                    <a href="#" title="help"><?= $block->escapeHtml(__('Help'))?></a>
                </li>
                <li class="item home">
                    <a href="#" title="help"><?= $block->escapeHtml(__('Return & Refund'))?></a>
                </li>
                <li class="item">
                    <strong><?= $block->escapeHtml(__('When can I return a product? What are the conditions?'))?></strong>
                </li>
            </ul>
        </div>
        <div class="help-content-list">
            <div class="help-content-list-top">
                <h2>When can I return a product? What are the conditions?</h2>
            </div>
            <div class="help-content-detail">
                <p>For most products and locations we will deliver your order tomorrow if you order before midnight and use our next-day home delivery service or order before 10pm to collect your order in store tomorrow. We don’t deliver on bank holidays. During busy times, some delivery routes may take longer than usual. Up-to-date estimates of delivery dates will be shown at checkout. To find out which delivery options are available to your postcode, click here</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
        </div>
        <div class="need-help-hand">
            <h3>Need a Helping Hand?</h3>
            <p>Transmart.com will 24/7 help you</p>

            <button class="action secondary"><?= $block->escapeHtml(__('Contact Us'))?></button>
        </div>
    </div>
    <!------site content------>

    <!------site bar left------>
    <div class="sidebar sidebar-main">
        <div class="block block-collapsible-nav">
            <div class="title block-collapsible-nav-title">

                <strong><?= $block->escapeHtml(__('Help Center'))?></strong>
            </div>
            <div class="content block-collapsible-nav-content" id="block-collapsible-nav">
                <ul class="nav items">
                    <li class="nav item">
                        <a href="http://transmart.local/customer/account/"><?= $block->escapeHtml(__('My Orders'))?></a></li>
                    <li class="nav item"><a href="#"><?= $block->escapeHtml(__('Return & Refund'))?></a></li>
                    <li class="nav item"><a href="#"><?= $block->escapeHtml(__('My Account'))?></a></li>
                    <li class="nav item"><a href="#"><?= $block->escapeHtml(__('Payment'))?></a></li>
                    <li class="nav item"><a href="#"><?= $block->escapeHtml(__('Promos & Vouchers'))?></a></li>
                    <li class="nav item"><a href="#"><?= $block->escapeHtml(__('Buying Guide'))?></a></li>
                    <li class="nav item"><a href="#"><?= $block->escapeHtml(__('About Us'))?></a></li>
                    <li class="nav item"><a href="#"><?= $block->escapeHtml(__('Delivery & Pick Up in Sto..'))?></a></li>
                    <li class="nav item"><a href="#"><?= $block->escapeHtml(__('Contact Us'))?></a></li>
                </ul>
            </div>
        </div>
    </div>
    <!------site bar left------>

</div>
