<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<div class="help-pages">
    <!------site content------>
    <div class="help-content help-contactus-wrap">
        <div class="help-content-list-top">
            <h2>What Can We Do For you?</h2>
        </div>

        <div class="help-contactus">

            <p class="tl-contact-please">Please Share the Details!</p>
            <div class="cat-select-contact">
                <label><?= $block->escapeHtml(__('Category')) ?></label>
                <div class="sortby-dropdown">
                        <span aria-haspopup="true" class="action toggle" data-toggle="dropdown">
                            <span>All</span>
                        </span>
                    <ul class="dropdown">
                        <li class="item"><a href="#">All</a></li>
                        <li class="item"><a href="#">My Order</a></li>
                        <li class="item"><a href="#">Return & Refund</a></li>
                        <li class="item"><a href="#">My Account</a></li>
                        <li class="item"><a href="#">Payment</a></li>
                        <li class="item"><a href="#">Vouchers & Promos</a></li>
                        <li class="item"><a href="#">Delivery & Pick Up in Store</a></li>
                        <li class="item"><a href="#">Buying Guide</a></li>
                        <li class="item"><a href="#">About Us</a></li>
                    </ul>
                </div>
            </div>
            <div class="help-order-to-track">
                <label><?= $block->escapeHtml(__('Order to Track')) ?></label>
                <a href="#" id="button-order-track" class="button-order-track" data-trigger="choose-order"><?= $block->escapeHtml(__('Choose Order…')) ?></a>
            </div>
            <div class="help-contact-textarea">
                <label><?= $block->escapeHtml(__('Tell us your concerns')) ?></label>
                <textarea rows="4" cols="50" placeholder="Please tell us your concerns here"></textarea>
                <p class="typ-word">140/500</p>
                <div class="input-attach-button">
                    <img src='<?= $block->getViewFileUrl('images/icon-attach.png'); ?>' alt=""/>
                    <input type="file" class="file-upload" id="file-upload"/>
                    <span id="change-text-file"><?= $block->escapeHtml(__('Attach your file here')) ?></span>
                </div>
                <div class="checkbox-custom">
                    <input type="checkbox" name="messages" checked/>
                    <label for="messages"><?= $block->escapeHtml('Send me the copy of my message') ?></label>
                </div>
                <div class="align-right">
                    <button class="action primary"
                            data-trigger="contact-submit"><?= $block->escapeHtml(__('Submit')) ?></button>
                </div>
            </div>
        </div>
    </div>
    <!------site content------>

    <!------site bar left------>
    <div class="sidebar sidebar-main">
        <div class="block block-collapsible-nav">
            <div class="title block-collapsible-nav-title">
                <strong>Help</strong>
            </div>
            <div class="content block-collapsible-nav-content" id="block-collapsible-nav">
                <ul class="nav items">
                    <li class="nav item">
                        <a href="http://transmart.local/customer/account/"><?= $block->escapeHtml(__('My Orders')) ?></a>
                    </li>
                    <li class="nav item"><a href="#"><?= $block->escapeHtml(__('Return & Refund')) ?></a></li>
                    <li class="nav item"><a href="#"><?= $block->escapeHtml(__('My Account')) ?></a></li>
                    <li class="nav item"><a href="#"><?= $block->escapeHtml(__('Payment')) ?></a></li>
                    <li class="nav item"><a href="#"><?= $block->escapeHtml(__('Promos & Vouchers')) ?></a></li>
                    <li class="nav item"><a href="#"><?= $block->escapeHtml(__('Buying Guide')) ?></a></li>
                    <li class="nav item"><a href="#"><?= $block->escapeHtml(__('About Us')) ?></a></li>
                    <li class="nav item"><a href="#"><?= $block->escapeHtml(__('Delivery & Pick Up in Sto..')) ?></a>
                    </li>
                    <li class="nav item"><a href="#"><?= $block->escapeHtml(__('Contact Us')) ?></a></li>
                </ul>
            </div>
        </div>
    </div>
    <!------site bar left------>

</div>

<div data-bind="mageInit: {
    'Magento_Ui/js/modal/modal':{
    'type': 'popup',
    'title': 'Choose Order',
    'trigger': '[data-trigger=choose-order]',
    'modalClass': 'pp-choose-order',
    'responsive': true
    }}">
    <div class="order-track-box">
        <div class="order-track-head">
            <div class="gr-date-total"><span class="date-track">28 Oct 2019</span><span
                    class="or-track-total"> Total <span class="color-red">Rp 1.738.000</span></span></div>
            <div class="gr-status"><span class="or-track-status"> Status:<span
                        class="color-blue">In Process</span></span></div>
        </div>
        <div class="order-track-content">
            <div class="gr-img">
                <img src="https://via.placeholder.com/70x70.png" alt=""/>
                <img src="https://via.placeholder.com/70x70.png" alt=""/>
                <img src="https://via.placeholder.com/70x70.png" alt=""/>
            </div>
            <div class="gr-info">
                <p> Onitsuka Tiger Mexico 66 Kill Bill, Molto Pewangi Pakaian Blue 90 ml, Alexa Pants by
                    This is April (L Size)</p>
            </div>
        </div>
    </div>
    <div class="order-track-box">
        <div class="order-track-head">
            <div class="gr-date-total"><span class="date-track">10 Oct 2019</span><span
                    class="or-track-total"> Total <span class="color-red">Rp 594.000</span></span></div>
            <div class="gr-status"><span class="or-track-status"> Status:<span
                        class="color-blue">In Delivery</span></span></div>
        </div>
        <div class="order-track-content">
            <div class="gr-img">
                <img src="https://via.placeholder.com/70x70.png" alt=""/>
                <img src="https://via.placeholder.com/70x70.png" alt=""/>

            </div>
            <div class="gr-info">
                <p> Mediheal Line Friends E.G.T. Timetox Ampoule Mask, Missha Line Friends Edition Glow Tension Cushion</p>
            </div>
        </div>
    </div>
    <div class="order-track-box">
        <div class="order-track-head">
            <div class="gr-date-total"><span class="date-track">01 Oct 2019</span><span
                    class="or-track-total"> Total <span class="color-red">Rp 25.000</span></span></div>
            <div class="gr-status"><span class="or-track-status"> Status:<span
                        class="color-red-cancel">Order Cancelled</span></span></div>
        </div>
        <div class="order-track-content">
            <div class="gr-img">
                <img src="https://via.placeholder.com/70x70.png" alt=""/>

            </div>
            <div class="gr-info">
                <p> Susu Ultra Full Cream 1L</p>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    document.getElementById("file-upload").addEventListener("change", function () {
        var fullPath = document.getElementById("file-upload").value;
        var filename = fullPath.replace(/^.*[\\\/]/, '');
        document.getElementById("change-text-file").innerHTML = filename;
    });
</script>




