<?php 
/**
 * @category Trans
 * @package  Trans_Customer
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author   Imam Kusuma <imam.kusuma@ctcorpdigital.com>
 *
 * Copyright © 2019 CT Corp Digital. All rights reserved.
 * http://www.ctcorpora.com
 */
?>

<div class="auth-page otp-auth">
	<form class="form create account form-create-account" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off" data-mage-init='{"validation":{}}'>
	    <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
	    <?php echo $block->getRegisterForm(); ?>
		<?php echo $block->getChildHtml('field.otp') ?>

		<div class="actions-toolbar">
	        <div class="primary">
	            <button type="submit" class="action submit primary" title="<?= $block->escapeHtmlAttr(__('Continue')) ?>"><span><?= $block->escapeHtml(__('Continue')) ?></span></button>
	        </div>
	    </div>
	</form>
</div>

<style type="text/css">
	.field-otp {
		display: block;
	}
</style>