<?php
/**
 * @project    ct-corp-transmart
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author     Duc Nguyen Hoang <ducnh2@smartosc.com>
 * @copyright  Copyright © 2020 SmartOSC. All rights reserved.
 * @url        http://www.smartosc.com
 */

/** @var \SM\Customer\Block\Widget\VerifyEmail $block */
$verified = $block->getVerifiedEmail();
?>

    <div class="notification-verify-email" id="notification-verify-email" style="display:none;">
        <div class="top-container">
            <i class="notification-icon"></i>
            <span class="notification-verify-email-content">
                <?= __('Let\'s verify your account! It\'s as easy as completing your profile.') ?>
            </span>
            <a href="<?= $block->escapeUrl($block->getMyAccountUrl()) ?>">
                <button class="action primary"><?= __('Complete Now') ?></button>
            </a>
            <button class="close-button" id="close-notification"></button>
        </div>

    </div>

    <script type="text/javascript">
        require([
            'jquery',
            'domReady!'
        ], function ($) {
            $.ajax({
                url: "<?= $block->escapeUrl($block->validateWidget()); ?>",
                type: 'POST',
                dataType: 'json',
                success: function (response) {
                    if (response === false) {
                        $('#notification-verify-email').remove();
                    } else {
                        $('#notification-verify-email').css('display', '');
                    }
                }
            });

            $('#close-notification').click(function () {
                $('#notification-verify-email').remove();
                $.ajax({
                    url: "<?= $block->escapeUrl($block->getCloseActionUrl()); ?>",
                    type: 'POST',
                    dataType: 'json',
                    success: function (response) {
                    }
                })
            });
        });
    </script>
