<?php
use SM\StoreLocator\Block\StoreLocation\Listing;

/**
 * @var Listing $block
 */

?>
<div id="store-locator" data-bind="scope:'store-location-listing'">

    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
       {
           "#store-locator": {
               "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
           }
       }
   </script>

    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
            return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
        })
    </script>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "SM_StoreLocator/js/view/location-view":{
            "apiKey":"https://maps.googleapis.com/maps/api/js?key=<?php echo $block->getGoogleApiKey();?>&libraries=places"
        }
    }
}
</script>
