<?php
/**
 * @project    ct-corp-transmart
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author     Duc Nguyen Hoang <ducnh2@smartosc.com>
 * @copyright  Copyright © 2020 SmartOSC. All rights reserved.
 * @url        http://www.smartosc.com
 */

/** @var SM\InspireMe\Block\Post\View\MostPopular $block */
$listPost = $block->getMostPopularPosts();
if (!count($listPost)) {
    return;
}
$GTMViewModel = $block->getData('gtm_view_model');
?>
<div class="blog__post-view blog__post-view-most-popular">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Most Popular Articles')) ?></strong>
        <a class="section-link inspire-see-all"
           href="<?= $block->escapeUrl($block->getSeeAllUrl()) ?>"
        >
            <?= $block->escapeHtml(__('See all')) ?>
        </a>
    </div>

    <div class="block-content inspire-post-listing">
        <div class="row">
        <?php foreach ($listPost as $post): ?>
            <?php if ($post) : ?>
                <?php $GTMViewModel ? $data = $GTMViewModel->getGtm($post) : $data = null; ?>
            <div class="col-xs-12 col-sm-6 col-md-4">
                <div class="post-item-content">
                <?php if ($post->getFeaturedImageUrl()): ?>
                    <div class="post-image">
                        <a class="fade-img" href="<?= $block->escapeUrl($post->getUrl()) ?>"
                           title="<?= $block->escapeHtml($post->getName()) ?>"
                            <?php if ($data) : ?>
                                data-gtm-event="<?= \SM\InspireMe\Helper\Data::GTM_POST_EVENT_CLICK_VIEW ?>"
                                data-gtm="<?= $block->escapeHtml($data) ?>"
                                data-gtm-name="<?= \SM\InspireMe\Helper\Data::GTM_POST_DATA_NAME ?>"
                            <?php endif; ?>
                        >
                            <img class="lazy-loaded" loading="lazy" width="470" height="260"
                                 src="<?= $block->escapeUrl($block->getImageResize($post->getFeaturedImage(), 470, 260)) ?>"
                                 alt="<?= $block->escapeHtml($post->getName()) ?>">
                        </a>
                    </div>
                <?php endif; ?>
                 <div class="post-info">
                     <div class="post-info-date">
                         <?php $topics = $post->getCategories()->excludeRoot() ?>
                         <?php if ($topics->getSize()): ?>
                             <?php /** @var \Mirasvit\Blog\Model\Category $firstTopic */?>
                             <?php $firstTopic = $topics->getFirstItem() ?>
                             <span class="post-tag"><?= $block->escapeHtml($firstTopic->getName()) ?></span>
                         <?php endif; ?>
                         <span class="post-created-date"><?= $block->escapeHtml($block->getFormatDate($post->getCreatedAt())) ?></span>
                     </div>
                     <a href="<?= $block->escapeUrl($post->getUrl()) ?>"
                        title="<?= $block->escapeHtml($post->getName()) ?>"
                        class="post-title"
                     >
                         <h3 ><?= $block->escapeHtml($post->getName()) ?></h3>
                     </a>
                     <p class="post-description"><?= $block->escapeHtml($post->getShortContent()) ?></p>
                     <a href="<?= $block->escapeUrl($post->getUrl()) ?>"
                        title="<?= $block->escapeHtml($post->getName()) ?>"
                        class="post-readmore"
                         <?php if ($data) : ?>
                             data-gtm-event="<?= \SM\InspireMe\Helper\Data::GTM_POST_EVENT_CLICK_VIEW ?>"
                             data-gtm="<?= $block->escapeHtml($data) ?>"
                             data-gtm-name="<?= \SM\InspireMe\Helper\Data::GTM_POST_DATA_NAME ?>"
                         <?php endif; ?>
                     >
                         <?= $block->escapeHtml(__('Read More'))?>
                     </a>
                </div>
                </div>
            </div>
            <?php endif; ?>
        <?php endforeach ?>
        </div>
    </div>
</div>
