<?php

/**
 * @project    ct-corp-transmart
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author     Duc Nguyen Hoang <ducnh2@smartosc.com>
 * @copyright  Copyright © 2020 SmartOSC. All rights reserved.
 * @url        http://www.smartosc.com
 */

?>
<div class="social-share">
    <div class="title-social-share"><?= $block->escapeHtml(__('Share this article via')) ?></div>
    <div id="social-bt" class="social-bt"></div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "SM_Catalog/js/social/social-share": {}
        }
    }
</script>
