<?php
/**
 * @project    ct-corp-transmart
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author     Duc Nguyen Hoang <ducnh2@smartosc.com>
 * @copyright  Copyright © 2020 SmartOSC. All rights reserved.
 * @url        http://www.smartosc.com
 */

/**
 * @var \SM\InspireMe\Block\Post\View\ViewsCount $block
 */
?>
<script>
    require(['jquery', 'domReady!'], function ($) {
        setTimeout(function () {
            $.ajax({
                url: "<?= $block->escapeUrl($block->getCounterUrl());?>",
                type: 'POST',
                dataType: 'json',
                success: function (response) {
                }
            })
        }, 10000);
    });
</script>


