<?php $helper = $this->helper('MGS\Ajaxscroll\Helper\Data') ?>

<script type="text/javascript">
	require([
		"jquery",
		"jquery/ui",
		"ajaxscroll"
	], function($){
		$(document).ready(function(){
			var ajaxscroll = $.scroll({
				wrapperSelector : '.products.wrapper',
				itemSelector: '.product-item',
				paginationSelector: '.pages-items .item',
				nextSelector: '.pages-items .next'
			});

			ajaxscroll.extension(new scrollLoading({html: '<div class="ajax-scroll-loading"><img src="<?php echo $helper->getLoadingImageUrl($this->getViewFileUrl('MGS_Ajaxscroll::images/loader.gif')) ?>" /></div>'}));
		});
	});
</script>
