<?php
/** @var \Magento\MultipleWishlist\Block\Customer\Wishlist\Management $block */

/** @var \Magento\Wishlist\Model\Wishlist[] $wishlists */
$wishlists = $block->getWishlists()->getItems();
$defaultId = $block->getDefaultWishlist()->getId();
/** @var \SM\ShoppingList\ViewModel\MyListViewModel $viewModel */
$viewModel = $block->getData("viewModel");
if (isset($wishlists[$defaultId])) {
    unset($wishlists[$defaultId]);
}
?>
<div class="shopping-lists">
    <div class="product data items">
        <div class="item title">
            <a class="switch" href="<?= $block->getUrl("wishlist/index/index", ['wishlist_id' => $defaultId]) ?>"><?= $block->escapeHtml(__('My Favorites')) ?></a>
        </div>
        <div class="item title active">
            <a class="switch"><?= $block->escapeHtml(__('My Lists')) ?></a>
        </div>
        <input name="form_key" type="hidden" value="<?= $block->escapeHtml($block->getFormKey()) ?>" />
        <div id="tab-mylists" class="item content" data-role="content">
            <?php if (count($wishlists) > 0): ?>
                <div class="mylists-grid wishlist">
                    <ol class="mylists-items" id="mylists-lists">
                        <?php
                        /** @var \Magento\Wishlist\Model\Wishlist $wishlist */
                        foreach ($wishlists as $wishlist): ?>
                        <li class="mylists-item" id="item_<?= $block->escapeHtmlAttr($wishlist->getId()) ?>">
                            <div class="mylists-item-info">
                                <div class=mylists-item-header">
                                    <h5 class="mylists-title"><?= $wishlist->getName() ?></h5>

                                    <?php /** @var \SM\ShoppingList\Block\Toolbar $settingBlock */
                                    $settingBlock = $block->getChildBlock("customer.shoppinglist.mylists.settings")
                                    ?>
                                    <?= $settingBlock->setShoppingList($wishlist)->toHtml() ?>

                                </div>
                            </div>
                            <div class="mylists-item-content">
                                <a class="mylists preview-product" href="<?= $block->getUrl("wishlist/index/index", ["wishlist_id" => $wishlist->getId()])?>">
                                    <?php $n = 1; $left = 0;?>
                                    <?php
                                    /** @var \Magento\Wishlist\Model\Item $item */
                                    foreach ($wishlist->getItemCollection()->getItems() as $item): ?>
                                        <?php if ($n <= 4): ?>
                                            <img class="" loading="lazy" src="<?= $viewModel->getImageUrl($item->getProduct()) ?>" height="80px"  alt="<?= $block->escapeHtml('item ' . $n)?>">
                                        <?php else:?>
                                            <?php $left++; ?>
                                        <?php endif;?>
                                        <?php $n++;?>
                                    <?php endforeach; ?>

                                    <?php if ($wishlist->getItemCollection()->count() == 0): ?>
                                        <img loading="lazy" src="<?= $block->getViewFileUrl('images/shopping-list-empty.png')?>" height="80px"/>
                                        <h4 style="display: inline-flex; align-items: center;"><?= $block->escapeHtml(__('This list is still empty'))?></h4>
                                    <?php endif;?>
                                    <?php if ($left  > 0): ?>
                                        <span class="extra-product-count"><?= $block->escapeHtml(__('+ ' . $left . ' more products')) ?></span>
                                    <?php endif;?>
                                </a>
                            </div>
                        </li>
                        <?php endforeach; ?>
                    </ol>
                </div>
            <?php else: ?>
                <div class="no-route shopping-list-empty">
                    <div class="no-route-info">
                        <img src="<?=$block->getViewFileUrl('images/shopping-list-empty.png')?>" alt="Your list is still empty" width="401"/>
                        <h4><?= $block->escapeHtml(__('You haven’t made any lists yet.')) ?><br/>
                            <?= $block->escapeHtml(__('Create your lists and save your favorite products!')) ?>
                        </h4>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
