<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>


<div class="giftMainList">
    <?php
    echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('gift-sharedme')
        ->toHtml();
    ?>


    <div class="block-giftRegistry-list">

        <div class="giftRegistry-list--content">
            <div class="box-gift-list box-gift-list--service">
                <div class="row">
                    <div class="col-xs-12 col-xl-4">
                        <div class=" widget block-gift-services">
                            <div class="block-title">
                                <i class="icon-gift icon-gift-up"></i>
                                <span class="block-title-inner">Up to 20% Off</span>
                            </div>
                            <div class="block-content">
                                <p>Enjoy a special completion discount </p>
                                <p>   on any items left on your registry</p>

                            </div>
                        </div>

                    </div>
                    <div class="col-xs-12 col-xl-4">
                        <div class=" widget block-gift-services">
                            <div class="block-title">
                                <i class="icon-gift icon-gift-ship"></i>
                                <span class="block-title-inner">Fast & FreeShipping</span>
                            </div>
                            <div class="block-content">
                                <p>Two day shipping on eligible registry</p>
                                <p> items - you’ll get your gifts in a snap</p>


                            </div>
                        </div>

                    </div>
                    <div class="col-xs-12 col-xl-4">
                        <div class=" widget block-gift-services">
                            <div class="block-title">
                                <i class="icon-gift icon-gift-easy"></i>
                                <span class="block-title-inner">Easy Returns</span>
                            </div>
                            <div class="block-content">
                                <p>Don’t like it ? You can return any</p>
                                <p>   gifts within 180 days.</p>

                            </div>
                        </div>

                    </div>


                </div>
            </div>
        </div>
    </div>

    <div class="block-giftRegistry-terms">
        <div class="block widget block-dashboard-info">
            <div class="block-title">
                <strong>Terms & Conditions of Gift Registry</strong>
            </div>
            <div class="block-content">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </p>

            </div>
        </div>
    </div>

</div>

<script>
    require(
        [
            'jquery',
        ],
        function(
            $,
            modal
        ) {
            ToxProgress.create();
            ToxProgress.animate();




        }
    );
</script>
