<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Customer\Block\Account\Customer $block */
?>
<?php if ($block->customerLoggedIn()) : ?>
    <li class="customer-welcome">
        <button type="button"
                class="action switch"
                tabindex="-1"/>
        <div class="customer-name"
              data-role="dropdownDialog"
              data-mage-init='{"dropdownDialog":{
                 "appendTo":".customer-welcome",
                 "triggerTarget":".header.links",
                 "triggerEvent":"hover touchend",
                 "timeout": "500",
                 "closeOnMouseLeave": true,
                 "closeOnEscape": true,
                 "parentClass":"active",
                 "buttons":[]}}'
              data-bind="scope: 'customer'">
            <?php if ($block->getChildHtml()) :?>
                <div class="customer-menu" data-target="dropdown">
                    <?= $block->getChildHtml() ?>
                </div>
            <?php endif; ?>
        </div>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
    </li>
<?php endif; ?>
