<?php

/**
 * @category  SM
 * @package   SM_Catalog
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 * @author    Logan Ta <phuongtt2@smartosc.com>
 *
 * @copyright 2020 Copyright (c) SmartOSC. All rights reserved.
 * @url http://www.smartosc.com/
 */

?>
<div class="social-share">
    <div class="title-social-share"><?= $block->escapeHtml(__('Share')) ?></div>
    <div id="social-bt" class="social-bt"></div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "SM_Catalog/js/social/social-share": {}
        }
    }
</script>
