<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
/** @var \SM\Catalog\Helper\Data $helper */
$helper = $this->helper('SM\Catalog\Helper\Data');
$shoppingListHelper = $this->helper('SM\ShoppingList\Helper\Data');
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $type = 'product-items  row';

    $mode = 'grid';

    $image = 'product_small_image';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = false;
    $showCart = $block->getData('show_cart');

    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    $productCount = $block->getData('products_count');
    $showProductCount = 4;
    if($productCount== 5){
        $showProductCount = "col-md-15";
    }else{
        $showProductCount = "col-md-".floor(12/$productCount);
    }
    ?>
    <div class=" widget block-products-list <?= /* @noEscape */ $mode ?>">
        <div class="block-title">
            <?php if ($block->getTitle()) : ?>
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            <?php endif ?>
            <?php if ($link = $block->getData('link')) : ?>
                <a data-gtm-product="<?= $block->getTitle() ?>" class="see-all-grid <?= $block->getTitle() ? $block->toClassName($block->escapeHtml(__($block->getTitle()))) : "" ?>" href="<?= $block->escapeUrl($link)?>"><?= __('See All') ?></a>
            <?php endif ?>
        </div>

        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-cards <?= /* @noEscape */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item) : ?>
                        <?php /** @var \Magento\Catalog\Model\Product $_item */ ?>
                        <?php $dataGTM = $block->escapeHtml($block->getGtm($_item)); ?>
                    <?php if ($helper->isProductStockStatus($_item->getId())): ?>
                        <?php $showCart = ($showCart == 2) ? !$_item->getData('hide_cta_button') : $showCart; ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-card col-xs-6 col-sm-4 '.$showProductCount.'">' : '</li><li class="product-card  col-xs-6 col-sm-4 '.$showProductCount.'">' ?>
                        <div class="product-item <?php if (!$showCart) : ?>product-item--hideCart<?php endif; ?>">
                            <div class="product-item-info">
                            <div class="product-item-photo-wrapper">
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo"
                                   <?php if ($dataGTM) : ?>
                                   data-gtm-product='<?= $dataGTM ?>'
                                   data-position="<?= $iterator - 1 ?>"
                                   <?php endif; ?>
                                >
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>


                                <?php $count = $helper->countChildren($_item); ?>
                                <?php if ($count): ?>
                                    <div class="swatch-options">
                                        <span class="oval-swatch oval-black"></span>
                                        <span class="oval-swatch oval-pink"></span>
                                        <span class="oval-swatch oval-dark-blue"></span>
                                        <span class="oval-swatch oval-dark-blue2"></span>
                                        <span class="oval-number"><?= $count ?></span>
                                    </div>
                                <?php endif; ?>
                            </div>
                            <div class="product details product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link <?= $_item->getId() ?>lp"
                                       <?php if ($dataGTM) : ?>
                                       data-gtm-product='<?= $dataGTM ?>'
                                       data-position="<?= $iterator - 1 ?>"
                                       <?php endif; ?>>
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>

                                <?= $block->getProductPriceHtml($_item, $type) ?>
                                <?php if ($templateType && $block->getData("show_review") == "true") :?>
                                    <?php
                                    $ratingSummary = $helper->getRattingSummary($_item->getSku());
                                    $reviewCount = $helper->getRattingCount($_item->getSku());
                                    ?>
                                    <div class="product-reviews-summary short<?= !$ratingSummary ? ' no-rating' : '' ?>" onclick="location.href = '<?= $block->getProductUrl($_item)?>'">
                                        <div class="rating-summary">
                                            <div class="rating-result" title="<?= $block->escapeHtmlAttr($ratingSummary) ?>%">
                                                <span style="width:<?= $ratingSummary ?>%"><span><?= $block->escapeHtml($ratingSummary) ?>%</span></span>
                                            </div>
                                        </div>
                                        <span class="rating-count reviews-actions">(<?= $block->escapeHtml($reviewCount) ?>)</span>
                                    </div>
                                <?php endif; ?>

                                <?= $block->getProductDetailsHtml($_item) ?>

                                <?php if ($showCompare || $showCart || $showWishlist) : ?>
                                    <div class="product-item-inner">
                                        <div class="product-item-actions">
                                            <?php if ($showCart) : ?>
                                                <div class="actions-primary">
                                                    <?php $childrenIds = $_item->getTypeInstance()->getChildrenIds($_item->getId()); ?>
                                                    <?php if ($childrenIds): ?>
                                                        <a title="<?= $block->escapeHtmlAttr(__('View Details')) ?>"
                                                           href="<?= $block->escapeUrl($_item->getProductUrl()) ?>"
                                                           class="action view-details primary"
                                                           <?php if ($dataGTM) : ?>
                                                           data-gtm-product='<?= $dataGTM ?>'
                                                           data-position="<?= $iterator - 1 ?>"
                                                           <?php endif; ?>>
                                                            <?= $block->escapeHtml(__('View Details')) ?>
                                                        </a>
                                                    <?php else : ?>
                                                        <?php if ($_item->isSaleable()) : ?>
                                                            <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                                <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                                <div class="update-cart-qty">
                                                                    <input type="hidden" name="item_id" value="0"/>
                                                                    <input type="hidden" name="qty_type" value="1"/>
                                                                    <button type="submit"
                                                                            title="<?= $block->escapeHtmlAttr(__('Decrease qty')) ?>"
                                                                            class="action decrease-qty"
                                                                            <?php if ($dataGTM) : ?>
                                                                                data-gtm-product='<?= $dataGTM ?>'
                                                                                data-position="<?= $iterator - 1 ?>"
                                                                            <?php endif; ?>>
                                                                        <span><?= __('-') ?></span>
                                                                    </button>
                                                                    <label for="item_qty" class="label-item-qty">
                                                                        <input type="number" name="item_qty" value="0"/>
                                                                    </label>
                                                                    <button type="submit" title="<?= $block->escapeHtmlAttr(__('Increase qty')) ?>"
                                                                            value="increase" class="action increase-qty"
                                                                            <?php if ($dataGTM) : ?>
                                                                                data-gtm-product='<?= $dataGTM ?>'
                                                                                data-position="<?= $iterator - 1 ?>"
                                                                            <?php endif; ?>>
                                                                        <span><?= __('+') ?></span>
                                                                    </button>
                                                                </div>
                                                                <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                <?= $block->getBlockHtml('formkey') ?>
                                                                <button type="submit"
                                                                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                        class="action tocart primary"
                                                                        <?php if ($dataGTM) : ?>
                                                                        data-gtm-product='<?= $dataGTM ?>'
                                                                        data-position="<?= $iterator - 1 ?>"
                                                                        <?php endif; ?>>
                                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                </button>
                                                            </form>
                                                        <?php else : ?>
                                                            <?php if ($_item->getIsSalable()) : ?>
                                                                <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                            <?php else : ?>
                                                                <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>

                                            <?php if ($showCompare) : ?>
                                                <div class="actions-secondary" data-role="add-to-links">
                                                    <?php //phpcs:disable?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                                        <?php //phpcs:disable?>
                                                        <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                                        <?php //phpcs:enable?>
                                                        <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($shoppingListHelper->isActiveShoppingList()):?>
                                            <?php
                                                $isAddedShoppingList = $shoppingListHelper->isAddedShoppingList($_item->getId())? 'true':'false';
                                                $getMyFavoritesListDefaultId = $shoppingListHelper->getMyFavoritesListDefaultId();
                                            ?>
                                            <a style="cursor: pointer"
                                               id="shoppinglist-add-<?= $_item->getId() ?>"
                                               class="action towishlist"
                                               <?php if ($dataGTM) : ?>
                                               data-gtm-product='<?= $dataGTM ?>'
                                               data-position="<?= $iterator - 1 ?>"
                                               <?php endif; ?>
                                               title="<?= $block->escapeHtmlAttr(__('Add to Shopping List')) ?>">
                                                <span><?= $block->escapeHtml(__('Add to Shopping List')) ?></span>
                                            </a>
                                            <a style="cursor: pointer; display: none;"
                                               id="shoppinglist-remove-<?= $_item->getId() ?>"
                                               class="action remove towishlist"
                                               title="<?= $block->escapeHtmlAttr(__('Remove to Shopping List')) ?>">
                                                <span><?= $block->escapeHtml(__('Remove to Shopping List')) ?></span>
                                            </a>

                                            <div id="success-alert-modal-<?= $_item->getId() ?>" class="content add-success-modal" style="display:none;">
                                                <div class="product-info">
                                                    <img src="<?= $block->getImage($_item, "product_base_image")->getData("image_url");
                                                    ?>" width="124px"  alt="<?= $_item->getName() ?>"/>
                                                    <div class="success-content">
                                                        <span class="product-name"><?= $block->escapeHtml($_item->getName()) ?></span>
                                                        <h3><?= $block->escapeHtml(__("This item has been added to"))?></h3>
                                                        <ul id="destination-list-<?= $_item->getId() ?>" style="list-style-type: none;">
                                                        </ul>
                                                    </div>
                                                </div>

                                            </div>
                                            <script type="text/x-magento-init">
                                            {
                                                "*": {
                                                    "AddFromList":{
                                                        "product_id":"<?= $_item->getId() ?>",
                                                        "store_id":"<?= $_item->getStoreId() ?>",
                                                        "add_item_url":"<?= $block->getUrl("shoppinglist/ajax/additems")?>",
                                                        "remove_item_url":"<?= $block->getUrl("shoppinglist/ajax/removeitem")?>",
                                                        "is_added_shopping_list":"<?php echo $isAddedShoppingList ?>",
                                                        "my_favorite_id": "<?= $getMyFavoritesListDefaultId ?>"
                                                    }
                                                }
                                            }
                                            </script>
                                            <?php endif;?>
                                        </div>
                                    </div>
                                <?php endif; ?>

                                <?php $percent = $block->getDiscountPercent($_item); ?>
                                <?php if ($percent != null && $percent > 0) : ?>
                                    <span class="product-sale">
                                        <?= $block->escapeHtml(__('%1% OFF', $percent)); ?>
                                     </span>
                                <?php endif; ?>
                            </div>
                            </div>
                        </div>
                    <?php endif; ?>
                        <script>
                            require(['jquery', "gtmProduct", 'domReady!'], function ($, gtm) {
                                if (typeof dataLayerSourceObjects !== 'undefined') {
                                    $(window).load(function () {
                                        let data = $('.product-item-link.<?= $_item->getId() ?>lp').attr("data-gtm-product");

                                        if (data) {
                                            try {
                                                data = JSON.parse(data);
                                                data['position'] = $('.product-item-link.<?= $_item->getId() ?>lp').attr("data-position");
                                                gtm.push("product_view", data);
                                            } catch (e) {

                                            }
                                        }
                                    });
                                }
                            });
                        </script>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
    <script>
        require(['jquery', "gtmProduct", 'Magento_Ui/js/lib/view/utils/async', 'domReady!'], function ($, gtm, async) {
            if (typeof dataLayerSourceObjects !== 'undefined') {
                window.eventCreate = window.eventCreate || {};
                async.async('.product-item-link', function () {
                    if (!eventCreate['.product-item-link']) {
                        eventCreate['.product-item-link'] = 0;
                    }

                    let current = $($('.product-item-link')[eventCreate['.product-item-link']]);
                    $(current).click(function (e) {
                        e.preventDefault();
                        let data = $(this).attr("data-gtm-product");
                        let url = $(this).attr('href');

                        if (data) {
                            try {
                                data = JSON.parse(data);
                                data['eventCallback'] = function () {
                                    document.location = url;
                                };
                                data['position'] = $(this).attr("data-position");
                                gtm.push("productClick", data);
                            } catch (e) {
                                window.location = url;
                            }
                        } else {
                            window.location = url;
                        }
                    });
                    eventCreate['.product-item-link']++;
                });
                async.async('.action.view-details.primary', function () {
                    if (!eventCreate['.action.view-details.primary']) {
                        eventCreate['.action.view-details.primary'] = 0;
                    }

                    let current = $($('.action.view-details.primary')[eventCreate['.action.view-details.primary']]);
                    $(current).click(function (e) {
                        e.preventDefault();
                        let data = $(this).attr("data-gtm-product");
                        let url = $(this).attr('href');

                        if (data) {
                            try {
                                data = JSON.parse(data);
                                data['eventCallback'] = function () {
                                    document.location = url;
                                };
                                data['position'] = $(this).attr("data-position");
                                gtm.push("productClick", data);
                            } catch (e) {
                                window.location = url;
                            }

                        } else {
                            window.location = url;
                        }
                    });
                    eventCreate['.action.view-details.primary']++;
                });
                async.async('.product-item-photo', function () {
                    if (!eventCreate['.product-item-photo']) {
                        eventCreate['.product-item-photo'] = 0;
                    }

                    let current = $($('.product-item-photo')[eventCreate['.product-item-photo']]);
                    $(current).click(function (e) {
                        e.preventDefault();

                        let data = $(this).attr("data-gtm-product");
                        let url = $(this).attr('href');

                        if (data) {
                            try {
                                data = JSON.parse(data);
                                data['eventCallback'] = function () {
                                    document.location = url;
                                };
                                data['position'] = $(this).attr("data-position");
                                gtm.push("productClick", data);
                            } catch (e) {
                                window.location = url;
                            }
                        } else {
                            window.location = url;
                        }
                    });
                    eventCreate['.product-item-photo']++;
                });
                async.async('.action.towishlist', function () {
                    if (!eventCreate['.action.towishlist']) {
                        eventCreate['.action.towishlist'] = 0;
                    }

                    let current = $($('.action.towishlist')[eventCreate['.action.towishlist']]);
                    $(current).click(function (e) {
                        let data = $(this).attr("data-gtm-product");

                        if (data) {
                            try {
                                data = JSON.parse(data);
                                data['position'] = $(this).attr("data-position");
                                gtm.push("add_to_favorite", data);
                            } catch (e) {

                            }
                        }
                    });
                    eventCreate['.action.towishlist']++;
                });
                async.async('.action.tocart.primary', function () {
                    if (!eventCreate['.action.tocart.primary']) {
                        eventCreate['.action.tocart.primary'] = 0;
                    }

                    let current = $($('.action.tocart.primary')[eventCreate['.action.tocart.primary']]);
                    $(current).click(function (e) {
                        let data = $(this).attr("data-gtm-product");

                        if (data) {
                            try {
                                data = JSON.parse(data);
                                data['position'] = $(this).attr("data-position");
                                gtm.push("addToCart", data);
                            } catch (e) {

                            }
                        }
                    });
                    eventCreate['.action.tocart.primary']++;
                });

                async.async('.action.increase-qty', function () {
                    if (!eventCreate['.action.increase-qty']) {
                        eventCreate['.action.increase-qty'] = 0;
                    }

                    let current = $($('.action.increase-qty')[eventCreate['.action.increase-qty']]);
                    $(current).click(function (e) {
                        let data = $(this).attr("data-gtm-product");

                        if (data) {
                            try {
                                data = JSON.parse(data);
                                data['position'] = $(this).attr("data-position");
                                gtm.push("addToCart", data);
                            } catch (e) {

                            }
                        }
                    });
                    eventCreate['.action.increase-qty']++;
                });

                async.async('.action.decrease-qty', function () {
                    if (!eventCreate['.action.decrease-qty']) {
                        eventCreate['.action.decrease-qty'] = 0;
                    }

                    let current = $($('.action.decrease-qty')[eventCreate['.action.decrease-qty']]);
                    $(current).click(function (e) {
                        let data = $(this).attr("data-gtm-product");

                        if (data) {
                            try {
                                data = JSON.parse(data);
                                data['position'] = $(this).attr("data-position");
                                gtm.push("removeFromCart", data);
                            } catch (e) {

                            }
                        }
                    });
                    eventCreate['.action.decrease-qty']++;
                });
            }
        });
    </script>
    <?php if ($link = $block->getData('link')) : ?>
        <script>
            require(['jquery', 'moment', 'gtmProduct', 'Magento_Ui/js/lib/view/utils/async','domReady!'], function ($, moment, gtm, async) {
                if (typeof dataLayerSourceObjects !== 'undefined') {
                    window.eventCreate = window.eventCreate || {};
                    async.async('.see-all-grid', function () {
                        if (!eventCreate['.see-all-grid']) {
                            eventCreate['.see-all-grid'] = 0;
                        }

                        let current = $($('.see-all-grid')[eventCreate['.see-all-grid']]);
                        $(current).click(function () {
                            let data = [];
                            data['shop_category'] = $(this).attr("data-gtm-product");
                            gtm.push("see_all_category_page", data);
                        });

                        eventCreate['.see-all-grid']++;
                    });
                }
            });
        </script>
    <?php endif ?>
    <?php if (!$block->isRedirectToCartEnabled()) :?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCartAdvanced": {
                    "product_sku": "<?= $block->escapeJs($_item->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif;?>
