<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist $block */
/** @var SM\ShoppingList\Helper\Data $helper */

$shoppingListHelper = $this->helper('SM\ShoppingList\Helper\Data');

?>
<?php if ($shoppingListHelper->isActiveShoppingList()): ?>
    <?php
    $product = $block->getProduct();
    $productImage = $block->getImage($product, "product_base_image")->getData("image_url");
    $productName = $product->getName();
    $productId = $product->getId();
    ?>
    <a style="cursor: pointer"
       id="shoppinglist-add-<?= $productId ?>"
       class="action towishlist"
       title="<?= $block->escapeHtmlAttr(__('Add to Shopping List')) ?>"
       aria-label="<?= $block->escapeHtmlAttr(__('Add to Shopping List')) ?>"
       data-product-id="<?= $block->escapeHtml($productId)?>"
       role="button">
        <span><?= $block->escapeHtml(__('Add to Shopping List')) ?></span>
    </a>
    <div id="success-alert-modal-<?= $productId ?>" class="content add-success-modal" style="display:none;">
        <div class="product-info">
            <img src="<?= $productImage ?>" width="124px" alt="<?= $productName ?>"/>
            <div class="success-content">
                <span class="product-name"><?= $block->escapeHtml($productName) ?></span>
                <h3><?= $block->escapeHtml(__("This item has been added to")) ?></h3>
                <ul id="destination-list-<?= $productId ?>" style="list-style-type: none;">
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php if ($shoppingListHelper->isActiveShoppingList()):?>
    <script type="text/x-magento-init">
    {
        "*": {
            "AddFromList":{}
        }
    }
    </script>
<?php endif;?>
