<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \SM\Catalog\Block\Product\View\Addto\Compare */
if ($block->isAllowAddToComepare()):
?>

<?php $viewModel = $block->getData('addToCompareViewModel'); ?>
<?php $product = $block->getProduct();?>
    <?php if($product->getTypeId() == 'simple' ||  $product->getTypeId() == 'configurable'):?>
        <div class="split button">
            <a id="add-compare" href="#" data-role="add-to-links" class="action tocompare">
                <svg aria-hidden="true" focusable="false" data-prefix="fal" data-icon="exchange" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="svg-inline--fa svg-icon-exchange fa-w-16 fa-2x">
                    <path fill="currentColor" d="M508.485 184.485l-92.485 92c-4.687 4.686-12.284 4.686-16.97 0l-7.071-7.07c-4.687-4.686-4.687-12.284 0-16.971L452.893 192H12c-6.627 0-12-5.373-12-12v-8c0-6.627 5.373-12 12-12h440.905l-60.946-60.444c-4.687-4.686-4.687-12.284 0-16.971l7.07-7.07c4.687-4.686 12.284-4.686 16.971 0l92.485 92c4.687 4.686 4.686 12.284 0 16.97zm-504.97 160l92.485 92c4.687 4.686 12.284 4.686 16.971 0l7.07-7.07c4.687-4.686 4.687-12.284 0-16.971L59.095 352H500c6.627 0 12-5.373 12-12v-8c0-6.627-5.373-12-12-12H59.107l60.934-60.444c4.687-4.686 4.687-12.284 0-16.971l-7.071-7.07c-4.686-4.686-12.284-4.687-16.97 0l-92.485 92c-4.686 4.686-4.687 12.284 0 16.97z" class=""></path>
                </svg>
                <span><?= $block->escapeHtml(__('Add to Compare Products')) ?></span>
            </a>
        </div>
    <?php endif; ?>
<?php endif; ?>
<?php $product = $block->getProduct();?>
<script>
    require([
            'jquery',
            'Magento_Ui/js/modal/confirm'
        ],
        function($, confirmation) {
            if($('#add-compare').length > 0) $('.product-add-form').addClass('product-addto-break');
            $('#add-compare').on('click', function (e){
                e.preventDefault();

                var message = '<?php echo __('Item does not belong to the same category as the item in current comparison list. Adding it to comparison list will replace the current comparison. Do you want to continue?') ?>';
                var customUrl = "<?php echo $this->getUrl().'catalog/product_compare/check'?>";
                var productId = "<?php echo $product->getId() ?>";
                $.ajax({
                    url: customUrl,
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        productId: productId
                    },
                    complete: function(response) {
                        clearList = response.responseJSON.clearList;
                        if(clearList == true){
                            confirmation({
                                title: 'Same Category Warning',
                                content: message,
                                actions: {

                                    confirm: function () {
                                        var url = '<?php echo $this->getUrl('catalog/product_compare/customadd',['_query' => ['product' => $product->getId(),'isremove' => true ]])?>';
                                        window.location.href = url;
                                    },

                                    cancel: function () {
                                        e.preventDefault();
                                        return false;
                                    }
                                }
                            });
                        }else{
                            var url = '<?php echo $this->getUrl('catalog/product_compare/customadd',['_query' => ['product' => $product->getId(),'isremove' => false ]])?>';
                            window.location.href = url;
                        }
                    },
                    error: function (xhr, status, errorThrown) {

                    }
                });
            });
        });
</script>

