<?php
/**
 * @category Trans
 * @package  Trans_CustomerMyProfile
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 *
 * @author   Dwi Septha Kurniawan <septha.kurniawan@transdigital.co.id>
 *
 * Copyright © 2019 PT Trans Digital. All rights reserved.
 * http://www.ctcorpora.com
 */
?>
<div class="block block-dashboard-info">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Password')) ?></strong>
        <a class="action edit primary" href="<?= $block->escapeUrl($block->getUrl('customermyprofile/myprofile/changepassword')) ?>">
            <span><?= $block->escapeHtml(__('Edit')) ?></span>
        </a>
    </div>
    <div class="block-content">
        <div class="box-title">
            <span><?= $block->escapeHtml(__('My Password')) ?></span>
        </div>
       <div class="box-content">
            <p>•••••••••</p>
       </div>
    </div>
</div>
