<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>

<div class="new-checkout">
    <!--start order-summary-->
    <div class="wrap-order-summary">
        <h3><?= $block->escapeHtml(__('Order #1 (1 item)')) ?></h3>
        <div class="order-summary-info">
            <div class="order-summary-content">
                <div class="bx-address-info">
                    <h5><?= $block->escapeHtml(__('Delivery Address')) ?></h5>
                    <h4><?= $block->escapeHtml(__('Bangkit')) ?><span class="status status-blue"><?= $block->escapeHtml(__('Apartment')) ?></span></h4>
                    <p>Apartment Bassura City, Jl. Jendral Basuki<br/> Rachmat No.13 Kel. Cipinang Besar Selatan, Kec<br/> Jatinegara, Jakarta Timur 13410 <br/>+628176888763</p>
                </div>
                <div class="checkout-list-items">
                    <!------start item------>
                    <div class="item">
                        <div class="item-info">
                            <a href="#" title="thaole1233" class="product-item-photo">
                                <img src="https://apollo11-dev.ctdigital.id/media/catalog/product/cache/6410bdb417f1097c90b11783ebe3d82c/2/_/2_1_1.jpg" width="110" height="110" alt="thaole1233" />
                            </a>
                            <div class="product-item-details">
                                <a href="https://apollo11-dev.ctdigital.id/thaole1233.html" class="product-item-name">thaole1233</a>
                            </div>
                        </div>
                        <div class="subtotal">
                            <span class="price">Rp 1.490.000</span>
                        </div>
                    </div>
                    <!------End item------>
                </div>
            </div>
            <div class="order-sumary-footer">
                <div class="delivery-method">
                    <h5><?= $block->escapeHtml(__('Delivery Method')) ?></h5>
                    <span><?= $block->escapeHtml(__('Regular (2-7 Days)')) ?></span>
                </div>
                <div class="delivery-fee">
                    <h5><?= $block->escapeHtml(__('Delivery Fee')) ?></h5>
                    <span><?= $block->escapeHtml(__('Rp 30.000')) ?></span>
                </div>
            </div>
        </div>
    </div>
    <!--end order-summary-->

    <!--start order-summary-->
    <div class="wrap-order-summary">
        <h3><?= $block->escapeHtml(__('Order #2 (2 item)')) ?></h3>
        <div class="order-summary-info">
            <div class="order-summary-content">
                <div class="bx-address-info">
                    <h5><?= $block->escapeHtml(__('Delivery Address')) ?></h5>
                    <h4><?= $block->escapeHtml(__('Bangkit')) ?><span class="status status-blue"><?= $block->escapeHtml(__('Apartment')) ?></span></h4>
                    <p>Apartment Bassura City, Jl. Jendral Basuki<br/> Rachmat No.13 Kel. Cipinang Besar Selatan, Kec<br/> Jatinegara, Jakarta Timur 13410 <br/>+628176888763</p>
                </div>
                <div class="checkout-list-items">
                    <!------start item------>
                    <div class="item">
                        <div class="item-info">
                            <a href="#" title="thaole1233" class="product-item-photo">
                                <img src="https://apollo11-dev.ctdigital.id/media/catalog/product/cache/6410bdb417f1097c90b11783ebe3d82c/2/_/2_1_1.jpg" width="110" height="110" alt="thaole1233" />
                            </a>
                            <div class="product-item-details">
                                <a href="https://apollo11-dev.ctdigital.id/thaole1233.html" class="product-item-name">thaole1233</a>
                                <dl class="item-options">
                                    <dt>Ram</dt>
                                    <dd>
                                        1 x RAM 8GB <span class="price">$100.00</span> </dd>
                                    <dt>Monitor</dt>
                                    <dd>
                                        1 x Monitor 32 inch <span class="price">$200.00</span> </dd>
                                    <dt>CPU</dt>
                                    <dd>
                                        1 x CPU core i3 <span class="price">$300.00</span> </dd>
                                </dl>
                            </div>
                        </div>
                        <div class="subtotal">
                            <span class="price">Rp 1.490.000</span>
                        </div>
                    </div>
                    <!------End item------>
                </div>
            </div>
            <div class="order-sumary-footer">
                <div class="delivery-method">
                    <h5><?= $block->escapeHtml(__('Delivery Method')) ?></h5>
                    <span><?= $block->escapeHtml(__('Regular (2-7 Days)')) ?></span>
                </div>
                <div class="delivery-fee">
                    <h5><?= $block->escapeHtml(__('Delivery Fee')) ?></h5>
                    <span><?= $block->escapeHtml(__('Rp 30.000')) ?></span>
                </div>
            </div>
        </div>
    </div>
    <!--end order-summary-->
</div>
