<script type="text/javascript">
    require(['jquery', 'gtmCheckout', 'mage/url', 'domReady!'], function ($, gtmCheckout, urlBuilder) {
        $(window).load(function () {
            $('[data-gtm-event="remove-selected-items"]').on('click',function () {
                if (typeof dataLayerSourceObjects !== 'undefined') {
                    let productIds = [];
                    $('input.item-checked:checked').each(function () {
                        //Todo Remove Debug
                        console.log($(this).attr('data-gtm-product-id'));
                        console.log($(this).parents().eq(2).find('input[data-role="cart-item-qty"]').val());
                        let data = {
                            'productId' : $(this).attr('data-gtm-product-id'),
                            'productQty' : $(this).parents().eq(2).find('input[data-role="cart-item-qty"]').val(),
                            'delivery_option' : 'Not available'
                        };
                        productIds.push(data);
                    });
                    console.log(productIds);
                    let data = {
                        'productsInfo' : productIds
                    };
                    console.log(data);
                    $.ajax({
                        type: 'POST',
                        url: urlBuilder.build('sm_gtm/gtm/product'),
                        data: data,
                        dataType: "json",
                        async: true,
                        success: function (result) {
                            //Todo Remove Debug
                            console.log(typeof result);
                            console.log(result);
                            if (result) {
                                var dataProducts = [];
                                var quantity = 0;
                                var total = 0;
                                $.each(result, function(key, value){
                                    console.log(value);
                                    try {
                                        let product = JSON.parse(value);
                                        dataProducts.push(product);
                                        quantity += (product.quantity * 1);
                                        console.log(quantity);
                                        total += (product.quantity * product.price);
                                        console.log(total);
                                    } catch (e) {

                                    }
                                });
                                //Todo Remove Debug
                                console.log(dataProducts);
                                dataProducts['basket_value'] = total;
                                dataProducts['basket_quantity'] = quantity;
                                gtmCheckout.push('removeFromCart',dataProducts);
                            }
                        },
                        error: function () {

                        }
                    });
                }
            });
            $('[data-gtm-event="removeFromCart"]').on('click', function () {
                let productIds = [];
                let dataProduct = {
                    'productId' : $(this).attr('data-gtm-product-id'),
                    'productQty' : $(this).parents().eq(3).find('input[data-role="cart-item-qty"]').val(),
                    'delivery_option' : 'Not available'
                };
                productIds.push(dataProduct);
                let data = {
                    'productsInfo' : productIds
                };
                console.log(data);
                $.ajax({
                    type: 'POST',
                    url: urlBuilder.build('sm_gtm/gtm/product'),
                    data: data,
                    dataType: "json",
                    async: true,
                    success: function (result) {
                        //Todo Remove Debug
                        console.log(typeof result);
                        console.log(result);
                        if (result) {
                            var dataProducts = [];
                            var quantity = 0;
                            var total = 0;
                            $.each(result, function(key, value){
                                console.log(value);
                                try {
                                    let product = JSON.parse(value);
                                    dataProducts.push(product);
                                    quantity += (product.quantity * 1);
                                    console.log(quantity);
                                    total += (product.quantity * product.price);
                                    console.log(total);
                                } catch (e) {

                                }
                            });
                            //Todo Remove Debug
                            console.log(dataProducts);
                            dataProducts['basket_value'] = total;
                            dataProducts['basket_quantity'] = quantity;
                            gtmCheckout.push('removeFromCart',dataProducts);
                        }
                    },
                    error: function () {

                    }
                });
            });
        });
    });
</script>
