<script>
    require(['jquery', 'Magento_Ui/js/lib/view/utils/async', 'gtmCheckout', 'mage/url', 'jquery/jquery-storageapi', 'mage/translate', 'domReady!'],function ($, async, gtmCheckout, urlBuilder) {
        $(window).load(function () {
            if (typeof dataLayerSourceObjects !== 'undefined') {
                var getItems = function (){
                    if (window.checkoutConfig)
                        return window.checkoutConfig.quoteItemData;
                };
                var getDeliveryOption = function () {
                    return window.itemsCheckoutGTM
                };
                var productIds = [];
                async.async('[data-gtm-event="checkout-step-2"]',function () {
                    $('[data-gtm-event="checkout-step-2"]').on('click',function () {
                        if ($(this).text().includes($.mage.__('Go To Payment'))) {
                            let items = getItems();
                            let deliveryOption = getDeliveryOption();
                            console.log(items);
                            if (productIds.length === 0) {
                                $.each(items, function (key, value) {
                                    let delivery = "Not available";
                                    if (deliveryOption[key].shipping_method_selected !== 'store_pickup_store_pickup') {
                                        delivery = "Delivery";
                                    } else {
                                        delivery = $('h4[data-bind="html: currentStoreName"]').text();
                                    }
                                    let data = {
                                        'productId': value.product_id,
                                        'productQty': value.qty,
                                        'delivery_option': delivery
                                    };
                                    productIds.push(data);
                                });
                            }
                            console.log(productIds);
                            let data = {
                                'productsInfo': productIds
                            };
                            console.log(data);
                            $.ajax({
                                type: 'POST',
                                url: urlBuilder.build('sm_gtm/gtm/product'),
                                data: data,
                                dataType: "json",
                                async: true,
                                success: function (result) {
                                    //Todo Remove Debug
                                    console.log(typeof result);
                                    console.log(result);
                                    if (result) {
                                        var dataProducts = [];
                                        var quantity = 0;
                                        var total = 0;
                                        $.each(result, function (key, value) {
                                            console.log(value);
                                            try {
                                                let product = JSON.parse(value);
                                                dataProducts.push(product);
                                                quantity += (product.quantity * 1);
                                                console.log(quantity);
                                                total += (product.quantity * product.price);
                                                console.log(total);
                                            } catch (e) {

                                            }
                                        });
                                        //Todo Remove Debug
                                        console.log(dataProducts);
                                        let productForStep3 = {
                                            'step': 3,
                                            'option': 'Payment Method',
                                            'basket_value': total,
                                            'basket_quantity': quantity,
                                            'eventTimeout': 2000,
                                            'product': dataProducts
                                        }
                                        console.log(productForStep3);
                                        dataProducts['step'] = 2;
                                        dataProducts['option'] = 'Delivery Option';
                                        dataProducts['basket_value'] = total;
                                        dataProducts['basket_quantity'] = quantity;
                                        dataProducts['eventCallback'] = function () {
                                            //document.location = '<?//= $block->getUrl('transcheckout')?>//';
                                        };
                                        dataProducts['eventTimeout'] = 2000;
                                        gtmCheckout.push('checkout', dataProducts);
                                        console.log(productForStep3);
                                        $.localStorage.set('product-checkout-gtm', productForStep3);
                                    }
                                },
                                error: function () {
                                    //window.location.href='<?//= $block->getUrl('transcheckout')?>//';
                                }
                            });
                        }
                    });
                });
            }
        });
    });
</script>
