<?php
/**
 * @category Amasty
 * @package Amasty_Shopby
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author      Chinhvd <chinhvd@smartosc.com>
 * @copyright   Copyright (c) SmartOSC. All rights reserved.
 * @url http://www.smartosc.com/
 */
?>
<?php
/** @var \Amasty\Shopby\Block\Navigation\Widget\HideMoreOptions $block */
$dataAmJsAttribute = "data-am-js=%s";

if ($block->getIsState()) {
    $buttonSelector = sprintf($dataAmJsAttribute, 'show-more_button_state');
    $itemSelector = '[' . sprintf($dataAmJsAttribute, 'shopby-container') . ']';
    $numberUnfoldedOptions = $block->getUnfoldedOptions();
    $isModeDropdown = false;
} else {
    $filterSetting = $block->getFilterSetting();
    $isModeDropdown = $filterSetting->getDisplayMode()
        == \Amasty\Shopby\Model\Source\DisplayMode::MODE_DROPDOWN;
    $filterCode = $block->escapeHtml($filterSetting->getFilterCode());
    $buttonSelector = sprintf($dataAmJsAttribute, 'am-filter-items-'.  $filterCode. '-show-more');
    $itemSelector = '.am-filter-items-' . $filterCode;
    $numberUnfoldedOptions = $filterSetting->getNumberUnfoldedOptions();
}
?>

<?php if (!$isModeDropdown): ?>
    <a class="am-show-more"
       title="<?= $block->escapeHtml(__("Show more"))?>" <?= $block->escapeHtml($buttonSelector) ?>
       data-text-more="<?= $block->escapeHtml(__("View more"))?>"
       data-text-less="<?= $block->escapeHtml(__("Less"))?>"
       data-is-hide="false">
        <?= $block->escapeHtml(__("Less"))?>
    </a>

    <script type="text/x-magento-init">
        {
            "<?= /* @noEscape */ $itemSelector ?>": {
                "amShopbyFilterHideMoreOptions": {
                    "numberUnfoldedOptions": <?= $block->escapeHtml($numberUnfoldedOptions) ?>,
                    "selectors": {
                        "button": "[<?= /* @noEscape */ $buttonSelector ?>]"
                    },
                    "isState": "<?= /* @noEscape */ $block->getIsState() ?>"
                }
            }
        }
    </script>
<?php endif; ?>
