<?php
/**
 * SMCommerce
 *
 * Date: May, 22 2020
 * Time: 10:45 AM
 * User: VooThanh DEV
 *
 * @author    SMCommerce Core Team <connect@smartosc.com>
 * @copyright Copyright SMCommerce (http://smartosc.com/)
 */ ?>
<?php /** @var $block \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox */ ?>
<?php /** @var $priceModel \Magento\Framework\Pricing\Price\PriceInterface */ ?>
<?php /** @var $finalPriceModel \Magento\Framework\Pricing\Price\PriceInterface */ ?>
<?php /** @var $helper \SM\Catalog\Helper\Data */ ?>
<?php $helper = $this->helper(\SM\Catalog\Helper\Data::class); ?>
<?php if ($helper && $minProduct = $helper->getMinConfigurable($block->getSaleableItem())) : ?>
    <?php $priceModel = $minProduct->getPriceInfo()->getPrice('regular_price') ?>
    <?php $finalPriceModel = $minProduct->getPriceInfo()->getPrice('final_price') ?>
    <?php $idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : ''; ?>
    <?php $schema = $block->getZone() === 'item_view' ?>
    <?php if ($block->hasSpecialPrice()) : ?>
        <?php if (!$schema) : ?>
            <?php if ($finalPriceModel->getAmount() < $priceModel->getAmount()) : ?>
                <span class="special-price">
                <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
                    'display_label' => __('As low as'),
                    'price_id' => $block->getPriceId('product-price-' . $idSuffix),
                    'price_type' => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema,
                ]);
                ?>
            </span>
                <span class="old-price sly-old-price">
                <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
                    'display_label'     => __('Regular Price'),
                    'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                    'price_type'        => 'oldPrice',
                    'include_container' => true,
                    'skip_adjustments'  => true
                ]); ?>
            </span>
            <?php else: ?>
                <span class="normal-price">
                <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
                    'display_label' => __('As low as'),
                    'price_id' => $block->getPriceId('product-price-' . $idSuffix),
                    'price_type' => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema,
                ]);
                ?>
            </span>
            <?php endif ?>
        <?php else: ?>
            <span class="normal-price">
            <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
                'display_label' => __('As low as'),
                'price_id' => $block->getPriceId('product-price-' . $idSuffix),
                'price_type' => 'finalPrice',
                'include_container' => true,
                'schema' => $schema,
            ]);
            ?>
        </span>
        <?php endif ?>
    <?php else: ?>
        <span class="normal-price">
        <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label' => __('As low as'),
            'price_id' => $block->getPriceId('product-price-' . $idSuffix),
            'price_type' => 'finalPrice',
            'include_container' => true,
            'schema' => $schema,
        ]);
        ?>
    </span>
    <?php endif; ?>

    <?php if ($block->showMinimalPrice()) : ?>
        <?php if ($block->getUseLinkForAsLowAs()) :?>
            <a href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="minimal-price-link">
                <?= /* @noEscape */ $block->renderAmountMinimal() ?>
            </a>
        <?php else :?>
            <span class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </span>
        <?php endif?>
    <?php endif; ?>
<?php endif; ?>
