<?php
/**
 * SMCommerce
 *
 * @category  SM
 * @package   SM_Theme
 *
 * Date: April, 08 2020
 * Time: 4:29 PM
 * User: VooThanh DEV
 *
 * @author    SMCommerce Core Team <connect@smartosc.com>
 * @copyright Copyright SMCommerce (http://smartosc.com/)
 */
?>
<?php /** @var \Magento\LayeredNavigation\Block\Navigation $block */ ?>
<?php $category = $block->getLayer()->getCurrentCategory(); ?>
<?php if ($block->canShowBlock()) : ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='
    {
        "collapsible":
        {
            "openedState": "active",
            "collapsible": true,
            "active": false,
            "collateral":
            {
                "openedState": "filter-active",
                "element": "body"
            }
        }
    }'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?= /* @noEscape */ $filtered ?>">
            <strong data-role="title"><?= $block->escapeHtml(__('Shop By')); ?></strong>
        </div>
        <div class="block-content filter-content">
            <?= $block->getChildHtml('state') ?>


            <?php $wrapOptions = false; ?>
            <?php /** @var \Magento\Catalog\Model\Layer\Filter\FilterInterface $filter */ ?>
            <?php foreach (array_values($block->getFilters()) as $key => $filter) : ?>
                <?php if (!$wrapOptions) : ?>
                    <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= $block->escapeHtml(__('Shopping Options')) ?></strong>
                    <div class="filter-options" id="narrow-by-list" data-role="content"
                         data-mage-init='{
                                       "SM_Theme/js/accordion":{
                                            "openedState": "active",
                                            "collapsible": true,
                                            "active": false,
                                            "multipleCollapsible": false
                                       }
                                    }'
                    >
                    <?php $wrapOptions = true; ?>
                <?php endif; ?>
                <div data-role="collapsible" class="filter-options-item">
                    <div data-role="title" class="filter-options-title">
                        <?= $block->escapeHtml(__($filter->getName())) ?>
                    </div>
                    <div data-role="content" class="filter-options-content ">
                        <?php if ($filter->getRequestVar() == 'cat'): ?>
                        <div class="am-ranges filter-options-category">
                         <?php endif; ?>

                            <?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?>
                         <?php if ($filter->getRequestVar() == 'cat'): ?>
                        </div>
                        <?php endif; ?>

                        <?php if ($filter->getRequestVar() == 'cat'): ?>
                            <div class="navList-seeall">
                                <a href="<?= $block->escapeHtml($category->getUrl()) ?>"
                                   title="<?= $block->escapeHtmlAttr($category->getName())?>"
                                >
                                    <?= __('See All ') . $block->escapeHtml($category->getName()) ?>
                                </a>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php if ($wrapOptions) : ?>
                        </div>
        <?php else : ?>
            <script>
                require([
                    'jquery'
                ], function ($) {
                    $('#layered-filter-block').addClass('filter-no-options');
                });
            </script>
        <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
