<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
    $_product = $block->getProduct();
?>
<?php if ($_product->isSaleable() && $block->hasOptions()): ?>
<div id="bundleSummary"
     class="block-bundle-summary"
     data-mage-init='{"sticky":{"container": ".product-add-form"}}'>
    <div class="content">
        <div class="bundle-info">
            <?php echo $block->getImage($_product, 'bundled_product_customization_page')->toHtml(); ?>
            <div class="product-details">
                <strong class="product name"><?php echo $block->escapeHtml($_product->getName()) ?></strong>
                <?php if ($_product->getIsSalable()): ?>
                    <p class="available stock" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
                        <span><?php /* @escapeNotVerified */ echo __('In stock') ?> 1</span>
                    </p>
                <?php else: ?>
                    <p class="unavailable stock" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
                        <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
                    </p>
                <?php endif; ?>
                <?php echo $block->getChildHtml('', true);?>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".product-add-form": {
            "slide": {
                "slideSpeed": 1500,
                "slideSelector": "#bundle-slide",
                "slideBackSelector": ".action.customization.back",
                "bundleProductSelector": "#bundleProduct",
                "bundleOptionsContainer": ".product-add-form"
                <?php if ($block->isStartCustomization()): ?>
                ,"autostart": true
                <?php endif;?>
            }
        }
    }
</script>

<script type="text/x-magento-init">
    {
        ".product-add-form": {
            "Wizkunde_ConfigurableBundle/js/bundle-conditions": {
                "cascade": <?= /* @escapeNotVerified */ $_product->getBundleCascadeQty() ?>
            }
        }
    }
</script>
<?php endif; ?>
