<?php
/** @var \Magento\MultipleWishlist\Block\Customer\Wishlist\Management $block */

/** @var \Magento\Wishlist\Model\Wishlist $wishlist */
$wishlist = $block->getCurrentWishlist();
$defaultWishlistId = $block->getDefaultWishlist()->getId();
$isDefault = $wishlist->getId() == $defaultWishlistId;
?>
<div class="headtab-toolbar">
    <h4 class="title-tab"><?= $block->escapeHtml($wishlist->getName()) ?></h4>
    <a href="#" class="setting" id="button-open-settings-modal">
        <?= $block->escapeHtml(__('Settings')) ?>
    </a>
    <div id="shopping-list-setting-modal" class="content" style="display: none">
        <label class="label" for="input-wishlist-name">
            <span><?= $block->escapeHtml(__("List Name"))?></span>
        </label>
        <form id="form-update-list" action="<?= $block->getUrl("wishlist/action/updatelist")?>" method="post">
            <input type="text" class="wishlist-name" id="input-wishlist-name" name="shoppinglist_name" value="<?= $wishlist->getName()?>" placeholder="<?= $block->escapeHtml(__('Type the list name here'))?>" <?= ($isDefault ? "readonly" : "") ?>/>
            <input type="hidden" name="shoppinglist_id" value="<?= $wishlist->getId()?>"/>
        </form>
        <a href="#" class="action remove-list"
           data-remove-url="<?= $block->escapeHtml($block->getUrl("wishlist/action/removelist", ["wishlist_id" => $wishlist->getId()]))?>"
           id="button-confirm-delete-list-modal">
            <?= $block->escapeHtml(__('Delete List'))?>
        </a>
    </div>

    <div id="confirm-delete-list-modal" class="content" style="display:none;">
        <span class="remove-wishlist-verify">
            <span><?= $block->escapeHtml(__('Are you sure you want to delete'))?></span>
            <b><?= $block->escapeHtml($wishlist->getName()) ?></b>
            <span><?=$block->escapeHtml(__('from shopping list?'))?></span>
        </span>
        <input type="hidden" id="list-id-delete-modal">
    </div>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "ShoppingListSettings":{
                "update_url":"<?= $block->escapeUrl($block->getUrl("wishlist/ajax/updatelist"))?>",
                "wishlist_id":"<?= $block->escapeHtml($wishlist->getId())?>",
                "shoppinglist_name":"<?= $wishlist->getName() ?>",
                "is_default":"<?= $block->escapeHtml($isDefault)?>"
        }
    }
}
</script>
