<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
/** @var \SM\ShoppingList\ViewModel\ItemViewModel $viewModel */
$product = $block->getProduct();
$viewModel = $block->getData('viewModel');
$productImage = $viewModel->getProductImage($product);
$productId = $product->getId();
/** @var \SM\ShoppingList\Helper\Data $shoppingListHelper */
$shoppingListHelper = $this->helper(\SM\ShoppingList\Helper\Data::class);
?>
<?php if ($shoppingListHelper->isActiveShoppingList()):?>
<a class="action towishlist"
   id="btn-open-add-item"
   data-product-id="<?= $block->escapeHtml($productId)?>"
   style="cursor: pointer;">
    <span id="additem-title"><?= $block->escapeHtml(__('Add to Shopping List')) ?></span>
</a>
<div id = "add-item-modal" class="content" style="display: none">
    <div class="product-info">
        <img src="<?= $block->escapeUrl($productImage) ?>" width="124px" alt="<?= $block->escapeHtml($product->getName()) ?>"/>
        <span class="product-name"><?= $block->escapeHtml($product->getName()) ?></span>
    </div>
    <form id="form-add-item">
        <ul class="list-choice" id="list-choice-pdp">
            <?php
            /** @var \Magento\Wishlist\Model\Wishlist $wishlist */
            foreach ($viewModel->getShoppingLists() as $wishlist) :?>
                <li class="checkbox-custom">
                    <input type="checkbox" name="selected[]" value="<?= $block->escapeHtml($wishlist->getId()) ?>">
                    <label><?= $block->escapeHtml($wishlist->getName()) ?></label>
                </li>
            <?php endforeach;?>
        </ul>

        <div class="add-new-wishlist">
            <a id="open-create-to-add" class="remove-list" style="cursor: pointer">
                <span><?= $block->escapeHtml(__('Create a List')) ?></span>
            </a>

            <div id="create-to-add" class="bx-addition-wishlist-name" style="display: none">
                <label class="label" for="shoppinglist-name-pdp"><?= $block->escapeHtml(__('List Name')) ?></label>
                <div class="wrap">
                <input type="text" class="addition-wishlist-name" id="shoppinglist-name-pdp" name="addition_wishlist_name"
                       placeholder="<?= $block->escapeHtml(__('Type the list name here')) ?>"/>
                <button type="button" class="add-wishlist-name" id="submit-create-pdp"><span class="apl-ic_plus"><?= $block->escapeHtml(__('Plus')) ?></span></button>
                </div>
            </div>
        </div>

    </form>
</div>
<div id="success-alert-modal" class="content add-success-modal" style="display:none;">
    <div class="product-info">
        <img src="<?= $block->escapeUrl($productImage) ?>" width="124px"  alt="<?= $block->escapeHtml($product->getName()) ?>"/>
        <div class="success-content">
            <span class="product-name"><?= $block->escapeHtml($product->getName()) ?></span>
            <h3><?= $block->escapeHtml(__("This item has been added to"))?></h3>
            <ul id="destination-list" style="list-style-type: none;">
            </ul>
        </div>
    </div>
    <input type="hidden" data-gtm-pdp="add-to-wishlist">
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "ItemAdd": {}
        }
    }
</script>
<?php endif;?>
