<?php
/** @var \SM\Customer\Block\Form\Register $block */
if (!$block->isLoggedIn()) :
?>
<?php
    $helper = $this->helper(SM\AndromedaSms\Helper\Config::class);
    $countdownTime = $helper->getVerificationCodeExpiredIn();
?>
    <div class="block-container-otp block-container-signin" id="tab-verification" style="display: none">
        <div class="row no-gutters">
            <div class="container-signin--left col-xs-12 col-xl-6">
                <img src='<?= $block->escapeUrl($block->getViewFileUrl('images/reliable.jpg')); ?>' alt="Welcome" loading="lazy" width="585" height="859">
            </div>
            <div class="container-signin--right col-xs-12 col-xl-6">
                <div class="container-signin--content">
                    <div class="block-title block-title-otp" id="block-customer-login-heading" role="heading" aria-level="2">
                        <?= $block->escapeHtml(__('Verification')) ?>
                    </div>
                    <form class="form-verification form-customer-login" action="" method="post" >
                        <div class="message-verify">
                            <div class="block-subtitle-verify" id="phone-number"><?= $block->escapeHtml(__('We have sent a verification code to ')) ?> </div>
                            <div class="phone-otp" id="phone-otp"></div>
                        </div>
                        <div class="block-subtitle"><?= $block->escapeHtml(__('Enter your code here')) ?></div>
                        <div class="digit-group" data-group-name="digits" data-autosubmit="false">
                            <input class="combine otp-input" type="number" id="digit-1"
                                   name="digit-1" data-next="digit-2" maxlength="1" />
                            <input class="combine otp-input" type="number" id="digit-2" name="digit-2"
                                   data-next="digit-3" data-previous="digit-1" maxlength="1" />
                            <input class="combine otp-input" type="number" id="digit-3" name="digit-3"
                                   data-next="digit-4" data-previous="digit-2" maxlength="1" />
                            <input class="combine otp-input" type="number" id="digit-4" name="digit-4"
                                   data-next="digit-5" data-previous="digit-3" maxlength="1" />
                            <input class="combine otp-input" type="number" id="digit-5" name="digit-5"
                                   data-next="digit-6" data-previous="digit-4" maxlength="1" />
                            <input class="combine otp-input" type="number" id="digit-6" name="digit-6"
                                   data-previous="digit-5" maxlength="1" />
                        </div>
                        <div class="message-otp-error field-error" id="message-otp-error"></div>
                        <input id="combine" type="hidden" />
                        <div class="actions-toolbar">
                            <button type="submit" id="otp-validate" form="form-create" class="disabled action verification primary" title="<?= $block->escapeHtmlAttr(__('Verification')) ?>"><span><?= $block->escapeHtml(__('Next')) ?></span></button>
                        </div>
                    </form>
                    <div class="txt-bottom-verify clearfix">
                <span class="txt-count">
                    <?= $block->escapeHtml(__('You can try resending the code')) ?>
                    <span class="txt-second" count="<?= $countdownTime; ?>"><?= sprintf(__('in <span>%s</span> second(s).'), $countdownTime) ?></span>
                </span>
                        <a class="txt-resend" href="#" id="resend-otp"><?= $block->escapeHtml(__('Resend code')) ?></a>
                        <div class="message-otp-notice" id="message-otp-notice"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        require(
            [
                'OtpVerification',
                'domReady!'
            ],
            function (OtpVerification) {
                OtpVerification.init();
            },
        );
    </script>
<?php endif; ?>
