<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="block block-notification-setting">
    <div class="block-content block-notification-settings-content">
        <div class="block-item container-two-col">
            <div class="block-item-title">
                <div class="title">
                    <p>Transmart Update</p>
                </div>
                <div class="title">
                    <p>Email</p>
                </div>
            </div>
            <div class="block-item-content">
               <div class="item">
                   <div class="content">
                       <p>Promos & Events</p>
                   </div>
                   <div class="content">
                       <div class="checkbox-custom">
                           <input type="checkbox" name="checkbox" value="1">
                           <label></label>
                       </div>
                   </div>
               </div>
                <div class="item">
                    <div class="content">
                        <p>Information</p>
                    </div>
                    <div class="content">
                        <div class="checkbox-custom">
                            <input type="checkbox" name="checkbox" value="1">
                            <label></label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="block-item container-three-col">
            <div class="block-item-title">
                <div class="title col-1">
                    <p>My orders</p>
                </div>
                <div class="title col-2">
                    <p>Email</p>
                </div>
                <div class="title col-3">
                    <p>SMS</p>
                </div>
            </div>
            <div class="block-item-content">
                <div class="item">
                    <div class="content col-1">
                        <p>Order Status</p>
                    </div>
                    <div class="content col-2">
                        <div class="checkbox-custom">
                            <input type="checkbox" name="checkbox" value="1">
                            <label></label>
                        </div>
                    </div>
                    <div class="content col-3">
                        <div class="checkbox-custom">
                            <input type="checkbox" name="checkbox" value="1">
                            <label></label>
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="content col-1">
                        <p>Order Status When Signed Out</p>
                    </div>
                    <div class="content col-2">
                        <div class="checkbox-custom">
                            <input type="checkbox" name="checkbox" value="1">
                            <label></label>
                        </div>
                    </div>
                    <div class="content col-3">
                        <div class="checkbox-custom">
                            <input type="checkbox" name="checkbox" value="1">
                            <label></label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="block-item container-two-col">
            <div class="block-item-title">
                <div class="title">
                    <p>Transmart Update</p>
                </div>
                <div class="title">
                    <p>Email</p>
                </div>
            </div>
            <div class="block-item-content">
                <div class="item">
                    <div class="content">
                        <p>My Appointments</p>
                    </div>
                    <div class="content">
                        <div class="checkbox-custom">
                            <input type="checkbox" name="checkbox" value="1">
                            <label></label>
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="content">
                        <p>Subscriptions</p>
                    </div>
                    <div class="content">
                        <div class="checkbox-custom">
                            <input type="checkbox" name="checkbox" value="1">
                            <label></label>
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="content">
                        <p>Reorder Quickly</p>
                    </div>
                    <div class="content">
                        <div class="checkbox-custom">
                            <input type="checkbox" name="checkbox" value="1">
                            <label></label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="block-item container-two-col">
            <div class="block-item-title">
                <div class="title">
                    <p>Digital Care Chat</p>
                </div>
                <div class="title">
                    <p>Email</p>
                </div>
            </div>
            <div class="block-item-content">
                <div class="item">
                    <div class="content">
                        <p>Chat Recap</p>
                    </div>
                    <div class="content">
                        <div class="checkbox-custom">
                            <input type="checkbox" name="checkbox" value="1">
                            <label></label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="block-item container-two-col-special">
            <div class="block-item-title">
                <div class="title col-1">
                    <p>Notify me</p>
                </div>
                <div class="title col-2">
                    <p>SMS</p>
                </div>
            </div>
            <div class="block-item-content">
                <div class="item">
                    <div class="content col-1">
                        <p>Unknown Device Sign In</p>
                    </div>
                    <div class="content col-2">
                        <div class="checkbox-custom">
                            <input type="checkbox" name="checkbox" value="1">
                            <label></label>
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="content col-1">
                        <p>My Appointments</p>
                    </div>
                    <div class="content col-2">
                        <div class="checkbox-custom">
                            <input type="checkbox" name="checkbox" value="1">
                            <label></label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

