<?php
/**
 * @project    ct-corp-transmart
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author     Duc Nguyen Hoang <ducnh2@smartosc.com>
 * @copyright  Copyright © 2020 SmartOSC. All rights reserved.
 * @url        http://www.smartosc.com
 */
/** @var \SM\InspireMe\Block\Post\PostList $block */

?>
<h3 class="results-tag-count">
    <?= $block->escapeHtml(__('%1 Results Tagged in', $block->getPostCollection()->getSize())) ?>
    <strong><?= $block->escapeHtml($block->getTag()->getName()) ?></strong>
</h3>
