<?php
/**
 * @category    SM
 * @package     SM_Coachmarks
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 * @author      Logan Ta <phuongtt2@smartosc.com>
 *
 * @copyright   Copyright (c) SmartOSC. All rights reserved.
 * @url http://www.smartosc.com/
 */

/** @var $block \SM\Coachmarks\Block\Adminhtml\Tooltip\Edit\Form */
?>
<div class="entry-edit form-inline" id="sm-coachmarks">
    <?= $block->getFormHtml(); ?>
</div>
<?= $block->getChildHtml('form_after'); ?>

<script type="text/x-magento-init">
    {
        "#sm-coachmarks": {
            "SM_Coachmarks/js/view/coachmarks":{
                "templateHtml": "<?= $block->escapeJs(''); ?>",
                "imgUrls": "<?= $block->escapeJs(''); ?>"
            }
        }
    }

</script>
