<?php

/**
 * @category  SM
 * @package   SM_Catalog
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 * @author    Logan Ta <phuongtt2@smartosc.com>
 *
 * @copyright 2020 Copyright (c) SmartOSC. All rights reserved.
 * @url http://www.smartosc.com/
 */
/** @var $block \Magento\Checkout\Block\Cart\Additional\Info */
$label = $block->getLabel();
?>
<div class="product-label-item-cart">
    <p class="label-item"><strong><?= __($label)?></strong></p>
</div>
