<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

if (!$block->isLoggedIn()): ?>
    <li class="sign-link" data-label="<?= $block->escapeHtmlAttr(__('or')) ?>">
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?>>
            <?= __('Sign In') ?>
        </a>
    </li>
<?php endif ?>
