<?php
/** @var \SM\Sales\Block\Order\Digital\Part\Content $block */

/** @var \SM\Sales\Api\Data\DigitalOrderDataInterface $digitalOrder */
$digitalOrder = $block->getParentOrder();
$ext = $digitalOrder->getProductOption()->getExtensionAttributes();
?>

<div class="bx-order-status bx-order-status-digital">
    <div class="od-delivery-address">
        <div class="tracking-order-service">
            <span class="service-type"><?= $block->escapeHtml(__('Service Type')) ?></span>
            <h4><?= $ext->getDigitalData()->getDigital()->getServiceType() ?></h4>
        </div>
        <div class="product-name">
            <span class="delivery-address"><?= $block->escapeHtml(__('Power')) ?></span>
            <h4><?= $ext->getDigitalData()->getDigital()->getPower() ?></h4>
        </div>
    </div>
    <div class="tracking-order">
        <div class="mobile-number">
            <span class="delivery-address"><?= $block->escapeHtml(__('Customer ID')) ?></span>
            <h4><?= $ext->getDigitalData()->getDigital()->getCustomerId() ?></h4>
        </div>
        <div class="serial-number">
            <span class="delivery-address"><?= $block->escapeHtml(__('Period')) ?></span>
            <h4><?= $ext->getDigitalData()->getDigital()->getPeriod() ?></h4>
        </div>
    </div>
    <div class="od-delivery-address-last">
        <div class="operator">
            <span class="delivery-address"><?= $block->escapeHtml(__('Name')) ?></span>
            <h4><?= $ext->getDigitalData()->getDigital()->getCustomerName() ?></h4>
        </div>
    </div>
</div>
