<?php
/**
 * SMCommerce
 *
 * @category  Magento
 * @package   Magento_GroupedProduct
 *
 * Date: May, 13 2020
 * Time: 3:10 PM
 * User: VooThanh DEV
 *
 * @author    SMCommerce Core Team <connect@smartosc.com>
 * @copyright Copyright SMCommerce (http://smartosc.com/)
 */ ?>
<?php /** @var $block \Magento\Catalog\Pricing\Render\FinalPriceBox */ ?>
<?php /** @var $helper \SM\Catalog\Helper\Data */ ?>
<?php $helper = $this->helper(\SM\Catalog\Helper\Data::class) ?>
<?php if ($helper && $minProduct = $helper->getMinGrouped($block->getSaleableItem())) : ?>
    <?php $priceModel = $minProduct->getPriceInfo()->getPrice('regular_price') ?>
    <?php $finalPriceModel = $minProduct->getPriceInfo()->getPrice('final_price') ?>
    <?php $idSuffix = $block->getIdSuffix() ?? '' ?>
    <?php $schema = ($block->getZone() === 'item_view') ?>
    <!--if has special price or not and in product detail page-->
    <?php if ($schema) : ?>
        <?php
        if ($minProduct) {
            $amountRender = $block->getRendererPool()
                ->createAmountRender(
                    $minProduct->getPriceInfo()->getPrice('final_price')->getAmount(),
                    $minProduct,
                    $minProduct->getPriceInfo()->getPrice('final_price'),
                    ['include_container' => true]
                );
        }
        ?>
        <div class="price-box">
            <?php if ($minProduct) : ?>
                <p class="minimal-price">
                    <span class="price-label"><?= $block->escapeHtml(__('From')) ?></span><?= $amountRender->toHtml() ?>
                </p>
            <?php endif ?>
        </div>
    <?php else : ?>
        <div class="label"><?= $block->escapeHtml(__('From')) ?></div>
        <?php if ($finalPriceModel->getAmount() < $priceModel->getAmount()) : ?>
            <span class="special-price">
                <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
                    'display_label'     => __('Special Price'),
                    'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema'            => $schema
                ]); ?>
            </span>
            <span class="old-price">
                <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
                    'display_label'     => __('Regular Price'),
                    'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                    'price_type'        => 'oldPrice',
                    'include_container' => true,
                    'skip_adjustments'  => true
                ]); ?>
            </span>
        <?php else : ?>
            <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema'            => $schema
            ]); ?>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>

