<?php
/**
 * @category    SM
 * @package     SM_Coachmarks
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 * @author      Logan Ta <phuongtt2@smartosc.com>
 *
 * @copyright   Copyright (c) SmartOSC. All rights reserved.
 * @url http://www.smartosc.com/
 */
/** @var \SM\Coachmarks\Block\Topic $block */
if ($block->isEnabled() && $block->getCustomerLoggedIn()):
$getTopicCollect = $block->getObjectTopicCollect();
$getTooltipCollect = $block->getObjectTooltipCollect();
    if ($getTopicCollect):
?>
<div class="wrapper-topic-tooltip">
    <div class="topic-tooltip-action" data-bind="scope: 'topicTooltip'">
        <script type="text/x-magento-init">
            {
                "*": {
                    "Magento_Ui/js/core/app": {
                        "components": {
                            "topicTooltip": {
                                "component": "SM_Coachmarks/js/view/maincoachmarks",
                                    "config": {
                                        "topic": <?php echo $getTopicCollect; ?>,
                                        "tooltip": <?php echo $getTooltipCollect; ?>
                                             }
                                        }
                                    }
                                }
                }
            }
        </script>
    </div>
</div>
    <?php else: ?>
        <script type="text/x-magento-init">
            {
                "*": {
                    "SM_Coachmarks/js/view/maincoachmarks-none": {
                    }
                }
            }
        </script>
    <?php endif; ?>
<?php elseif($block->getCustomerLoggedIn()): ?>
    <script type="text/x-magento-init">
            {
                "*": {
                    "SM_Coachmarks/js/view/maincoachmarks-none": {
                    }
                }
            }
        </script>
<?php endif; ?>

