<?php
/** @var \Magento\Review\Block\Form $block */

/** @var \Magento\Review\Model\Rating $rating */
$rating = $block->getQualityRating();
/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getProductInfo();

?>
<div class="review-product">
    <a href="<?= $block->getUrl('review/customer/index') ?>" class="back-myreview"><?= $block->escapeHtml(__('Back to My Reviews')) ?></a>
    <div class="form-review">
        <?php
        /** @var \SM\Review\Block\Customer\Form\Detail $formBlock */
        $formBlock = $block->getChildBlock("product.review.form.detail");
        $formBlock->setProduct($product); ?>
        <?= $block->getChildHtml("product.review.form.detail");?>
    </div>
</div>
