<?php
/**
 * @project    ct-corp-transmart
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author     Duc Nguyen Hoang <ducnh2@smartosc.com>
 * @copyright  Copyright © 2020 SmartOSC. All rights reserved.
 * @url        http://www.smartosc.com
 */

/** @var \SM\Customer\Block\Form\CheckLogin $block */
?>
<?php if (!$block->isLoggedIn()): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "SM_Customer/js/popup": {}
            }
        }
    </script>
<?php else: ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "SM_Customer/js/popup-recovery": {}
            }
        }
    </script>
<?php endif; ?>
