<?php
/**
 * @project    ct-corp-transmart
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author     Duc Nguyen Hoang <ducnh2@smartosc.com>
 * @copyright  Copyright © 2020 SmartOSC. All rights reserved.
 * @url        http://www.smartosc.com
 */

/** @var \SM\Customer\Block\Form\Register $block */
?>
<div class="block-container-signin block-container--privacy" id="privacy-popup" style="display: none">
    <div class="row no-gutters">
        <div class="container-signin--left col-xs-12 col-xl-6">
            <img src='<?= $block->escapeUrl($block->getViewFileUrl('images/reliable.jpg')); ?>' alt="Welcome" loading="lazy" width="585" height="859">
        </div>
        <div class="container-signin--right col-xs-12 col-xl-6">
            <div class="container-signin--content">
                <div class="block-title block-title-privacy">
                    <button type="button" class="action-back" selector="action-back">
                        <i class="icon ic-black"></i>
                    </button>
                    <strong id="block-customer-privacy-heading" role="heading" aria-level="2">
                        <?= $block->escapeHtml(__('PRIVACY POLICY')) ?>
                    </strong>
                </div>
                <div class="block-content">
                    <?= /* @noEscape */ $block->getPrivacyPolicyContent() ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ], function ($, modal) {
            let registerPrivacy = $('#register-privacy-policy'),
                privacyPopup = $('#privacy-popup'),
                options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: false,
                    clickableOverlay: false,
                    modalClass: 'terms-privacy',
                    title: '',
                    buttons: []
                };

            modal(options, privacyPopup);
            registerPrivacy.on('click', function () {
                $('#register').modal('closeModal');
                privacyPopup.modal('openModal').show();
            });

            privacyPopup.find('[selector=action-back]').click(function () {
                privacyPopup.modal('closeModal');
                $('#register').modal('openModal').show();
            });
        }
    )
</script>
