<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
$selected = "Default";
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Sort by')) ?></label>
    <form class="sortby-dropdown shoplist-sortby">
        <span class="action toggle" data-toggle="dropdown">
            <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
                <?php if ($block->isOrderCurrent($_key)) :?>
                    <?php $selected = $_order; ?>
                <?php endif; ?>
            <?php endforeach; ?>
            <span><?= $block->escapeHtml(__($selected)) ?></span>
        </span>
        <ul id="sorter" data-role="sorter" class="dropdown">
            <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
                <li class="radio-custom" data-sort="<?= $block->escapeHtmlAttr($_key) ?> "
                    <?php if ($block->isOrderCurrent($_key)) :?>
                        selected="selected"
                    <?php endif; ?>
                >


                    <input type="radio"  name="sorter"
                           value="<?= $block->escapeHtmlAttr($_key) ?>"
                        <?= ($block->isOrderCurrent($_key) ? 'checked' : '') ?>
                    />
                    <label ><?= $block->escapeHtml(__($_order)) ?></label>
                </li>
            <?php endforeach; ?>
        </ul>
        <?php if ($block->getCurrentDirection() == 'desc') :?>
            <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
               href="#"
               class="action sorter-action sort-desc"
               data-role="direction-switcher"
               data-value="asc">
                <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
            </a>
        <?php else :?>
            <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>"
               href="#"
               class="action sorter-action sort-asc"
               data-role="direction-switcher"
               data-value="desc">
                <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
            </a>
        <?php endif; ?>
    </form>
</div>
