<?php
/** @var \SM\ShoppingList\Block\Toolbar $block */

/** @var \Magento\Wishlist\Model\Wishlist $wishlist */
$wishlist = $block->getShoppingList();
?>

<button id="open-delete-modal-<?= $block->escapeHtml($wishlist->getId())?>" type="submit" class="mylists-action remove"><span class="apl-Remove"></span></button>
<div id="confirm-delete-list-modal-<?= $block->escapeHtml($wishlist->getId())?>" class="content" style="display:none;">
    <span class="remove-wishlist-verify">
        <span><?= $block->escapeHtml(__('Are you sure you want to delete'))?></span>
        <b><?= $block->escapeHtml($wishlist->getName())?></b>
        <span><?= $block->escapeHtml(__(' from your shopping list?'))?></span>
    </span>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "ListSettings":{
            "remove_list_url":"<?= $block->getUrl('wishlist/action/removelist', ['wishlist_id' => $wishlist->getId()]) ?>",
            "list_id":"<?= $wishlist->getId() ?>"
        }
    }
}
</script>
