<?php
/**
 * SMCommerce
 *
 * @category  Amasty
 * @package   Amasty_Shopby
 *
 * Date: April, 09 2020
 * Time: 4:29 PM
 * User: VooThanh DEV
 *
 * @author    SMCommerce Core Team <connect@smartosc.com>
 * @copyright Copyright SMCommerce (http://smartosc.com/)
 */
?>
<?php
/** @var \Amasty\ShopbyBase\Model\FilterSetting $filterSetting */
/** @var \Amasty\Shopby\Block\Navigation\FilterRenderer $block */

$filterUniqId = $block->escapeId(uniqid());
$filterCode = $block->escapeHtml($filterSetting->getFilterCode());
?>

<?php if ($filterSetting->isShowSearchBox(count($filterItems))): ?>
    <?= /* @noEscape */ $block->getSearchForm(); ?>
<?php endif; ?>
<?php if ($filterSetting->getAddFromToWidget() && isset($fromToConfig) && is_array($fromToConfig)): ?>
    <?= /* @noEscape */ $block->getFromToWidget('default') ?>
<?php endif;?>
<form class="am-ranges"
      data-am-js="ranges"
      data-amshopby-filter="<?= $block->escapeHtml($filterCode);?>"
      data-amshopby-filter-request-var="<?= $block->escapeHtml($block->getFilter()->getRequestVar()); ?>"
      autocomplete="off">
    <ol class="items am-filter-items-<?= /* @noEscape */ $filterCode;?>"
        <?php if ($filterSetting->getEnableOverflowScroll() > 0): ?>
            style="max-height:<?= $block->escapeHtml($filterSetting->getEnableOverflowScroll()) ?>px;"
        <?php endif; ?>>
        <?php /** @var \Amasty\Shopby\Model\Layer\Filter\Item $filterItem */?>
        <?php foreach ($filterItems as $filterItem): ?>
            <?php $optionLabel = $filterItem->getOptionLabel(); ?>
            <?php $inputType = !$filterSetting->isMultiselect() || in_array($filterCode, ['rating', 'stock']) ? 'radio' : 'checkbox'?>
            <?php $displayLabel = trim(preg_replace('/\s+/', ' ', $block->stripTags($optionLabel))) . ($filterCode == 'rating' ? __(' star(s)') : '');?>
        <li class="item" data-label="<?= /* @noEscape */ $displayLabel ?>">
            <?php if ($filterItem->getCount() >= 0): ?>
                <?php $style = 'display: none;'; ?>
                <input name="amshopby[<?= /* @noEscape */ $block->getFilter()->getRequestVar();?>][]"
                        value="<?= $block->escapeHtml($filterItem->getValueString());?>"
                        type="<?= /* @noEscape */ $inputType;?>"
                        style="<?= /* @noEscape */ $style ?>"
                    <?= /* @noEscape */ $block->checkedFilter($filterItem) ? ' checked' : ''; ?>
                />

                <a class="am-filter-item-<?= /* @noEscape */ $block->escapeId(uniqid())?>"
                    data-am-js="filter-item-default"
                    data-gtm-event="<?= \SM\GTM\Helper\Data::LAYER_FILTER_CLICK_EVENT_NAME ?>"
                    data-gtm='{"name": "<?= addslashes($block->getFilter()->getName()) ?>", "option": "<?= /* @noEscape */ $displayLabel ?>"}'
                    data-gtm-name="<?= \SM\GTM\Helper\Data::LAYER_FILTER_KEY_NAME ?>"
                    href="<?= $block->escapeUrl($filterItem->getUrl()) ?>"
                    <?= /* @noEscape */ $filterSetting->isAddNofollow() ? ' rel="nofollow"' : '' ?>
                >

                    <span class="label"><?= /* @noEscape */ $optionLabel;?></span>
                    <?php if ($filterSetting->isShowProductQuantities()): ?>
                        <?php //Delete spaces around counter ?>
                        <span class="count"><?= /* @noEscape */ $filterItem->getCount(); ?><span class="filter-count-label">
                                <?php $title = ($filterItem->getCount() == 1) ? __('item') : __('items');?><?= /* @noEscape */ $block->escapeHtml($title) ?></span></span>
                    <?php endif; ?>
                </a>
            <?php else: ?>
                <span class="label"><?= /* @noEscape */ $optionLabel;?></span>
                <?php if ($filterSetting->isShowProductQuantities()): ?>
                    <?php //Delete spaces around counter ?>
                    <span class="count"><?= /* @noEscape */ $filterItem->getCount(); ?><span class="filter-count-label">
                            <?php $title = ($filterItem->getCount() == 1) ? __('item') : __('items');?><?= $block->escapeHtml($title) ?></span></span>
                <?php endif; ?>
            <?php endif; ?>
            </li>
        <?php endforeach ?>
    </ol>
</form>

