<?php
/**
 * @category    SM
 * @package     SM_Customer
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 * @author      Logan Ta <phuongtt2@smartosc.com>
 *
 * @copyright   Copyright (c) SmartOSC. All rights reserved.
 * @url http://www.smartosc.com/
 */
/** @var \SM\Customer\Block\Form\ForgotPassword $block */
if (!$block->isLoggedIn()) :
    ?>
    <div class="block-container-signin block-container--notify-email" id="tab-notify-email" style="display: none;">
        <button class="action-close" selector="close" type="button">
            <span><?= __('Close') ?></span>
        </button>
        <div class="notify-email-notification-field" id="notify-email-success-field"></div>
        <div class="block-content" aria-labelledby="block-customer-notify-email-heading">
            <fieldset class="fieldset notify-email">
                <div class="field fgPass-request">
                    <div class="control">
                        <div id="email-forgot-pass-image">
                            <img src='<?= $block->escapeUrl($block->getViewFileUrl('images/email-confirm.png')); ?>' alt="success forgot password">
                        </div>
                    </div>
                </div>
                <div class="txt-notifi-email">
                    <p><?= __('We have sent a verification email to') //phpcs:ignore Magento2.Security.XssTemplate.FoundUnescaped?></p>
                    <p class="email-send" id="emailSend"></p>
                    <p><?= __('Please check your inbox.') //phpcs:ignore Magento2.Security.XssTemplate.FoundUnescaped?></p>
                </div>
            </fieldset>
        </div>
    </div>
    <script type="text/javascript">
        require(
            [
                'ForgotPasswordConfirm',
                'domReady!'
            ],
            function(ForgotPasswordConfirm) {
                ForgotPasswordConfirm.init();
            }
        );
    </script>
<?php endif; ?>
