<?php
/**
 * SMCommerce
 *
 * @category  Amasty
 * @package   Amasty_Shopby
 *
 * Date: May, 26 2020
 * Time: 2:24 PM
 * User: VooThanh DEV
 *
 * @author    SMCommerce Core Team <connect@smartosc.com>
 * @copyright Copyright SMCommerce (http://smartosc.com/)
 */ ?>
<?php /** @var $block \Amasty\Shopby\Block\Navigation\FilterCollapsing */ ?>
<script type="text/x-magento-init">
    {
        ".sidebar #narrow-by-list": {
            "SM_Theme/js/accordion": {
                "multipleCollapsible": true,
                "active": [0, 1, 2, 3, 4]
            }
        }
    }
</script>
