<?php
/**
 * @project    ct-corp-transmart
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author     Duc Nguyen Hoang <ducnh2@smartosc.com>
 * @copyright  Copyright © 2020 SmartOSC. All rights reserved.
 * @url        http://www.smartosc.com
 */
/** @var \SM\Help\Block\Help\Question $block */
?>
<?php
$currentTopic = $block->getCurrentTopic();
$currentQuestion = $block->getCurrentQuestion();
?>
<div class="help-pages">
    <div class="go-back">
        <div class="icon ic-arrow-prev"></div>
        <a href="<?= $block->escapeUrl($currentTopic->getUrl()) ?>"><?= $block->escapeHtml('Back') ?></a>
    </div>
    <!------site content------>
    <div class="help-content">
        <?= $block->getChildHtml('help.search') ?>
        <?= $block->getChildHtml('breadcrumbs') ?>

        <div class="help-content-list">
            <div class="help-content-list-top">
                <h2><?= $block->escapeHtml($currentQuestion->getTitle()) ?></h2>
            </div>
            <div class="help-question-content">
                <?= /* @noEscape */ $block->getQuestionContent($currentQuestion) ?>
            </div>
        </div>

        <div class="help-content-contact">
            <h2><?= $block->escapeHtml(__('Need more information?')) ?></h2>
            <p><?= $block->escapeHtml(__('Send your questions to Transmart Customer Service')) ?></p>
            <a href="<?= $block->getUrl('help/contactus') ?>"><button class="primary"><?= $block->escapeHtml(__('Contact Us'))?></button></a>
        </div>
    </div>
    <!------site content------>

    <!------site bar left------>
    <div class="sidebar sidebar-main">
        <div class="block block-collapsible-nav">
            <div class="title block-collapsible-nav-title">
                <?php $parentTopic = $block->getParentTopic($currentTopic) ?>
                <?php if ($parentTopic) : ?>
                    <strong>
                        <?= $block->escapeHtml($parentTopic->getParentId() != 0 ? $parentTopic->getName() : __('Help Center')) ?>
                    </strong>
                <?php endif; ?>
            </div>
            <div class="content block-collapsible-nav-content" id="block-collapsible-nav">
                <ul class="nav items">
                    <?php $sameParentTopics = $block->getSameParentTopics() ?>
                    <?php if (count($sameParentTopics)) : ?>
                        <?php /** @var \SM\Help\Model\Topic $item */?>
                        <?php foreach ($sameParentTopics as $item) : ?>
                            <li class="nav item <?= $item->getId() === $currentTopic->getId() ? 'active': '' ?>">
                                <a href="<?= $block->escapeUrl($item->getUrl()) ?>">
                                    <?= $block->escapeHtml($item->getName()) ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php if ($currentTopic->getLevel() == 1) : ?>
                    <li class="nav item">
                        <a href="<?= $block->getUrl('help/contactus') ?>">
                            <?= $block->escapeHtml(__('Contact Us')) ?>
                        </a>
                    </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
    <!------site bar left------>

</div>

