<?php
/**
 * @project    ct-corp-transmart
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author     Duc Nguyen Hoang <ducnh2@smartosc.com>
 * @copyright  Copyright © 2020 SmartOSC. All rights reserved.
 * @url        http://www.smartosc.com
 */

/**
 * @var \SM\Help\ViewModel\Search $viewModel
 */
$viewModel = $block->getViewModel();
?>
<div class="help-search sortby-dropdown">
    <div class="control">
        <a href="#"><span class="apl-ic_search"></span></a>

        <input id="help-search" type="text" name="q-help" value=""
               placeholder="<?= $block->escapeHtml(__('Type to search topic (example: refund)'))?>"
               class="input-text" maxlength="128" autofocus
                />
        <span class="search-primary-loader action-primary-loader" style="display: none;"></span>
    </div>
    <ul class="autocomplete-results dropdown"></ul>
</div>
<script type="text/x-magento-init">
    {
        "#help-search": {
            "searchQuestions": {
                "currentStoreCode": "<?= $block->escapeJs($viewModel->getCurrentStoreCode()) ?>",
                "questionBaseUrl": "<?= $block->escapeJs($viewModel->getQuestionBaseUrl()) ?>",
                "urlSuffix": "<?= $block->escapeJs($viewModel->getQuestionUrlSuffix()) ?>"
            }
        }
    }
</script>

