<?php /** @var $block \Magento\Catalog\Block\Product\Image */ die('3')?>

<img class="photo image lazy"
    <?= /* @escapeNotVerified */ $block->getCustomAttributes() ?>
    src="<?= /* @escapeNotVerified */ $block->getImageUrl() ?>"
    width="<?= /* @escapeNotVerified */ $block->getWidth() ?>"
    height="<?= /* @escapeNotVerified */ $block->getHeight() ?>"
    alt="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true) ?>" />
