<?php
/**
 * @category Trans
 * @package  Trans_Customer
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author   Imam Kusuma <imam.kusuma@ctcorpdigital.com>
 * @edit     Muhammad Randy <muhammad.randy@ctcorpdigital.com>
 * Copyright © 2019 CT Corp Digital. All rights reserved.
 * http://www.ctcorpora.com
 */
?>
<?php $edit = $this->getUrl('customer/address/new/'); ?>
<?php $create = $this->getUrl('customer/address/form/') ?>
<?php $current = $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>

<div class="field required fullname <?= $block->escapeHtmlAttr($block->getContainerClassName()) ?>">
    <?php if ($current == $edit || $current == $create) { ?>
        <label class="label"
               for="<?= $block->escapeHtmlAttr($block->getFieldId('fullname')) ?>"><span><?= $block->escapeHtml(__('Recipient Name')) ?></span></label>
    <?php } else { ?>
        <label class="label"
               for="<?= $block->escapeHtmlAttr($block->getFieldId('fullname')) ?>"><span><?= $block->escapeHtml(__('Full Name')) ?></span></label>
    <?php } ?>
    <div class="control">
        <fieldset class="fieldset fieldset-fullname">
            <div class="fields">
                <div class="field field-name-fullname required">
                    <div class="control">
                        <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('fullname')) ?>"
                               name="<?= $block->escapeHtmlAttr($block->getFieldName('fullname')) ?>"
                               value="<?= $block->escapeHtmlAttr($block->getObject()->getFullname()) ?>"
                               title="<?= $block->escapeHtmlAttr($block->getStoreLabel('fullname')) ?>"
                               class="validate-length minimum-length-3 maximum-length-50 input-text <?= $block->escapeHtmlAttr($block->getAttributeValidationClass('fullname')) ?>"
                               data-validate="{required:true, 'validate-length':true}">
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>
