<?php
/**
 * @category    Ves
 * @package     Ves_Megamenu
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 * @author      Logan Ta <phuongtt2@smartosc.com>
 *
 * @copyright   Copyright (c) SmartOSC. All rights reserved.
 * @url http://www.smartosc.com/
 */
?>
<div class="wrapper-jsmegamenu">
    <div class="jsmegamenu-action" data-bind="scope: 'jsmegamenu'">
        <script type="text/x-magento-init">
            {
                ".nav-sections": {
                    "Magento_Ui/js/core/app": {
                        "components": {
                            "jsmegamenu": {
                                "component": "Ves_Megamenu/js/view/jstopmenu"
                                        }
                                    }
                                }
                }
            }
        </script>
    </div>
</div>

