<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Weee\Block\Item\Price\Renderer */

$item = $block->getItem();
$regularPriceTotal = $block->getRegularPrice($item->getProduct()) * $item->getQty();
$finalPriceTotal = $item->getPrice()*$item->getQty();

$freshHelper = $this->helper('SM\FreshProduct\Helper\Data');
$product = $item->getProduct();
?>
<?php if (($block->displayPriceInclTax() || $block->displayBothPrices()) && !$item->getNoSubtotal()) : ?>
    <span class="price-including-tax" data-label="<?= $block->escapeHtmlAttr(__('Incl. Tax')) ?>">
        <?php if ($block->displayPriceWithWeeeDetails()) : ?>
            <span class="cart-tax-total"
                data-mage-init='{"taxToggle": {"itemTaxId" : "#subtotal-item-tax-details<?= (int) $item->getId() ?>"}}'>
        <?php else : ?>
            <span class="cart-price">
        <?php endif; ?>
            <?php if ($regularPriceTotal == $finalPriceTotal):?>
            <span class="price-box">
                 <?= /* @noEscape */ $block->formatPrice($finalPriceTotal) ?>
            </span>
            <?php else:?>
            <span class="old-price" style="display: <?=$freshHelper->isShowPromoPrice($product) ? 'none':'block'?> ;">
                <?= /* @noEscape */ $block->formatPrice($regularPriceTotal) ?>
            </span>
            <span class="special-price">
                <?= /* @noEscape */ $block->formatPrice($finalPriceTotal) ?>
            </span>
            <?php endif;?>
            </span>

        <?php if ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($item)) : ?>
            <div class="cart-tax-info" id="subtotal-item-tax-details<?= (int) $item->getId() ?>" style="display: none;">
                <?php foreach ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($item) as $tax) : ?>
                    <span class="weee" data-label="<?= $block->escapeHtmlAttr($tax['title']) ?>">
                        <?= /* @noEscape */ $block->formatPrice($tax['row_amount_incl_tax'], true, true) ?>
                    </span>
                <?php endforeach; ?>
            </div>

            <?php if ($block->displayFinalPrice()) : ?>
                <span class="cart-tax-total"
                    data-mage-init='{"taxToggle": {"itemTaxId" : "#subtotal-item-tax-details<?= (int) $item->getId() ?>"}}'>
                    <span class="weee" data-label="<?= $block->escapeHtmlAttr(__('Total Incl. Tax')) ?>">
                    <?php if ($regularPriceTotal == $finalPriceTotal):?>
                    <span class="price-box">
                        <?= /* @noEscape */ $block->formatPrice($finalPriceTotal) ?>
                    </span>
                    <?php else:?>
                    <span class="old-price" style="display: <?=$freshHelper->isShowPromoPrice($product) ? 'none':'block'?> ;">
                        <?= /* @noEscape */ $block->formatPrice($regularPriceTotal) ?>
                    </span>
                    <span class="special-price">
                        <?= /* @noEscape */ $block->formatPrice($finalPriceTotal) ?>
                    </span>
                    <?php endif;?>
                    </span>
                </span>
            <?php endif; ?>
        <?php endif; ?>
    </span>
<?php endif; ?>

<?php if ($block->displayPriceExclTax() || $block->displayBothPrices()) : ?>
    <span class="price-excluding-tax" data-label="<?= $block->escapeHtmlAttr(__('Excl. Tax')) ?>">
        <?php if ($block->displayPriceWithWeeeDetails()) : ?>
            <span class="cart-tax-total"
                data-mage-init='{"taxToggle": {"itemTaxId" : "#esubtotal-item-tax-details<?= (int) $item->getId() ?>"}}'>
        <?php else : ?>
            <span class="cart-price">
        <?php endif; ?>
            <?php if ($regularPriceTotal == $finalPriceTotal):?>
            <span class="price-box">
                <?= /* @noEscape */ $block->formatPrice($finalPriceTotal) ?>
            </span>
            <?php else:?>
            <span class="old-price" style="display: <?=$freshHelper->isShowPromoPrice($product) ? 'none':'block'?> ;">
                <?= /* @noEscape */ $block->formatPrice($regularPriceTotal) ?>
            </span>
            <span class="special-price">
                <?= /* @noEscape */ $block->formatPrice($finalPriceTotal) ?>
            </span>
            <?php endif;?>
            </span>

        <?php if ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($item)) : ?>
            <span class="cart-tax-info" id="esubtotal-item-tax-details<?= (int) $item->getId() ?>"
                style="display: none;">
                <?php foreach ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($item) as $tax) : ?>
                    <span class="weee" data-label="<?= $block->escapeHtmlAttr($tax['title']) ?>">
                        <?= /* @noEscape */ $block->formatPrice($tax['row_amount'], true, true) ?>
                    </span>
                <?php endforeach; ?>
            </span>

            <?php if ($block->displayFinalPrice()) : ?>
                <span class="cart-tax-total"
                      data-mage-init='{"taxToggle": {"itemTaxId" : "#esubtotal-item-tax-details<?= (int) $item->getId() ?>"}}'>
                    <span class="weee" data-label="<?= $block->escapeHtmlAttr(__('Total')) ?>">
                    <?php if ($regularPriceTotal == $finalPriceTotal):?>
                    <span class="price-box">
                        <?= /* @noEscape */ $block->formatPrice($finalPriceTotal) ?>
                    </span>
                    <?php else:?>
                    <span class="old-price" style="display: <?=$freshHelper->isShowPromoPrice($product) ? 'none':'block'?> ;">
                        <?= /* @noEscape */ $block->formatPrice($regularPriceTotal) ?>
                    </span>
                    <span class="special-price">
                        <?= /* @noEscape */ $block->formatPrice($finalPriceTotal) ?>
                    </span>
                    <?php endif;?>
                    </span>
                </span>
            <?php endif; ?>
        <?php endif; ?>
    </span>
<?php endif; ?>
