<?php
/** @var \SM\DigitalProduct\Block\MobilePackage\ProductList $block*/

$c1Categories = $block->getC1Categories();
$operator = $block->getOperator();
?>
<?php $position = 1; ?>
<?php if (count($c1Categories)):?>
    <?php foreach ($c1Categories as $key => $c1Category):?>
        <label class="radio-custom-checkmark">
            <?php if ($key == 0):?>
                <?= $block->escapeHtml(__(\SM\DigitalProduct\Model\CategoryRepository::MOBILE_PACKAGE_INTERNET_TITLE))?>
            <?php else:?>
                <?= $block->escapeHtml(__(\SM\DigitalProduct\Model\CategoryRepository::MOBILE_PACKAGE_ROAMING_TITLE))?>
            <?php endif;?>
            <input class="check-type" type="radio"
                   value="<?= $c1Category->getMagentoCategoryId()?>"
                   data-type="<?= $c1Category->getType() ?>"
                   name="category_id" <?= (($key == 0) ? 'checked' : '')?>>
            <label class="type-name checkmark"></label>
        </label>
    <?php endforeach;?>
    <?php if (!is_null($operator)):?>
        <input type="hidden" value="<?= $operator->getOperatorName()?>" name="digital[operator]"/>
    <?php endif;?>
    <h3 class="title-nom"><?= $block->escapeHtml(__("Packages"))?></h3>
    <?php foreach ($c1Categories as $key => $c1Category):?>
        <ul id="list<?= $c1Category->getMagentoCategoryId()?>" class="list-nomial mobilepackage" <?= (($key != 0) ? 'style="display: none"' : '')?>>
            <?php
            /** @var \Magento\Catalog\Api\Data\ProductInterface $product */
            foreach ($c1Category->getProducts() as $pKey => $product):?>
                <?php
                $denom = $product->getCustomAttribute("denom");
                $denom = is_null($denom) ? "" : $denom->getValue();

                $productIdVendor = $product->getCustomAttribute("product_id_vendor");
                $productIdVendor = is_null($productIdVendor) ? "0" : $productIdVendor->getValue();

                $price = $product->getPriceInfo()->getPrice('final_price')->getValue();
                $variantGtm = $block->priceFormat($price);
                $brandGtm = $operator ? $operator->getOperatorName() : "Not Available";

                $gtmDigital = Zend_Json_Encoder::encode([
                    'product_id' => $product->getSku(),
                    'product_name' => $product->getName(),
                    'product_price' => $price,
                    'product_brand' => $brandGtm,
                    'product_variant' => $variantGtm,
                    'product_position' => $position
                ]);
                ?>
                <li class="item" <?php if ($gtmDigital) : ?>
                    data-gtm="<?= $block->escapeHtml($gtmDigital) ?>"
                    data-gtm-event="digital_product_buy"
                <?php endif; ?>>
                    <label style="cursor: pointer">
                        <div class="dpb-inner-content">
                            <h4 class="denom"><?= $product->getName() ?></h4>
                            <div class="price-box">
                                <?php if ($product->getSpecialPrice()) : ?>
                                    <p class="old-price">
                                        <span class="price-label"><?= $block->escapeHtml(__("Price: "))?></span>
                                        <span class="price"><?= $block->priceFormat($product->getPrice())?></span>
                                    </p>
                                    <p class="special-price ">
                                        <span class="price-label"><?= $block->escapeHtml(__("Price: "))?></span>
                                        <span class="price"><?= $block->priceFormat($price)?></span>
                                    </p>
                                <?php else: ?>
                                    <p class="regular-price">
                                        <span class="price-label"><?= $block->escapeHtml(__("Price: "))?></span>
                                        <span class="price"><?= $block->priceFormat($price)?></span>
                                    </p>
                                <?php endif; ?>
                            </div>
                            <input class="product-item" type="radio" value="<?= $product->getSku()?>" name="sku"
                                   data-product-price="<?= $block->priceFormat($price)?>"
                                   data-product-price-value="<?= $price ?>"
                                   data-product-id-vendor="<?= $productIdVendor ?>"
                                   data-product-desc="<?= $product->getDescription() ?>"
                                   data-product-name="<?= $product->getName() ?>"
                                   style="display: none"/>
                        </div>
                    </label>
                </li>
                <?php $position++; ?>
            <?php endforeach;?>
        </ul>
    <?php endforeach;?>
<?php endif;?>
