<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
/** @var \Magento\Wishlist\ViewModel\AllowedQuantity $viewModel */
$viewModel = $block->getData('allowedQuantityViewModel');
$allowedQty = $viewModel->setItem($item)->getMinMaxQty();
?>
<?php if (!$product->getData('hide_cta_button')) : ?>
    <?php foreach ($block->getChildNames() as $childName) : ?>
        <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false) ?>
    <?php endforeach;?>
    <div class="box-tocart">
        <fieldset class="fieldset">
        <?php if ($product->isSaleable()) : ?>
            <?php $childrenIds = $product->getTypeInstance()->getChildrenIds($product->getId()); ?>
            <?php if ($childrenIds): ?>
                <a title="<?= $block->escapeHtmlAttr(__('View Details')) ?>"
                   href="<?= $block->escapeHtmlAttr($product->getProductUrl()) ?>"
                   class="action view-details primary">
                    <?= $block->escapeHtml(__('View Details')) ?>
                </a>
            <?php else:?>
                <div class="product-item-actions">
                    <div class="actions-primary">
                        <button type="button" data-role="tocart" data-post='<?= /* @noEscape */ $block->getItemAddToCartParams($item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" data-item-id="<?= $block->escapeHtmlAttr($item->getId()) ?>" class="action tocart primary">
                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                        </button>
                    </div>
                </div>
            <?php endif;?>
        <?php else : ?>
            <?php if ($product->getIsSalable()) : ?>
                <p class="available stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                    <span><?= $block->escapeHtml(__('In stock')) ?></span>
                </p>
            <?php else : ?>
                <p class="unavailable stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                </p>
            <?php endif; ?>
        <?php endif; ?>
        </fieldset>
    </div>
<?php endif; ?>
