<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Image $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
/** @var \SM\ShoppingList\ViewModel\ItemViewModel $viewModel */
$viewModel = $block->getData("viewModel");
$label = $viewModel->getLabel($product);
?>
<a class="product-item-photo" tabindex="-1" href="<?= $block->escapeUrl($product->getProductUrl()) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>">
    <?= $block->getImage($block->getProductForThumbnail($item), 'wishlist_thumbnail')->toHtml() ?>
    <?php $percent = $viewModel->getDiscountPercent($product); ?>
    <?php if ($percent != null && $percent > 0) : ?>
        <span class="product-sale">
            <?= $block->escapeHtml(__('%1% OFF', $percent)); ?>
        </span>
    <?php endif; ?>
    <span class="product-stock popular-sale-count-<?php echo $product->getId() ?>" style="display: none"></span>

    <?php $count = $viewModel->countProductChildren($product); ?>
    <?php if ($count): ?>
        <div class="swatch-options">
            <span class="oval-swatch oval-black"></span>
            <span class="oval-swatch oval-pink"></span>
            <span class="oval-swatch oval-dark-blue"></span>
            <span class="oval-swatch oval-dark-blue2"></span>
            <span class="oval-number"><?= $count ?></span>
        </div>
    <?php endif; ?>
</a>
<div class="shoppinglist-item-label"><?= $label ?></div>
