<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart $block */

/** @var \SM\ShoppingList\ViewModel\ItemViewModel $viewModel */
$viewModel = $block->getData("viewModel");
?>
<div class="product-price">
    <?= $viewModel->getProductPrice($block->getItem()->getProduct()) ?>
</div>
<?php foreach ($block->getChildNames() as $childName) : ?>
    <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false) ?>
<?php endforeach;?>
