<?php

/**
 * SMCommerce
 *
 * @category  Trans
 * @package   Trans_CustomerMyProfile
 *
 * Date: April, 25 2020
 * Time: 8:26 AM
 * User: VooThanh DEV
 *
 * @author    SMCommerce Core Team <connect@smartosc.com>
 * @copyright Copyright SMCommerce (http://smartosc.com/)
 */
?>
<?php /** @var $block \Trans\CustomerMyProfile\Block\MyProfile\Edit\EditEmail */ ?>
<form class="form form-edit-account" action="<?= $block->escapeUrl($block->getUrl('customermyprofile/email/save')) ?>" method="post" id="form-edit-email" enctype="multipart/form-data" data-mage-init='{"validation": {}}' autocomplete="off">
    <legend class="legend"><span><?= $block->escapeHtml(__('Edit Email')) ?></span></legend><br>
    <fieldset class="fieldset change-email password" data-container="change-email-password" style="display: block;">
        <div class="field email" data-container="change-email">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email" autocomplete="email" data-input="change-email"
                       value="<?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       class="input-text validateee-customer-email validate-email-not-change" data-validate="{'required':true}"
                        data-current-email="<?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>"/>
                <div class="trans-message-error email-msg"></div>
                <div class="tooltip">
                    <img src='<?= $block->getViewFileUrl('images/info.svg'); ?>' alt=""  width="13" height="16" />
                    <span class="tooltiptext">
                        <?= $block->escapeHtml(__('You will receive a verification link by saving the change.')) ?>
                    </span>
                </div>
            </div>
        </div>
    </fieldset>

    <div class="actions-toolbar">
        <a href="<?= $block->getUrl('customer/account') ?>" class="profile-cancel action">
            <?= $block->escapeHtml(__('Cancel')) ?>
        </a>
        <button type="submit" class="profile-save primary action"><?= $block->escapeHtml(__('Save')) ?></button>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "*": {
            "Trans_CustomerMyProfile/js/email": {
                "formSelector": "#form-edit-email",
                "emailSelector": "#form-edit-email input[name=email]",
                "resetButtonSelector": "#form-edit-email button.profile-cancel",
                "email": "<?= $block->getCustomer()->getEmail(); ?>",
                "emailMsg": "#form-edit-email .email-msg"
            },
            "validateCustomerEmail" : {}
        }
    }
</script>
