<?php
/**
 * @category Magento
 * @package Magento_Catalog
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 * @author      Logan Ta <phuongtt2@smartosc.com>
 *
 * @copyright   Copyright (c) SmartOSC. All rights reserved.
 * @url http://www.smartosc.com/
 */
?>
<div class="object-connect-info" id="object-connect">
    <div class="available-delivery">
        <div class="block-delivery-infor">
            <span class="apl-ic-delivery-short"></span> <?= $block->escapeHtml(__('Available for Delivery')) ?>
        </div>
        <a href="#" class="delivery-infor" id="pdp-delivery-info" data-gtm-pdp="delivery-info">
            <?= $block->escapeHtml(__('Delivery info')) ?>
        </a>
    </div>
    <div class="available-pickup">
        <div class="block-delivery-infor">
            <span class="apl-ic-pickup"></span> <?= $block->escapeHtml(__('Available for Pick Up')) ?>
        </div>
        <a href="#" class="store-infor pdp-store-info" id="pdp-store-info" data-gtm-pdp="store-info">
            <?= $block->escapeHtml(__('Store info')) ?>
        </a>
    </div>
    <div class="available-pickup">
        <div class="block-delivery-infor" style="color:dodgerblue;cursor:pointer;">
            <span class="apl-ic-pickup apl-ic-store"></span> <span class="pdp-store-info-text  pdp-store-info"><?= $block->escapeHtml(__('Stores Have Stock')) ?></span>
        </div>
    </div>
</div>
