<?php
// @codingStandardsIgnoreFile

/** @var \SM\Customer\Block\Form\Login $block */
if (!$block->isLoggedIn()) : ?>

<?php
$helper = $this->helper(SM\AndromedaSms\Helper\Config::class);
$countdownTime = $helper->getVerificationCodeExpiredIn();
$stores = $block->getStores();

?>


    <div class="block-container-signin" id="tab-login" style="display: none;">
        <div class="row no-gutters">
            <div class="container-signin--left col-xs-12 col-xl-6">

                <div class="storeview-flags">
                    <div class="drop-down">
                        <select name="options">
                            <?php foreach ($stores as $store) :?>
                                <option class="<?= $store->getCode()?>" value="<?= $store->getCode()?>"
                                     style="background-image:url('<?= $block->getStoreviewFlags($store->getId())?>');"
                                        urlStore="<?= $block->getStoreUrl($store->getCode()) ?>"
                                    <?= ($store->getCode() == $block->getCurrentStoreCode()) ? 'selected' : ''?>
                                    data-href="<?= $block->getTargetStoreRedirectUrl($store) ?>"
                                        data-is-select="<?= (($store->getId() == $block->getCurrentStoreId()) ? 1 : 0)?>"
                                >
                                    <?= $block->getAbbreviationName($store->getId())?>
                                </option>
                            <?php endforeach;?>
                        </select>
                    </div>
                </div>

                <img src='<?= $block->escapeUrl($block->getViewFileUrl('images/reliable.jpg')); ?>' alt="Welcome" loading="lazy" width="585" height="859">
            </div>
            <div class="container-signin--right col-xs-12 col-xl-6">
                <div class="container-signin--content">

                    <div class="block-title block-title-signin">
                        <button type="button" class="action-back" selector="action-back" style="display: none">
                            <i class="icon ic-black"> </i>
                        </button>
                        <strong id="block-customer-login-heading" selector="block-customer-login-heading" role="heading" aria-level="2">
                            <?= $block->escapeHtml(__('Sign In')) ?>
                        </strong>
                        <div class="welcome-eco-user" selector="welcome-eco-user" style="display: none;">
                            <span id="welcome-eco-image"><img class="sociallogin-button-icon-image active" src='<?php echo $this->getViewFileUrl('SM_Customer::images/ct-crop.png'); ?>' alt="CT Corp" loading="lazy"></span>
                            <div class="block-subtitle--welcome"><span id="welcome-eco-title" selector="welcome-eco-title"><?= $block->escapeHtml(__('Welcome,')) ?></span>
                                <span class="block-subtitle--name" id="welcome-eco-fullname" selector="welcome-eco-fullname"></span></div>
                        </div>
                        <div class="user-eco-confirm" selector="user-eco-confirm" style="display: none;">
                            <span><?= __('You have been registered in other apps or brands of CT Corp. Please confirm your account.'); ?></span>
                        </div>
                    </div>
                    <div class="login-notification-field" id="login-success-field"></div>
                    <div class="block-content" aria-labelledby="block-customer-login-heading">
                        <form class="form-customer-login"
                              id="form-customer-login"
                              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
                              method="post"
                              data-mage-init='{"validation":{}}'>
                            <?= $block->getBlockHtml('formkey'); ?>
                            <fieldset class="fieldset login">
                                <!--user-->
                                <div class="field username field-username-edit fieldInputText" selector="username-block">
                                    <label class="label" for="username">
                                        <span><?= /* @escapeNotVerified */ __('Email or Mobile Number') ?></span>
                                    </label>
                                    <div class="control">
                                        <input name="username"
                                               id="username" type="text" class="input-text"
                                               title="<?= /* @escapeNotVerified */ __('Email or Mobile Number') ?>"
                                               data-validate="{required:true, 'validate-username':true}"
                                               autocomplete="off"/>
                                    </div>
                                    <div generated="true" class="mage-error" id="user-not-exist" style="display: none"></div>
                                </div>

                                <!--mobile_number-->
                                <div class="field mobile_number-lock fieldInputText" selector="mobile_number-block" style="display: none">
                                    <label class="label" for="mobile_number">
                                        <label class="label" for="delivery-area"><span><?= __('XXX Area') //phpcs:ignore Magento2.Security.XssTemplate.FoundUnescaped?></span></label>
                                    </label>
                                    <div class="control">
                                        <input name="mobile_number"
                                               id="mobile_number" selector="mobile-number-input" type="text" class="input-text"
                                               title="<?= /* @escapeNotVerified */ __('Mobile Number') ?>" value=""
                                               autocomplete="off" readonly/>
                                    </div>
                                </div>

                                <!--user_eco_field-->
                                <div class="field user_eco_data fieldInputText" style="display: none">
                                    <input id="eco_email" name="eco_email" selector="eco_email" type="hidden"/>
                                    <input id="eco_firstname" name="eco_firstname" selector="eco_firstname" type="hidden"/>
                                    <input id="eco_lastname" name="eco_lastname" selector="eco_lastname" type="hidden"/>
                                    <input id="eco_phonenumber" name="eco_phonenumber" selector="eco_phonenumber" type="hidden"/>
                                </div>

                                <!--password-->
                                <div class="field password fieldInputText" selector="password-block" style="display: none">
                                    <label for="pass" class="label">
                                        <span><?= /* @escapeNotVerified */ __('Password') ?></span>
                                    </label>
                                    <div class="control input-group">
                                        <input name="password"
                                               disabled
                                               type="password"
                                               class="input-text" id="pass" title="<?= /* @escapeNotVerified */ __('Password') ?>"
                                               data-validate="{required:true}"
                                               autocomplete="off"/>
                                        <div selector="show-password" class="input-group-prepend input-group-password" id="show-login-password">
                                            <span class="input-group-text" id="inputGroupPrepend">
                                                <a class="input-icon-eye eye-back" href="javascript:void(0)" aria-hidden="true"><svg
                                                        aria-hidden="true" class="stUf5b" fill="currentColor"
                                                        focusable="false" width="19px" height="19px" viewBox="0 0 24 24"
                                                        xmlns="https://www.w3.org/2000/svg"><path
                                                            d="M10.58,7.25l1.56,1.56c1.38,0.07,2.47,1.17,2.54,2.54l1.56,1.56C16.4,12.47,16.5,12,16.5,11.5C16.5,9.02,14.48,7,12,7 C11.5,7,11.03,7.1,10.58,7.25z"></path><path
                                                            d="M12,6c3.79,0,7.17,2.13,8.82,5.5c-0.64,1.32-1.56,2.44-2.66,3.33l1.42,1.42c1.51-1.26,2.7-2.89,3.43-4.74 C21.27,7.11,17,4,12,4c-1.4,0-2.73,0.25-3.98,0.7L9.63,6.3C10.4,6.12,11.19,6,12,6z"></path><path
                                                            d="M16.43,15.93l-1.25-1.25l-1.27-1.27l-3.82-3.82L8.82,8.32L7.57,7.07L6.09,5.59L3.31,2.81L1.89,4.22l2.53,2.53 C2.92,8.02,1.73,9.64,1,11.5C2.73,15.89,7,19,12,19c1.4,0,2.73-0.25,3.98-0.7l4.3,4.3l1.41-1.41l-3.78-3.78L16.43,15.93z M11.86,14.19c-1.38-0.07-2.47-1.17-2.54-2.54L11.86,14.19z M12,17c-3.79,0-7.17-2.13-8.82-5.5c0.64-1.32,1.56-2.44,2.66-3.33 l1.91,1.91C7.6,10.53,7.5,11,7.5,11.5c0,2.48,2.02,4.5,4.5,4.5c0.5,0,0.97-0.1,1.42-0.25l0.95,0.95C13.6,16.88,12.81,17,12,17z"></path></svg></a>
                                                <a class="input-icon-eye eye-front " href="javascript:void(0)" aria-hidden="true"><svg
                                                        aria-hidden="true" class="stUf5b" fill="currentColor"
                                                        focusable="false" width="19px" height="19px" viewBox="0 0 24 24"
                                                        xmlns="https://www.w3.org/2000/svg"><path
                                                            d="M12,7c-2.48,0-4.5,2.02-4.5,4.5S9.52,16,12,16s4.5-2.02,4.5-4.5S14.48,7,12,7z M12,14.2c-1.49,0-2.7-1.21-2.7-2.7 c0-1.49,1.21-2.7,2.7-2.7s2.7,1.21,2.7,2.7C14.7,12.99,13.49,14.2,12,14.2z"></path><path
                                                            d="M12,4C7,4,2.73,7.11,1,11.5C2.73,15.89,7,19,12,19s9.27-3.11,11-7.5C21.27,7.11,17,4,12,4z M12,17 c-3.79,0-7.17-2.13-8.82-5.5C4.83,8.13,8.21,6,12,6s7.17,2.13,8.82,5.5C19.17,14.87,15.79,17,12,17z"></path></svg></a>

                                            </span>
                                        </div>
                                    </div>
                                    <div generated="true" class="mage-error" id="wrong-password-field" style="display: none"></div>
                                </div>

                                <!--Delivery and district-->
                                <div class="field delivery-area actions-toolbar" selector="delivery-district" style="display: none">
                                    <div class="row">
                                        <div class="col-xs-6 col-md-6">
                                            <label class="label" for="delivery-area"><span><?= __('Delivery Area') //phpcs:ignore Magento2.Security.XssTemplate.FoundUnescaped?></span></label>
                                            <div class="autocomplete dropdown-city">
                                                <div class="dropdown-toggle">
                                                    <label for="city"/>
                                                    <input autocomplete="<?= substr(md5(mt_rand()), 0, 7); ?>" id="city" selector="city" type="text" placeholder="<?= $block->escapeHtml(__('Select City')) ?>" data-validate='{"required":true}' />
                                                </div>

                                                <ul id="city-list" class="dropdown" selector="city-list" style="display: none"></ul>
                                            </div>
                                        </div>
                                        <div class="col-xs-6 col-md-6">
                                            <div class="autocomplete  dropdown-city">

                                                <label class="label" for="delivery-area"><span><?= __('District') //phpcs:ignore Magento2.Security.XssTemplate.FoundUnescaped?></span></label>
                                                <div class="dropdown-toggle">
                                                <span class="action toggle district-fake-current" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" aria-haspopup="true">
                                                    <span><?= $block->escapeHtml(__('Select District')) ?></span>
                                                </span>
                                                </div>
                                                <ul class="dropdown district-fake" data-role="sorter">
                                                </ul>
                                                <div class="select-district">
                                                    <select class="" id="district" name="district" placeholder="<?= __('District') //phpcs:ignore Magento2.Security.XssTemplate.FoundUnescaped?>" data-validate='{"required":true}'>
                                                        <optgroup>
                                                            <option value="" ><?= __('Select District') //phpcs:ignore Magento2.Security.XssTemplate.FoundUnescaped?></option>
                                                        </optgroup>
                                                    </select>
                                                    <input id="cityId" name="city" type="hidden"/>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>

                                <!--forgot-->
                                <div class="actions-toolbar" selector="additional" style="display: none">
                                    <div class="row no-gutters">
                                        <div class="col-xs-6 col-md-6 checkbox-remember">
                                            <?= $block->getChildHtml('form.additional.info') ?>
                                        </div>
                                        <div class="col-xs-6 col-md-6">
                                            <div class="secondary">
                                                <a id="action-forgot-password" class="social-login forgot-password" href="#"
                                                    <span><?= /* @escapeNotVerified */ __('Forgot password?') ?></span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <!--otp-->
                                <div id="login-otp" class="otp-block" selector="otp-block" style="display: none">
                                    <div class="txt-description-modal ">
                                        <div class="message-verify">
                                            <span class="block-subtitle-verify" selector="phone-number"><?= $block->escapeHtml(__('We have sent a verification message to ')) ?></span>
                                            <span class="phone-otp" selector="phone-otp"></span>
                                        </div>
                                        <div class="block-subtitle"><?= $block->escapeHtml(__('Enter your code here')) ?></div>
                                    </div>
                                    <div class="digit-group" data-group-name="digits" data-autosubmit="false">
                                        <input disabled class="combine otp-input" type="number" name="digit-1"
                                               data-next="digit-2" maxlength="1" />
                                        <input disabled class="combine otp-input" type="number" name="digit-2"
                                               data-next="digit-3" data-previous="digit-1" maxlength="1" />
                                        <input disabled class="combine otp-input" type="number" name="digit-3"
                                               data-next="digit-4" data-previous="digit-2" maxlength="1" />
                                        <input disabled class="combine otp-input" type="number" name="digit-4"
                                               data-next="digit-5" data-previous="digit-3" maxlength="1" />
                                        <input disabled class="combine otp-input" type="number" name="digit-5"
                                               data-next="digit-6" data-previous="digit-4" maxlength="1" />
                                        <input disabled class="combine otp-input" type="number" name="digit-6"
                                               data-previous="digit-5" maxlength="1" />
                                    </div>
                                   <div class="message-otp-error field-error" id="message-otp-error" selector="message-otp-error"></div>
                                </div>

                                <!--action-->
                                <div class="actions-login">
                                    <button type="submit" class="action login primary" id="form-login">
                                        <span><?= /* @escapeNotVerified */ __('Continue') ?></span>
                                    </button>
                                </div>

                                <!--otp-->
                                <div class="txt-bottom-verify clearfix" selector="otp-block" style="display: none">
                                        <span class="txt-count">
                                            <?= $block->escapeHtml(__('You can try resending the code')) ?>
                                            <span class="txt-second" selector="count">
                                                <?= sprintf(__('in <span>%s</span> second(s).'), $block->escapeHtml($countdownTime)) ?>
                                            </span>
                                        </span>

                                    <a class="txt-resend" href="#" selector="resend-otp"><?= $block->escapeHtml(__('Resend code')) ?></a>
                                </div>
                            </fieldset>
                        </form>
                        <div class="form-login-after" selector="form-login-after">
                            <?= $block->getChildBlock('login.popup.authentication.social')->toHtml(); ?>
                            <div class="create-account">
                                <p><?= /* @escapeNotVerified */ __('Do not have an account?') ?></p>
                                <button type="button" class="action create secondary" id="create-account">
                                    <span><?= /* @escapeNotVerified */ __('Create Account') ?></span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        require(
            [
                'jquery',
                'Magento_Ui/js/modal/modal',
                'FilloutCityDistrict',
                'mage/validation',
                'domReady!'
            ],
            function($, modal, fillOutCityDistrict) {

                $('body').on('click', '#form-login', function() {
                    let loginContainer = $('#tab-login');

                    var loginModal = loginContainer.modal('openModal').show().closest('.modal-popup').addClass('modal-popup-signin');
                    fillOutCityDistrict.create(loginModal);
                });
            }
        );
    </script>
    <script type="text/x-magento-init">
        {
            "*": {
                "SM_Customer/js/login": {
                    "tabLoginSelector": "#tab-login",
                    "checkUserUrl": "<?= $block->escapeUrl($block->getUrl('customer/account/userexist')); ?>",
                    "sendRecoveryUrl": "<?= $block->escapeUrl($block->getUrl('customer/account/sendrecovery')); ?>",
                    "loginUrl": "<?= $block->escapeUrl($block->getAjaxLoginUrl()); ?>",
                    "sendOTPUrl": "<?= $block->escapeUrl($block->getBaseUrl() . 'rest/V1/sms/verification/send'); ?>",
                    "count": <?= $countdownTime ?>
                }
            }
        }
    </script>
<?php endif; ?>
