<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="wrapper-payment">
    <div class="logo-bank">
        <img src='<?= $block->getViewFileUrl('images/payment-success-credit-card.png'); ?>' alt=""  width="461" height="406" />
    </div>

    <div class="success-payment">
        <p class="status-payment"><?= $block->escapeHtml(__('Payment Successful!')) ?></p>
        <p class="text-label-body">01 Nov 2019</p>
    </div>
    <div class="total-payment">
        <label class="text-label-body"><?= $block->escapeHtml(__('Total Payment')) ?></label>
        <p class="text-body">RP 1.499.000</p>
        <span class="text-label-body">Did you know? We don't charge until you receive your order.</span>
    </div>

    <div class="total-payment payment-method">
        <label class="text-label-body"><?= $block->escapeHtml(__('Payment Method')) ?></label>
        <div class="virtual-account">
            <img src='<?= $block->getViewFileUrl('images/visa.png'); ?>' alt=""  width="99" height="40" />
        </div>
    </div>

    <div class="invoice-number">
        <label class="text-label-body"><?= $block->escapeHtml(__('Transaction ID')) ?></label>
        <p class="text-body">ID0839203803</p>
    </div>

    <div class="check-payment-col">
        <button class="action primary" type="button">Back to Home</button>
    </div>
</div>