<?php
/**
 * SMCommerce
 *
 * @category  SM
 * @package   SM_LayeredNavigation
 *
 * Date: April, 27 2020
 * Time: 2:46 PM
 * User: VooThanh DEV
 *
 * @author    SMCommerce Core Team <connect@smartosc.com>
 * @copyright Copyright SMCommerce (http://smartosc.com/)
 */
?>
<?php /** @var $block \SM\LayeredNavigation\Block\Adminhtml\Category\AssignProductAttribute */ ?>
<?= ($grid = $block->getBlockGrid()) ? $grid->toHtml() : '' ?>
