<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="wrapper-voucher">
    <div class="row">
        <div class="col-lg-8 col-md-12 col-sm-12 voucher-left">
            <div class="bg-voucher">
                <div class="title-content">
                    <p class="name">VOUCHER</p>
                    <p class="price">Rp 100.000</p>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-12 col-sm-12 voucher-right">
            <div class="voucher-detail">
                <div class="voucher-detail-title">
                    <p>Voucher Details</p>
                </div>
                <div class="voucher-detail-content">
                    <ul class="list-group">
                        <li class="list-group-item"><img src='<?= $block->getViewFileUrl('images/svg-icons/Date.svg'); ?>' alt=""  width="15" height="20" />
                            <span>valid until 1 Apr 2020</span>
                        </li>
                        <li class="list-group-item"><img src='<?= $block->getViewFileUrl('images/svg-icons/Date.svg'); ?>' alt=""  width="15" height="20" />
                            <span>Without minium transaction</span>
                        </li>
                    </ul>
                    <div class="primary">
                        <button type="submit" class="action save primary" title="Use voucher"><span>Use</span></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <p class="minium-purchase">Voucher Rp 100.000 without minimum purchase</p>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="product data items"
             data-mage-init='{"mage/tabs": {"openedState": "active", "animate": {"duration": 100}, "active": 1, "disabledState": "disabled"}}'>
                <div class="item title" data-role="collapsible">
                    <a class="switch" data-toggle="trigger" href="#how-to-use">How to Use</a>
                </div>
                <div id="how-to-use" class="item content" data-role="content">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elited do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elited do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elited do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elited do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elited do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elited do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elited do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

                </div>

                <div class="item title" data-role="collapsible">
                    <a class="switch" data-toggle="trigger" href="#terms-conditions">Terms & Conditions</a>
                </div>
                <div id="terms-conditions" class="item content" data-role="content">
                    <p>- Anh Hoàng Minh Hà, tài xế (SN 1980, trú tại xã Quảng Nghĩa, thành phố Móng Cái, tỉnh Quảng Ninh);</p>
                    <p>- Anh Hoàng Minh Hà, tài xế (SN 1980, trú tại xã Quảng Nghĩa, thành phố Móng Cái, tỉnh Quảng Ninh);</p>
                    <p>- Anh Hoàng Minh Hà, tài xế (SN 1980, trú tại xã Quảng Nghĩa, thành phố Móng Cái, tỉnh Quảng Ninh);</p>
                    <p>- Anh Hoàng Minh Hà, tài xế (SN 1980, trú tại xã Quảng Nghĩa, thành phố Móng Cái, tỉnh Quảng Ninh);</p>
                    <p>- Anh Hoàng Minh Hà, tài xế (SN 1980, trú tại xã Quảng Nghĩa, thành phố Móng Cái, tỉnh Quảng Ninh);</p>
                </div>
            </div>
        </div>
    </div>
</div>