<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Role extends \Spatie\Permission\Models\Role
{
    protected $fillable = ['name', 'guard_name', 'display_name', 'allowed_scope'];

    public function permissions(): BelongsToMany
    {
        return parent::permissions(); // TODO: Change the autogenerated stub
    }

}
