<?php
/**
 * SMCommerce
 *
 * @category  SM
 * @package   SM_Promotion
 *
 * Date: June, 22 2020
 * Time: 5:57 PM
 * User: VooThanh DEV
 *
 * @author    SMCommerce Core Team <connect@smartosc.com>
 * @copyright Copyright SMCommerce (http://smartosc.com/)
 */ ?>
<?php /** @var $block \SM\Promotion\Block\Catalog\Product\View\PromoLabel */ ?>
<div class="promo-label-container">
    <label class="promo-name"><?= $block->escapeHtml($block->getPromoNotify()) ?></label>
    <span class="dpl-tooltip">
        <img src="<?= $block->escapeHtmlAttr($block->getViewFileUrl('images/info.svg')) ?>" width="13" height="16"/>
        <pre class="tooltip-content" role="tooltip"><?= $block->getPromoTooltip() ?></pre>
    </span>
</div>
