<?php
/** @var \Trans\Brand\Block\BrandSlider $block */
$brandCollection = $block->getBrandCollection();

if ($brandCollection->getSize()>0) {
    ?>
    <div>
        <div class="content-heading">
            <h2 class="title"><?= $block->escapeHtml(('Brands')); ?></h2>
        </div>
        <div class="trans-brand-slider">
            <?php foreach ($brandCollection as $brand) {
                $imageSize=getimagesize($block->getBrandImageUrl($brand));
                ?>       
                <div class="brand-title">
                    <a href="<?= $block->escapeUrl($this->getBrandUrl($brand->getId(), $brand->getUrlKey())); ?>">
                        <?php if ($imageSize[0]==210 && $imageSize[1]==50) { ?>
                        <img src="<?= $block->escapeUrl($block->getBrandImageUrl($brand)) ?>" />
                        <?php } else { ?>
                        <img src="<?= $block->escapeUrl($block->getResizeUrl($brand->getImage(), 210, 50)) ?>" />
                        <?php }  ?>
                    </a>
                    <b><?= $block->escapeHtml($brand->getTitle()) ?></b>
                </div>
            <?php } ?>
            </div>
        </div>
        <script>
            require([
                'jquery',
                'slick'
                ], function ($) {
                    jQuery(document).ready(function () {
                        $('.trans-brand-slider').slick({
                            infinite: false,
                            slidesToShow: 5,
                            slidesToScroll: 1,
                            dots: false,
                            autoplay: false,
                            arrows: true,
                            responsive: [
                            {
                                breakpoint: 9999,
                                settings: {
                                    slidesToShow: 5,
                                    slidesToScroll: 1,
                                }
                            },
                            {
                                breakpoint: 1024,
                                settings: {
                                    slidesToShow: 3,
                                    slidesToScroll: 3,
                                }
                            },
                            {
                                breakpoint: 600,
                                settings: {
                                    slidesToShow: 2,
                                    slidesToScroll: 2,
                                    variableWidth: false,
                                }
                            },
                            {
                                breakpoint: 480,
                                settings: {
                                    slidesToShow: 1,
                                    slidesToScroll: 1,
                                    arrows: false,
                                    variableWidth: false,
                                }
                            }
                        ]
                    });
                    });
                });
            
            </script>
<?php } ?>
