<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>

<div class="digital-product-billing">
    <div class="dpb-bn-top">
        <img src="https://via.placeholder.com/1175x248.png?text=TopUP+Bills+Make+yourlife" alt="" />
    </div>
    <div class="product data items"
         data-mage-init='{"mage/tabs": {"openedState": "active", "animate": {"duration": 100}, "active": 1}}'>

        <div class="item title" data-role="collapsible">
            <a class="switch" data-toggle="trigger" href="#tab-topup">
                <img src='<?= $block->getViewFileUrl('images/svg-icons/digital-product-icons/water.svg'); ?>' alt=""  width="50" height="50" />
                <span>Top Up</span>
            </a>
        </div>
        <div id="tab-topup" class="item content top-up" data-role="content">
            <!-- content-start------->
            <h3 class="title-head-ct">Easy Top Up by Transmart</h3>
            <label class="label-input">Mobile Number<span class="dpl-tooltip"><a href="#" aria-describedby="tooltip-1" >
                        <img src='<?= $block->getViewFileUrl('images/info.svg'); ?>' alt=""  width="13" height="16" /></a>
                    <span class="tooltip-content" id="tooltip-1" role="tooltip">Your mobile number or
the number used for your modem.</span></span></label>
            <div class="wrap-input">
                <input class="input-text" type="text" placeholder="08787368279" />
                <img src="https://via.placeholder.com/51x51.png" alt="" />
            </div>
            <h3 class="title-nom">Nominal</h3>
            <ul class="list-nomial">
                <li class="active">
                    <div class="dpb-inner-content">
                        <h4>15.000</h4>
                        <span>Price: Rp 15.000</span>
                    </div>

                </li>
                <li>
                    <div class="dpb-inner-content">
                        <h4>20.000</h4>
                        <span>Price: Rp 20.000</span>
                    </div>
                </li>
                <li>
                    <div class="dpb-inner-content">
                        <h4>25.000</h4>
                        <span>Price: Rp 25.000</span>
                    </div>
                </li>
                <li>
                    <div class="dpb-inner-content">
                        <h4>50.000</h4>
                        <span>Price: Rp 49.000</span>
                    </div>
                </li>
                <li>
                    <div class="dpb-inner-content">
                        <h4>100.000</h4>
                        <span>Price: Rp 99.000</span>
                    </div>
                </li>
                <li>
                    <div class="dpb-inner-content">
                        <h4>150.000</h4>
                        <span>Price: Rp 149.000</span>
                    </div>
                </li>
                <li>
                    <div class="dpb-inner-content">
                        <h4>200.000</h4>
                        <span>Price: Rp 199.000</span>
                    </div>
                </li>
                <li>
                    <div class="dpb-inner-content">
                        <h4>500.000</h4>
                        <span>Price: Rp 480.000</span>
                    </div>
                </li>
            </ul>
            <div class="dpb-block-mobile">
                <h3>Top Up Details</h3>
                <p>Validity Period for 90 Days</p>
            </div>
            <!------if not price please add class 'dpb-price-noprice' -->
            <div class="dpb-bottom-price">
                <div class="dpb-price">
                    <label>Total</label>
                    <span>Rp 15.000</span>
                </div>
                <a href="#" class="action primary">Buy</a>
            </div>
            <!------if not price please add class 'dpb-price-noprice'-->
            <div class="dpb-policy">
                <div class="dpb-title-head"><h3><?= $block->escapeHtml(__('How to Top Up Through Transmart')) ?></h3></div>
                <div class="dpd-policy-content">
                    <p>Top up your mobile number and stay connected with dearest family and friends. In Transmart, you can top up mobile number of all operators with various nominal options. Anytime you want and wherever you are, Transmart can provide the easist online top up and payment method. Top up your mobile number with these simple steps.</p>
                    <ol>
                        <li>Go to Transmart website.</li>
                        <li>Choose Top Up & Bills category on the homepage.</li>
                        <li>Go to Top Up menu.</li>
                        <li>Enter your mobile number or modem number, then choose the nominal.</li>
                        <li>Tap or click "Buy" button.</li>
                        <li>Select your payment method and please make the payment. </li>
                    </ol>
                    <p>In Transmart, you can also opt to buy mobile package, electricity token, as well as paying your postpaid, PLN electricity, PDAM, BPJS and Telkom bills. Make your life easier by doing your transactions through Transmart!</p>
                </div>
            </div>
            <!-- content-end------->
        </div>
        <div class="item title" data-role="collapsible">
            <a class="switch" data-toggle="trigger" href="#mobile-package">
                <img src='<?= $block->getViewFileUrl('images/svg-icons/digital-product-icons/phone.svg'); ?>' alt=""  width="50" height="50" />
                <span>Mobile Package</span>
            </a>
        </div>
        <div id="mobile-package" class="item content mobile-package" data-role="content">
            <!-- content-start------->
            <h3 class="title-head-ct">Buy Mobile Package for Any Operator</h3>
            <label class="label-input">Mobile Number<span class="dpl-tooltip"><a href="#" aria-describedby="tooltip-2" >
                        <img src='<?= $block->getViewFileUrl('images/info.svg'); ?>' alt=""  width="13" height="16" /></a>
                    <span class="tooltip-content" id="tooltip-2" role="tooltip">Your mobile number or
the number used for your modem.</span></span></label>
            <div class="wrap-input">
                <input class="input-text" type="text" placeholder="08787368279" />
                <img src="https://via.placeholder.com/51x51.png" alt="" />
            </div>
            <h3 class="title-nom">Nominal</h3>
            <ul class="list-nomial">
                <li class="active">
                    <div class="dpb-inner-content">
                        <h4>XTRA Combo VIP 5GB +5GB</h4>
                        <span>Price: Rp 35.000</span>
                    </div>

                </li>
                <li>
                    <div class="dpb-inner-content">
                    <h4>XTRA Combo VIP 10GB +10GB</h4>
                    <span>Price: Rp 50.000</span>
                    </div>
                </li>
                <li>
                    <div class="dpb-inner-content">
                    <h4>XTRA Combo VIP 5GB +5GB</h4>
                    <span>Price: Rp 65.000</span>
                    </div>
                </li>
                <li>
                    <div class="dpb-inner-content">
                    <h4>HotRod Internet 1GB +200 SMS</h4>
                    <span>Price: Rp 90.000</span>
                    </div>
                </li>
                <li>
                    <div class="dpb-inner-content">
                    <h4>XTRA Combo 12GB +5GB</h4>
                    <span>Price: Rp 15.000</span>
                    </div>
                </li>
                <li>
                    <div class="dpb-inner-content">
                    <h4>XTRA Combo VIP 11GB +5GB</h4>
                    <span>Price: Rp 15.000</span>
                    </div>
                </li>
                <li>
                    <div class="dpb-inner-content">
                    <h4>HotRod Internet 2GB +200 SMS</h4>
                    <span>Price: Rp 15.000</span>
                    </div>
                </li>
                <li>
                    <div class="dpb-inner-content">
                    <h4>Phone 100 Minutes + SMS 200</h4>
                    <span>Price: Rp 15.000</span>
                    </div>
                </li>
            </ul>
            <div class="dpb-block-mobile">
                <h3>Mobile Package Details</h3>
                <p>Broadband Single Zone 4.5GB+2GB Video</p>
            </div>
            <!------if not price please add class 'dpb-price-noprice'-->
            <div class="dpb-bottom-price">
                <div class="dpb-price">
                    <label>Price</label>
                    <span>Rp 35.000</span>
                </div>
                <a href="#" class="action primary">Buy</a>
            </div>
            <!-------if not price please add class 'dpb-price-noprice'-->

            <div class="dpb-policy">
                <div class="dpb-title-head"><h3><?= $block->escapeHtml(__('How to Buy Mobile Package Through Transmart')) ?></h3></div>
                <div class="dpd-policy-content">
                    <p>There is no day without internet! From updating social media, chatting, reading online news, to online shopping, mobile package is your daily need. Make sure you always have internet connection by purchasing your online quota from Transmart. You can get every internet package from all operators here. Choose your data plan and get it with easy steps.</p>
                    <ol>
                        <li>Go to Transmart website.</li>
                        <li>Choose Top Up & Bills category on the homepage.</li>
                        <li>Go to Mobile Package menu.</li>
                        <li>Enter your mobile number or modem number, then choose the nominal.</li>
                        <li>Tap or click "Buy" button.</li>
                        <li>Select your payment method and please make the payment. </li>
                    </ol>
                    <p>Need to top up your mobile number for an important call? Or do you need to pay PLN electricity, PDAM water, BPJS, postpaid and Telkom bills? You can do it all with Transmart. Entrust your transactions with us. With secure and easy payment, we will make your life easier.</p>
                </div>
            </div>
           <!-- content-end------->
        </div>

        <div class="item title active" data-role="collapsible">
            <a class="switch" data-toggle="trigger" href="#pln-electricity">
                <img src='<?= $block->getViewFileUrl('images/svg-icons/digital-product-icons/phone-reset.svg'); ?>' alt=""  width="50" height="50" />
                <span>PLN Electricity</span>
            </a>
        </div>
        <div id="pln-electricity" class="item content pln-electricity" data-role="content">
            <!-- content-start------->
            <h3 class="title-head-ct">Buy Token or Pay Electricity Bill</h3>
            <div class="wrap-radio">
                <div class="radio-custom-checkmark">Electricity Token
                    <input type="radio"  name="radio" />
                    <lable class="checkmark"></lable>
                </div>
                <div class="radio-custom-checkmark">Electricity Bill
                    <input type="radio" name="radio"  checked="checked"/>
                    <lable class="checkmark"></lable>
                </div>
            </div>
            <!-- content-start Token------->
            <div class="electricity-token" style="display: none">
                <label class="label-input">Meter Number/Customer ID<span class="dpl-tooltip"><a href="#" aria-describedby="tooltip-3" >
                            <img src='<?= $block->getViewFileUrl('images/info.svg'); ?>' alt=""  width="13" height="16" /></a>
                        <span class="tooltip-content" id="tooltip-3" role="tooltip">The number printed on
your customer card.</span></span></label>
                <div class="wrap-input">
                    <input class="input-text" type="text" placeholder="2124343552452" />
                    <img src="https://via.placeholder.com/51x51.png" alt="" />
                </div>
                <h3 class="title-nom">Nominal</h3>
                <ul class="list-nomial">
                    <li>
                        <div class="dpb-inner-content">
                            <h4>15.000</h4>
                            <span>Price: Rp 15.000</span>
                        </div>

                    </li>
                    <li>
                        <div class="dpb-inner-content">
                            <h4>20.000</h4>
                            <span>Price: Rp 21.000</span>
                        </div>
                    </li>
                    <li class="active">
                        <div class="dpb-inner-content">
                            <h4>25.000</h4>
                            <span>Price: Rp 25.000</span>
                        </div>
                    </li>
                    <li>
                        <div class="dpb-inner-content">
                            <h4>50.000</h4>
                            <span>Price: Rp 49.000</span>
                        </div>
                    </li>
                    <li>
                        <div class="dpb-inner-content">
                            <h4>100.000</h4>
                            <span>Price: Rp 99.000</span>
                        </div>
                    </li>
                    <li>
                        <div class="dpb-inner-content">
                            <h4>150.000</h4>
                            <span>Price: Rp 149.000</span>
                        </div>
                    </li>
                    <li>
                        <div class="dpb-inner-content">
                            <h4>200.000</h4>
                            <span>Price: Rp 198.000</span>
                        </div>
                    </li>
                    <li>
                        <div class="dpb-inner-content">
                            <h4>500.000</h4>
                            <span>Price: Rp 480.000</span>
                        </div>
                    </li>
                </ul>
                <div class="dpb-block-mobile info-pln">
                    <h3>Information</h3>
                    <p>You will receive your token code within 2 x 24 hours after payment.</p>
                </div>
                <!------if not price please add class 'dpb-price-noprice'-->
                <div class="dpb-bottom-price">
                    <div class="dpb-price">
                        <label>Total</label>
                        <span>Rp 25.000</span>
                    </div>
                    <a href="#" class="action primary">Buy</a>
                </div>
                <!------if not price please add class 'dpb-price-noprice'-->
                <div class="dpb-policy">
                    <div class="dpb-title-head"><h3><?= $block->escapeHtml(__('How to Buy Electricity Token or Pay PLN Bill')) ?></h3></div>
                    <div class="dpd-policy-content">
                        <ol>
                            <li>Go to Transmart website.</li>
                            <li>Choose Top Up & Bills category on the homepage.</li>
                            <li>Go to PLN Electricity menu.</li>
                            <li>Enter your meter number. You can find meter number in your customer card.</li>
                            <li>Select the nominal that you want to buy.</li>
                            <li>Tap or click "Buy" button.</li>
                            <li>Select your payment method and please make the payment.</li>
                            <li>You will receive your token code in maximum of 2 x 24 hours.</li>
                        </ol>
                    </div>
                </div>
            </div>
            <!-- content-end-ToKen------>

            <!-- content-start Bill------->

            <div class="electricity-bill">
                <label class="label-input">Meter Number/Customer ID<span class="dpl-tooltip"><a href="#" aria-describedby="tooltip-4" >
                            <img src='<?= $block->getViewFileUrl('images/info.svg'); ?>' alt=""  width="13" height="16" /></a>
                        <span class="tooltip-content" id="tooltip-4" role="tooltip">The number printed on your monthly bill or
electricity meter barcode.</span></span></label>
                <div class="wrap-input">
                    <input class="input-text" type="text" placeholder="2124343552452" />
                    <img src="https://via.placeholder.com/51x51.png" alt="" />
                </div>
                <div class="dpb-block-mobile info-pln">
                    <h3>Information</h3>
                    <ol>
                        <li>The bill payment is due every 20th of the month.</li>
                        <li>Payment verification process takes a maximum of 2 x 24 hours</li>
                        <li>Fine, if any, is already included in the total bill.</li>
                    </ol>
                </div>
                <div class="dpb-bottom-price">
                    <a href="#" class="action primary">Check My Bill</a>
                </div>
                <div class="dpb-policy">
                    <div class="dpb-title-head"><h3><?= $block->escapeHtml(__('How to Buy Electricity Token or Pay PLN Bill')) ?></h3></div>
                    <div class="dpd-policy-content">
                        <p>When it comes to paying your electricity bills or buying electricity token, no one wants to do it with too much hassle. Transmart gives you the solution! We offer a simplicity to provide your daily need.</p>
                        <p style="padding-bottom:0px;">Buying PLN Electricity Token<br/>
                            You can find various nominal options for your electricity token. This prepaid electricity purchase can be done anywhere and anytime from Transmart's website and app. Follow these steps to buy electricity token.</p>
                        <ol>
                            <li>Go to Transmart website.</li>
                            <li>Choose Top Up & Bills category on the homepage.</li>
                            <li>Go to PLN Electricity menu.</li>
                            <li>Enter your meter number. You can find meter number in your customer card.</li>
                            <li>Select the nominal that you want to buy.</li>
                            <li>Tap or click "Buy" button.</li>
                            <li>Select your payment method and please make the payment.</li>
                            <li>You will receive your token code in maximum of 2 x 24 hours.</li>
                        </ol>
                        <p style="padding-bottom:0;">Paying Your PLN Electricity Bill</p>
                        <ol>
                            <li>Go to Transmart website.</li>
                            <li>Choose Top Up & Bills category on the homepage.</li>
                            <li>Go to PLN Electricity menu.</li>
                            <li>Enter your meter number. You can find meter number in your customer card.</li>
                            <li>Select the nominal that you want to buy.</li>
                            <li>Tap or click "Check My Bill" button.</li>
                            <li>Select your payment method and please make the payment.</li>
                        </ol>
                        <p>Paying other bills is just as easy! Transmart allows you to pay your PDAM water bill, BPJS bill, mobile postpaid and Telkom bill. You can also enjoy the easy way to top up your mobile number and to buy mobile package.</p>
                    </div>
                </div>
            </div>
            <!-- content-End Bill------->
        </div>
        <div class="item title" data-role="collapsible">
            <a class="switch" data-toggle="trigger" href="#pdam-water">
                <img src='<?= $block->getViewFileUrl('images/svg-icons/digital-product-icons/sun.svg'); ?>' alt=""  width="50" height="50" />
                <span>PDAM Water</span>
            </a>
        </div>
        <div id="pdam-water" class="item content pdam-water" data-role="content">
            <!-- content-start------->
            <h3 class="title-head-ct">Pay PDAM Water Bill</h3>

            <div class="dpl-select sl-region">
                <label class="label-input">Region</label>
                <div class="sortby-dropdown shoplist-sortby">
                    <span class="action toggle" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" aria-haspopup="true">
                        <span><?= $block->escapeHtml('Select Region') ?></span>
                    </span>
                    <ul class="dropdown">
                        <li class="item">Select Region</li>
                        <li class="item">Select Region</li>
                    </ul>
                </div>
            </div>

            <label class="label-input">Customer ID<span class="dpl-tooltip"><a href="#" aria-describedby="tooltip-5" >
                        <img src='<?= $block->getViewFileUrl('images/info.svg'); ?>' alt=""  width="13" height="16" /></a>
                    <span class="tooltip-content" id="tooltip-5" role="tooltip">Your customer or connection number.</span></span></label>

            <div class="wrap-input">
                <input class="input-text" type="text" placeholder="2124343552452" />
                <img src="https://via.placeholder.com/51x51.png" alt="" />
            </div>


            <div class="dpb-bottom-price dpb-price-noprice">
                <a href="#" class="action primary">Check My Bill</a>
            </div>

            <div class="dpb-policy">
                <div class="dpb-title-head"><h3><?= $block->escapeHtml(__('How to Pay PDAM Water Bill')) ?></h3></div>
                <div class="dpd-policy-content">
                    <p>You can entrust yout PDAM water bill payment to Transmart. There is so much benefit you can get by paying your water bill online: easy water bill checking, paying without queuing in line and you can do it anywhere anytime. No more hassle in getting your bill payment done, just do these steps:</p>
                    <ol>
                        <li>Go to Transmart website.</li>
                        <li>Choose Top Up & Bills category on the homepage.</li>
                        <li>Go to PDAM Water menu.</li>
                        <li>Select your region and enter your Customer ID. You can find your Customer ID in the water bill.</li>
                        <li>Click "Check My Bill" button.</li>
                        <li>Select your payment method and please make the payment.</li>
                    </ol>
                    <p>You can also enjoy this easy payment while paying your PLN bill, BPJS bill, mobile postpaid bill and Telkom bill. Your transaction is made convenient with secure payment options from Transmart: virtual account, credit card, debit card and instant payment. Make sure you also top up your mobile number, mobile package and PLN electricity token through Transmart to make your life easier.</p>
                </div>
            </div>
            <!-- content-end------->
        </div>
        <div class="item title" data-role="collapsible">
            <a class="switch" data-toggle="trigger" href="#bpjs">
                <img src='<?= $block->getViewFileUrl('images/svg-icons/digital-product-icons/lighting.svg'); ?>' alt=""  width="50" height="50" />
                <span>BPJS</span>
            </a>
        </div>
        <div id="bpjs" class="item content bpjs" data-role="content">
           <!-- start content-->
            <h3 class="title-head-ct">Pay BPJS Premium</h3>

            <div class="wrap-radio">
                <div class="radio-custom-checkmark">Kesehatan
                    <input type="radio"  name="radio" checked="checked" />
                    <lable class="checkmark"></lable>
                </div>
                <div class="radio-custom-checkmark">Ketenagakerjaan
                    <input type="radio" name="radio"  />
                    <lable class="checkmark"></lable>
                </div>
            </div>

            <!--start box kesehatan-->
            <div class="bpjs-kese">

                <label class="label-input">Family Virtual Account Number<span class="dpl-tooltip"><a href="#" aria-describedby="tooltip-6" >
                        <img src='<?= $block->getViewFileUrl('images/info.svg'); ?>' alt=""  width="13" height="16" /></a>
                    <span class="tooltip-content" id="tooltip-6" role="tooltip">Reference number for payment sent
by SMS after your BPJS registration.</span></span></label>
                <div class="wrap-input">
                    <input class="input-text" type="text" placeholder="" />
                    <img src="https://via.placeholder.com/51x51.png" alt="" />
                </div>

                <div class="dpl-select sl-month">
                    <label class="label-input">Pay for</label>
                    <div class="sortby-dropdown shoplist-sortby">
                    <span class="action toggle" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" aria-haspopup="true">
                        <span><?= $block->escapeHtml('Select Month') ?></span>
                    </span>
                        <ul class="dropdown">
                            <li class="item">Select Month</li>
                            <li class="item">Select Month</li>
                        </ul>
                    </div>
                </div>
                <div class="dpb-block-mobile info-pln">
                    <h3>Information</h3>
                    <p>Starting 1 January 2020, BPJS Kesehatan fee has been adjusted as follows.</p>
                    <p>1st class: from Rp 80.000 to Rp 160.000</p>
                    <p>2nd class: from Rp 51.000 to Rp 110.000</p>
                    <p>3rd class: from Rp 25.500 to Rp 42.000</p>
                    <p class="mar-top-50">- Make sure you enter the right number according to your BPJS card.</p>
                    <p>- Payment verification will be proceeded in maximum of 2 x 24 hours of working days.</p>
                    <p>- Transaction with "Waiting for Operator" status on Friday, Saturday and Sunday will be proceeded on the next working days.</p>
                </div>

                <div class="dpb-bottom-price dpb-price-noprice">
                    <a href="#" class="action primary">Check My Bill</a>
                </div>

                <div class="dpb-policy">
                    <div class="dpb-title-head"><h3><?= $block->escapeHtml(__('How to Pay Your BPJS Premium')) ?></h3></div>
                    <div class="dpd-policy-content">
                        <p>Transmart now serves you with an option to pay yout BPJS premium. Only with your internet connection and an access to Transmart website or application, you can do your BPJS Kesehatan or BPJS Ketenagakerjaan payment in seconds. No more queuing to do this transaction, you just need to follow these steps.</p>
                        <p class="mar-pad-0">Pay BPJS Kesehatan Online</p>
                        <ol>
                            <li>Go to Transmart website.</li>
                            <li>Choose Top Up & Bills category on the homepage.</li>
                            <li>Go to BPJS menu.</li>
                            <li>Choose Kesehatan.</li>
                            <li>Enter your Family Virtual Account Number.</li>
                            <li>Select the period that you want to pay.</li>
                            <li>Click "Check My Bill" button.</li>
                            <li>Select your payment method and please make the payment.</li>
                        </ol>
                        <p class="mar-pad-0">Pay BPJS Ketenagakerjaan Online</p>
                        <ol>
                            <li>Go to Transmart website.</li>
                            <li>Choose Top Up & Bills category on the homepage.</li>
                            <li>Go to BPJS menu.</li>
                            <li>Choose Ketenagakerjaan.</li>
                            <li>Enter your KTP number.</li>
                            <li>Select the period that you want to pay.</li>
                            <li>Click "Check My Bill" button.</li>
                            <li>Select your payment method and please make the payment.</li>
                        </ol>
                        <p>Don't miss the chance to do other bill transactions through Transmart. Here you can pay your PLN electricity bill, PDAM water bill, mobile postpaid bill, Telkom bill and top up your mobile number, mobile package and electricity token. Make your life convenient by doing your transactions through Transmart website and application. Secure payment options available for you to choose.</p>
                    </div>
                </div>

            </div>
            <!--End box kesehatan-->

            <!--start box Ketenagakerjaan-->
            <div class="bpjs-ketenaga">

                <label class="label-input">KTP Number<span class="dpl-tooltip"><a href="#" aria-describedby="tooltip-7" >
                        <img src='<?= $block->getViewFileUrl('images/info.svg'); ?>' alt=""  width="13" height="16" /></a>
                    <span class="tooltip-content" id="tooltip-7" role="tooltip">Insert your KTP Number for your
BPJS Ketenagakerjaan.</span></span></label>
                <div class="wrap-input">
                    <input class="input-text" type="text" placeholder="" />
                    <img src="https://via.placeholder.com/51x51.png" alt="" />
                </div>

                <div class="dpl-select sl-period">
                    <label class="label-input">Pay for</label>
                    <div class="sortby-dropdown shoplist-sortby">
                    <span class="action toggle" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" aria-haspopup="true">
                        <span><?= $block->escapeHtml('Select Period') ?></span>
                    </span>
                        <ul class="dropdown">
                            <li class="item">Select Period</li>
                            <li class="item">Select Period</li>
                        </ul>
                    </div>
                </div>
                <div class="dpb-block-mobile info-pln">
                    <h3>Information</h3>
                    <p>You can do BPJS billing code payment from SiskoTKLN in Transmart.</p>
                </div>

                <div class="dpb-bottom-price dpb-price-noprice">
                    <a href="#" class="action primary">Check My Bill</a>
                </div>

                <div class="dpb-policy">
                    <div class="dpb-title-head"><h3><?= $block->escapeHtml(__('How to Pay Your BPJS Premium')) ?></h3></div>
                    <div class="dpd-policy-content">
                        <p>Transmart now serves you with an option to pay yout BPJS premium. Only with your internet connection and an access to Transmart website or application, you can do your BPJS Kesehatan or BPJS Ketenagakerjaan payment in seconds. No more queuing to do this transaction, you just need to follow these steps.</p>
                        <p class="mar-pad-0">Pay BPJS Kesehatan Online</p>
                        <ol>
                            <li>Go to Transmart website.</li>
                            <li>Choose Top Up & Bills category on the homepage.</li>
                            <li>Go to BPJS menu.</li>
                            <li>Choose Kesehatan.</li>
                            <li>Enter your Family Virtual Account Number.</li>
                            <li>Select the period that you want to pay.</li>
                            <li>Click "Check My Bill" button.</li>
                            <li>Select your payment method and please make the payment.</li>
                        </ol>
                        <p class="mar-pad-0">Pay BPJS Ketenagakerjaan Online</p>
                        <ol>
                            <li>Go to Transmart website.</li>
                            <li>Choose Top Up & Bills category on the homepage.</li>
                            <li>Go to BPJS menu.</li>
                            <li>Choose Ketenagakerjaan.</li>
                            <li>Enter your KTP number.</li>
                            <li>Select the period that you want to pay.</li>
                            <li>Click "Check My Bill" button.</li>
                            <li>Select your payment method and please make the payment.</li>
                        </ol>
                        <p>Don't miss the chance to do other bill transactions through Transmart. Here you can pay your PLN electricity bill, PDAM water bill, mobile postpaid bill, Telkom bill and top up your mobile number, mobile package and electricity token. Make your life convenient by doing your transactions through Transmart website and application. Secure payment options available for you to choose.</p>
                    </div>
                </div>

            </div>
            <!--End box Ketenagakerjaan-->

        </div>
        <div class="item title" data-role="collapsible">
            <a class="switch" data-toggle="trigger" href="#mobile-postpaid">
                <img src='<?= $block->getViewFileUrl('images/svg-icons/digital-product-icons/light-add.svg'); ?>' alt=""  width="50" height="50" />
                <span>Mobile Postpaid</span>
            </a>
        </div>
        <div id="mobile-postpaid" class="item content mobile-postpaid" data-role="content">

            <!-- content-end------->

            <h3 class="title-head-ct">Pay Mobile Postpaid Bill</h3>

            <div class="dpl-select sl-operator">
                <label class="label-input">Operator</label>
                <div class="sortby-dropdown shoplist-sortby">
                    <span class="action toggle" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" aria-haspopup="true">
                        <span><?= $block->escapeHtml('XL') ?></span>
                    </span>
                    <ul class="dropdown">
                        <li class="item">XL</li>
                        <li class="item">XL</li>
                    </ul>
                </div>
            </div>

            <label class="label-input">Mobile Number<span class="dpl-tooltip"><a href="#" aria-describedby="tooltip-8" >
                        <img src='<?= $block->getViewFileUrl('images/info.svg'); ?>' alt=""  width="13" height="16" /></a>
                    <span class="tooltip-content" id="tooltip-8" role="tooltip">Your mobile number or
the number used for your modem.</span></span></label>

            <div class="wrap-input">
                <input class="input-text" type="text" placeholder="Example: 0817039300" />
                <img src="https://via.placeholder.com/51x51.png" alt="" />
            </div>


            <div class="dpb-bottom-price dpb-price-noprice">
                <a href="#" class="action primary">Check My Bill</a>
            </div>

            <div class="dpb-policy">
                <div class="dpb-title-head"><h3><?= $block->escapeHtml(__('How to Pay Mobile Postpaid Bill')) ?></h3></div>
                <div class="dpd-policy-content">
                    <p>Mobile postpaid payment is now safer and more convenient with Transmart. Do your mobile postpaid payment online and stay connected. Below are the steps to do this transaction.</p>
                    <ol>
                        <li>Go to Transmart website.</li>
                        <li>Choose Top Up & Bills category on the homepage.</li>
                        <li>Go to Mobile Postpaid menu.</li>
                        <li>Select your operator and enter your mobile or modem number.</li>
                        <li>Tap or click "Go to Payment" button.</li>
                        <li>Select your payment method and please make the payment.</li>
                    </ol>
                    <p>You can pay your other bills through Transmart. From PLN electricity bill, PDAM water bill, BPJS bill, to Telkom bill; these payments can be done online. Try topping up you mobile number, mobile package and electricity online too in our Top Up & Bills menu. Everything is brought to you in secure payment options: virtual account, credit card, debit card and instant payment.</p>
                </div>
            </div>
            <!-- content-end------->
        </div>
        <div class="item title" data-role="collapsible">
            <a class="switch" data-toggle="trigger" href="#telkom">
                <img src='<?= $block->getViewFileUrl('images/svg-icons/digital-product-icons/circle.svg'); ?>' alt=""  width="50" height="50" />
                <span>Telkom</span>
            </a>
        </div>
        <div id="telkom" class="item content dpb-telkom" data-role="content">
            <!-- content-end------->

            <h3 class="title-head-ct">Pay Telkom Bill</h3>

            <div class="dpl-select sl-location">
                <label class="label-input">Location</label>
                <div class="sortby-dropdown shoplist-sortby">
                    <span class="action toggle" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" aria-haspopup="true">
                        <span><?= $block->escapeHtml('Jakarta') ?></span>
                    </span>
                    <ul class="dropdown">
                        <li class="item">Jakarta</li>
                        <li class="item">Jakarta</li>
                    </ul>
                </div>
            </div>

            <label class="label-input">Phone Number <span class="dpl-tooltip"><a href="#" aria-describedby="tooltip-9" >
                        <img src='<?= $block->getViewFileUrl('images/info.svg'); ?>' alt=""  width="13" height="16" /></a>
                    <span class="tooltip-content" id="tooltip-9" role="tooltip">Your area code and telephone number.
Example: 02187654321</span></span>
            </label>

            <div class="wrap-input">
                <input class="input-text" type="text" placeholder="Example: 0217368279" />
                <img src="https://via.placeholder.com/51x51.png" alt="" />
            </div>

            <div class="dpb-block-mobile info-pln">
                <h3>Information</h3>
                <ol>
                    <li>Telkom payments include Indihome products and landlines.</li>
                    <li>The total bill listed includes a fine.</li>
                    <li>The payment verification process takes a maximum of 2x24 hours.</li>
                </ol>
            </div>
            <div class="dpb-bottom-price dpb-price-noprice">
                <a href="#" class="action primary">Go to Payment</a>
            </div>

            <div class="dpb-policy">
                <div class="dpb-title-head"><h3><?= $block->escapeHtml(__('How to Pay Telkom Bill')) ?></h3></div>
                <div class="dpd-policy-content">
                    <ol>
                        <li>Go to Transmart website.</li>
                        <li>Choose Top Up & Bills category on the homepage.</li>
                        <li>Go to Telkom menu.</li>
                        <li>Enter your phone number (including area code).</li>
                        <li>Click "Check My Bill" button.</li>
                        <li>Select your payment method and please make the payment.</li>
                    </ol>
                </div>
            </div>
            <!-- content-end------->
        </div>
    </div>

</div>



