<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<div class="notification-verify-email" id="notification-verify-email">
    <div class="top-container">
    <i class="notification-icon"></i>
    <span class="notification-verify-email-content">
Let's verify your account! It's as easy as completing your profile. </span>
    <a href="https://apollo11-dev.ctdigital.id/customer/account/">
        <button class="action primary">Complete Now</button>
    </a>
    <button class="close-button" id="close-notification"></button>
    </div>
</div>


