<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>

<div class="loading-modal">
    <style type="text/css">
        .cms-home .page-header.sticky, .cms-home #chat-widget-container {
            display: none;
        }

        .loading-modal {
            background: #fff;
            position: absolute;
            top:0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: 99999;
        }
    </style>
    <div class="loading-html" style="margin:auto;max-width: 1175px">
        <div class="top" style="padding:20px 0 40px"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load_group.svg'); ?>' alt="" /></div>
        <div class="slider" style="padding:0 0 40px;"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load.svg'); ?>' alt=""  width="1175" height="412" /></div>
        <div style="display: flex;width: 100%;padding-bottom:100px;">
            <div class="one" style="padding-right: 50px"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load.svg'); ?>' alt="" width="349" height="261" /></div>
            <div class="two" style="padding-right: 20px"><img src='<?= $block->getViewFileUrl('images/svg_loading/circal-load_group.svg'); ?>' alt="" width="375"  /></div>
            <div class="three" style="border-left:1px solid #ccc;padding-left:20px"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load_group1.svg'); ?>' alt="" width="381"  /></div>
        </div>
        <div><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load_group2.svg'); ?>' alt=""  /></div>
        <div style="display: flex;padding:60px;">
            <div class="one" style="padding-right:25px"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load_group4.svg'); ?>' alt="" width="187"  /></div>
            <div class="two" style="padding-right:25px"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load_group4.svg'); ?>' alt="" width="187" /></div>
            <div class="three" style="padding-right:25px"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load_group4.svg'); ?>' alt=""  width="187" /></div>
            <div class="fore" style="padding-right:25px"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load_group4.svg'); ?>' alt=""  width="187" /></div>
            <div class="five"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load_group4.svg'); ?>' alt="" width="187" /></div>
        </div>
        <div style="padding-bottom: 50px;"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load_group2.svg'); ?>' alt=""  /></div>
        <div style="display: flex">
            <div class="one" style="margin-right: 37px;margin-bottom:37px"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load.svg'); ?>' alt="" width="365"  /></div>
            <div class="one" style="margin-right: 37px;margin-bottom:37px"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load.svg'); ?>' alt="" width="365" /></div>
            <div class="one"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load.svg'); ?>' alt="" width="365" /></div>
        </div>
        <div style="display: flex">
            <div class="one" style="margin-right: 37px;margin-bottom:37px"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load.svg'); ?>' alt="" width="365" /></div>
            <div class="one" style="margin-right: 37px;margin-bottom:37px"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load.svg'); ?>' alt="" width="365" /></div>
            <div class="one"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load.svg'); ?>' alt="" width="365" /></div>
        </div>
        <div style="padding-top:60px"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load_group3.svg'); ?>' alt=""  /></div>
        <div style="display: flex;padding-bottom:60px;padding-top:60px">
            <div class="one" style="padding-right: 60px"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load_group5.svg'); ?>' alt="" width="360" /></div>
            <div class="one" style="padding-right: 60px"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load_group5.svg'); ?>' alt="" width="360" /></div>
            <div class="one"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load_group5.svg'); ?>' alt="" width="360" /></div>
        </div>
        <div style="padding:0 0 50px"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load_group3.svg'); ?>' alt=""  /></div>
        <div style="display: flex;padding-bottom: 100px">
            <div class="one" style="padding-right: 25px;width:375px"><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load.svg'); ?>' alt=""  width="375" height="587" /></div>
            <div class="one" style="padding-right: 25px;width:375px">
                <img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load.svg'); ?>' alt=""  width="375"  style="margin-bottom: 25px" />
                <img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load.svg'); ?>' alt=""  width="375"  />
            </div>
            <div class="one" style="width:375px">
                <img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load.svg'); ?>' alt=""  width="375" style="margin-bottom: 25px" />
                <img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load.svg'); ?>' alt=""  width="375" />
            </div>
        </div>
        <div style="display: flex;border:1px solid #2f2f2f;border-right: 0;border-left: 0;padding: 60px;">
            <div><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load_group6.svg'); ?>' alt="" style="margin-right: 60px" width="180" /></div>
            <div><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load_group6.svg'); ?>' alt="" style="margin-right: 60px" width="180" /></div>
            <div><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load_group6.svg'); ?>' alt="" style="margin-right: 60px" width="180" /></div>
            <div><img src='<?= $block->getViewFileUrl('images/svg_loading/rectangle_load_group7.svg'); ?>' alt="" width="257" height="120" /></div>
        </div>
        <div style="text-align: center;padding:40px 0 60px"><img src='<?= $block->getViewFileUrl('images/svg_loading/circal-load.svg'); ?>' alt=""  width="411" height="20" /></div>
    </div>
</div>
