<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.Incorrect

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
$GTMViewModel = $block->getData('gtm_view_model');
/* @var $helper \SM\Catalog\Helper\Data */
$helper = $this->helper('SM\Catalog\Helper\Data');
$type = $helper->checkTypeBlock($block->getType());
$freshHelper = $this->helper('SM\FreshProduct\Helper\Data');
?>

<?php
switch ($type) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('You may also like');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('You may also like');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    default:
        $exist = null;
}
?>

<?php if ($exist) :?>

<?php if ($type == 'related' || $type == 'upsell') :?>
<?php if ($type == 'related') :?>
<div class="block <?= $block->escapeHtmlAttr($class) ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= $block->escapeHtmlAttr($limit) ?>" data-shuffle="<?= /* @noEscape */ $shuffle ?>" style="clear:both;">
    <?php else :?>
    <div class="block <?= $block->escapeHtmlAttr($class) ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?= $block->escapeHtmlAttr($limit) ?>" data-shuffle="<?= /* @noEscape */ $shuffle ?>">
        <?php endif; ?>
        <?php else :?>
        <div class="block <?= $block->escapeHtmlAttr($class) ?>">
            <?php endif; ?>
            <div class="block-title title">
                <strong id="block-<?= $block->escapeHtmlAttr($class) ?>-heading" role="heading" aria-level="2"><?= $block->escapeHtml($title) ?></strong>
            </div>
            <div class="block-content content" aria-labelledby="block-<?= $block->escapeHtmlAttr($class) ?>-heading">
                <?php if ($type == 'related' && $canItemsAddToCart) :?>
                <?php endif; ?>
                <div class="products wrapper  products-grid products-<?= $block->escapeHtmlAttr($type) ?>">
                    <ol class="products list items product-items">
                        <?php $position = 1; ?>
                        <?php foreach ($items as $_item) :?>
                        <?php $data = $GTMViewModel ? $GTMViewModel->getGtmData($_item) : null; ?>
                            <?php $available = ''; ?>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related') :?>
                                <?php if (!$_item->getRequiredOptions()) :?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($type == 'related' || $type == 'upsell') :?>
                                <li class="item product product-item" style="display: none;">
                            <?php else :?>
                                <li class="item product product-item">
                            <?php endif; ?>
                            <div class="product-item-info <?= /* @noEscape */ $available ?>"
                                 <?php if ($data) : ?>
                                 data-gtm-product="<?= $block->escapeHtml($data); ?>"
                                 data-gtm-position="<?= $position; ?>"
                                 data-gtm-list="<?= $block->escapeHtml($title) ?>"
                                 data-gtm-event="product_view"
                                 <?php endif; ?>>
                                <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                   class="product photo product-item-photo"
                                   <?php if ($data) : ?>
                                   data-gtm-product="<?= $block->escapeHtml($data); ?>"
                                   data-gtm-position="<?= $position; ?>"
                                   data-gtm-list="<?= $block->escapeHtml($title) ?>"
                                   data-gtm-event="product_click"
                                   <?php endif; ?>>
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <?php $percent = $helper->getDiscountPercent($_item); ?>
                                <?php if ($percent != null && $percent > 0) : ?>
                                    <span class="product-sale"><?= $block->escapeHtml(__('%1% OFF', $percent)); ?></span>
                                <?php endif; ?>
                                <div class="product details product-item-details demo2">
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                           href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                           <?php if ($data) : ?>
                                           data-gtm-product="<?= $block->escapeHtml($data); ?>"
                                           data-gtm-position="<?= $position; ?>"
                                           data-gtm-list="<?= $block->escapeHtml($title) ?>"
                                           data-gtm-event="product_click"
                                           <?php endif; ?>>
                                            <?= $block->escapeHtml($_item->getName()) ?></a>
                                    </strong>

                                    <?= /* @noEscape */ $block->getProductPrice($_item) ?>

                                    <?php if ($freshHelper->isFreshProduct($_item)) : ?>
                                        <?php /** @var $freshBlock \SM\FreshProduct\Block\Product\View */ ?>
                                        <?php $freshBlock = $block->getLayout()->getBlock('product.fresh') ?>

                                        <?php if ($freshBlock) : ?>
                                            <?= $freshBlock->setProduct($_item)->toHtml() ?>
                                        <?php endif; ?>
                                    <?php endif; ?>

                                    <?php if ($templateType) :?>
                                        <?php
                                        $ratingSummary = $helper->getRattingSummary($_item->getSku());
                                        $reviewCount = $helper->getRattingCount($_item->getSku());
                                        ?>
                                        <div class="product-reviews-summary short<?= !$ratingSummary ? ' no-rating' : '' ?>" onclick="location.href = '<?= $block->getProductUrl($_item)?>'">
                                            <div class="rating-summary">
                                                <div class="rating-result" title="<?= $block->escapeHtmlAttr($ratingSummary) ?>%">
                                                    <span style="width:<?= $ratingSummary ?>%"><span><?= $block->escapeHtml($ratingSummary) ?>%</span></span>
                                                </div>
                                            </div>
                                            <span class="rating-count reviews-actions">(<?= $block->escapeHtml($reviewCount) ?>)</span>
                                        </div>
                                    <?php endif; ?>
                                    <?php $showCart = $_item->getData('hide_cta_button') ? false : $showCart; ?>
                                    <?php if ($showAddTo || $showCart) :?>
                                        <div class="product actions product-item-actions">
                                            <?php if ($showCart) :?>
                                                <div class="actions-primary">
                                                    <?php $childrenIds = $_item->getTypeInstance()->getChildrenIds($_item->getId()); ?>
                                                    <?php if ($childrenIds): ?>
                                                        <a title="<?= $block->escapeHtmlAttr(__('View Details')) ?>"
                                                           href="<?= $block->escapeUrl($_item->getProductUrl()) ?>"
                                                           class="action view-details primary"
                                                           <?php if ($data) : ?>
                                                           data-gtm-product="<?= $block->escapeHtml($data); ?>"
                                                           data-gtm-position="<?= $position; ?>"
                                                           data-gtm-list="<?= $block->escapeHtml($title) ?>"
                                                           data-gtm-event="product_click"
                                                           <?php endif; ?>>
                                                            <?= $block->escapeHtml(__('View Details')) ?>
                                                        </a>
                                                    <?php else :?>
                                                        <?php if ($_item->isSaleable()) :?>
                                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)) :?>
                                                                <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                </button>
                                                            <?php else :?>
                                                                <?php $postDataHelper = $this->helper(Magento\Framework\Data\Helper\PostHelper::class);
                                                                $postData = $postDataHelper->getPostData($block->escapeUrl($block->getAddToCartUrl($_item)), ['product' => $_item->getEntityId()])
                                                                ?>
                                                                <form data-role="tocart-form"
                                                                      data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>"
                                                                      action="<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"
                                                                      method="post">
                                                                    <input type="hidden" name="product"
                                                                           value="<?= $block->escapeHtmlAttr($_item->getEntityId()) ?>">
                                                                    <div class="update-cart-qty">
                                                                        <input type="hidden" name="item_id" value="0"/>
                                                                        <input type="hidden" name="qty_type" value="1"/>
                                                                        <button type="submit"
                                                                                title="<?= $block->escapeHtmlAttr(__('Decrease qty')) ?>"
                                                                                class="action decrease-qty">
                                                                            <span><?= __('-') ?></span>
                                                                        </button>
                                                                        <label for="item_qty" class="label-item-qty">
                                                                            <input type="number" name="item_qty" value="0"/>
                                                                        </label>
                                                                        <button type="submit" title="<?= $block->escapeHtmlAttr(__('Increase qty')) ?>"
                                                                                value="increase" class="action increase-qty"
                                                                                <?php if ($data) : ?>
                                                                                    data-gtm-product="<?= $block->escapeHtml($data); ?>"
                                                                                    data-gtm-position="<?= $position ?>"
                                                                                <?php endif; ?>>
                                                                            <span><?= __('+') ?></span>
                                                                        </button>
                                                                    </div>
                                                                    <?= $block->getBlockHtml('formkey') ?>
                                                                    <button type="submit"
                                                                            title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                            class="action tocart primary"
                                                                            <?php if ($data) : ?>
                                                                                data-gtm-product="<?= $block->escapeHtml($data); ?>"
                                                                                data-gtm-position="<?= $position ?>"
                                                                            <?php endif; ?>>
                                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                    </button>
                                                                </form>
                                                            <?php endif; ?>
                                                        <?php else :?>
                                                            <?php if ($_item->getIsSalable()) :?>
                                                                <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                            <?php else :?>
                                                                <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>

                                            <?php if ($showAddTo) :?>
                                                <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                    <?php if ($addToBlock = $block->getChildBlock('addto')) :?>
                                                        <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            </li>
                            <?php $position++; ?>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
        </div>

            <?php if (!$block->isRedirectToCartEnabled()) :?>
                <script type="text/x-magento-init">
                {
                    "[data-role=tocart-form], .form.map.checkout": {
                        "catalogAddToCartAdvanced": {
                            "product_sku": "<?= $block->escapeJs($_item->getSku()) ?>"
                        }
                    }
                }
                </script>
            <?php endif; ?>
        <?php endif;?>
