<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Checkbox */ ?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<div class="field admin__field options<?php if ($_option->getRequired()) echo ' required' ?>">
    <label class="label admin__field-label"><span><?php echo $block->escapeHtml($_option->getTitle()) ?></span></label>
    <div class="control admin__field-control">
        <div class="nested<?php if ($_option->getDecoratedIsLast()):?> last<?php endif; ?>">
            <div class="field option <?php echo ($_option->getRequired()) ? ' required': ''; ?>">
                <label class="label">
                    <span><?php echo $block->escapeHtml($_option->getTitle()) ?></span>
                </label>
                <div class="nested options-list" data-role="single-options-<?php echo $block->getOption()->getId() ?>">
                    <?php if ($block->showSingle()): ?>
                        <?php /* @escapeNotVerified */ echo $block->getSelectionQtyTitlePrice($_selections[0]) ?>
                        <input type="hidden"
                               class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>  product bundle option"
                               name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                               value="<?php /* @escapeNotVerified */ echo $_selections[0]->getSelectionId() ?>"/>
                    <?php else:?>
                    <div style="overflow: auto;">
                        <div style="width: 40%; float: left; clear: left;border-bottom: 1px solid #000;">
                            <b>Name</b>
                        </div>
                        <div style="width: 25%; float: left;border-bottom: 1px solid #000;">
                            <b>Options</b>
                        </div>
                        <div style="width: 15%; float: left;border-bottom: 1px solid #000;">
                            <b>Qty</b>
                        </div>
                        <div style="width: 20%; float: left;border-bottom: 1px solid #000;">
                            <b>Price</b>
                        </div>
                    </div>

                    <?php foreach($_selections as $_selection): ?>
                    <div class="field choice">
                        <div style="margin-top: 10px; overflow: auto;">
                            <div style="width: 45%; float: left;">
                                <input class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?> checkbox bundle-selection-checkbox product bundle option change-container-classname hidden"
                                       id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"
                                       type="checkbox"
                                    <?php if ($_option->getRequired()) echo 'data-validate="{\'validate-one-required-by-name\':\'input[name^=&quot;bundle_option[' . $_option->getId() . ']&quot;]:checked\'}"'?>
                                       name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>][<?php /* @escapeNotVerified */ echo $_selection->getId() ?>]"
                                       data-selector="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>][<?php /* @escapeNotVerified */ echo $_selection->getId() ?>]"
                                    <?php if ($block->isSelected($_selection)) echo ' checked="checked"' ?>
                                    <?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>
                                       value="<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"/>
                                <label class="label" style="margin-left: 0;"
                                       for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>">
                                    <span><?php echo $_selection->getName() ?></span>
                                </label>
                            </div>
                            <div style="width: 20%; float: left;">
                                <?php if ($block->hasOptions($_selection)) : ?>
                                    <button title="Configure" type="button" class="action primary" onclick="jQuery('#custom-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>').toggle();"><span><span>Configure</span></span></button>
                                <?php else : ?>
                                    No Options
                                <?php endif; ?>
                            </div>
                            <div style="width: 15%; float: left;">
                                <input type="text" id="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>-qty-input" class="input-text bundle-selection-qty qty" style="width: 50px;" name="bundle_option_qty[<?php echo $_option->getId() ?>][<?php echo $_selection->getId() ?>]" value="0" />
                            </div>

                            <div style="width: 20%; float: left;">
                                <b><?php echo $block->renderPriceString($_selection, false) ?></b>
                            </div>
                        </div>
                    </div>

                    <div class="bundle-custom-options simple-options" style"text-align: left;border: 1px solid #000;padding: 25px;" id="custom-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>">
                    <?php echo $block->getOptionsHtml($_selection); ?>
                </div>
                <?php endforeach; ?>
                <div id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-container"></div>
                <?php endif; ?>
            </div>
        </div>
        </div>
    </div>
</div>