<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_option = $block->getOption() ?>
<div data-bundle-option-id="<?php echo $this->getBundleOption() ?>" data-product-id="<?php echo $this->getProduct()->getId() ?>" class="custom-option-field field">
    <label class="custom-option-label label"><span><?php echo  $block->escapeHtml($_option->getTitle()) ?></span></label>
</div>
