<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /* @var $block \Magento\Catalog\Block\Product\View\Options\Type\Select */ ?>
<?php
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';
?>
<div id="bss_options_<?php echo $_option->getId() ?>" data-bundle-option-id="<?php echo $this->getBundleOption() ?>" data-product-id="<?php echo $this->getProduct()->getId() ?>" class="custom-option-field field<?php /* @escapeNotVerified */ echo $class; ?>">
    <?php
    $requiredClass = '';
    if ($_option->getIsRequire()) { $requiredClass = ' required-star'; }
    ?>
    <label class="custom-option-label label<?php echo $requiredClass ?>" for="select_<?php /* @escapeNotVerified */ echo $_option->getId() ?>">
        <span><?php echo  $block->escapeHtml($_option->getTitle()) ?></span>
        <?php if($block->isBssInstalled()) : ?>
            <?php  echo $block->getBssCustomOptionBlock('after_title'); ?>
        <?php endif; ?>
    </label>
    <?php if($block->isBssInstalled()) : ?>
        <?php echo $block->getBssCustomOptionBlock('before_control'); ?>
    <?php endif; ?>
    <div class="control">
        <?php echo $block->getValuesHtml() ?>
        <?php if ($_option->getIsRequire()): ?>
            <?php if ($_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_RADIO ||
                      $_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_CHECKBOX): ?>
                <span id="options-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-container"></span>
            <?php endif; ?>
        <?php endif;?>
    </div>
    <?php if($block->isBssInstalled()) : ?>
        <?php  echo $block->getBssCustomOptionBlock('after_control'); ?>
    <?php endif; ?>
</div>
