<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<div class="my-giftRegistry">
<form action="<?= $block->escapeUrl($block->getUrl('*/*/editPost')) ?>"
      method="post"
      id="form-validate"
      class="form form-giftregistry-edit validation"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>

    <div class="widget block block-dashboard-info">
            <div class="block-title">
                <strong>Registry Details</strong>
            </div>

            <div class="block-content box-content-email-mobileNumber">
                <div class="row">
                    <div class="col-sm-12 col-md-8">
                        <?= $block->getBlockHtml('formkey') ?>
                        <?= $block->getChildHtml() ?>
                        <div class="actions-toolbar align-right">
                            <div class="primary">
                                <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>" class="
                                 back">
                                    <span><?= $block->escapeHtml(__('Back')) ?></span>
                                </a>
                            </div>
                            <div class="primary">
                                <button type="submit" id="submit.save" title="<?= $block->escapeHtmlAttr(__('Save')) ?>" class="action primary save">
                                    <span><?= $block->escapeHtml(__('Save')) ?></span>
                                </button>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
    </div>

</form>
</div>
