<?php
/**
 * @category Trans
 * @package  Trans_CustomerMyProfile
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 *
 * @author   Dwi Septha Kurniawan <septha.kurniawan@transdigital.co.id>
 *
 * Copyright © 2019 PT Trans Digital. All rights reserved.
 * http://www.ctcorpora.com
 */

// @codingStandardsIgnoreFile
?>
<form class="form form-edit-account" action="<?= $block->escapeUrl($block->getBaseUrl() . 'rest/V1/customers/changePassword') ?>" method="post" id="form-edit-password" enctype="multipart/form-data" data-mage-init='{"validation": {}}' autocomplete="off">
    <legend class="legend"><span><?= $block->escapeHtml(__('Change Password')) ?></span></legend><br>
    <fieldset class="fieldset change-password password" data-container="change-email-password">
        <div class="field password current required">
            <label class="label" for="current-password"><span><?= $block->escapeHtml(__('Current Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" placeholder="**********" name="current_password" id="current-password" data-input="current-password" autocomplete="off" aria-required="true" data-validate="{required:true}" />
            </div>
            <div class="trans-message-error pass-msg"></div>
        </div>
        <div class="field new password required" data-container="new-password" style="display: block;">
            <label class="label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password" placeholder="**********"
                    data-password-min-length="<?= $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                    data-password-min-character-sets="<?= $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                    data-input="new-password"
                    data-validate="{required:true, 'validate-trans-password':true}"
                    autocomplete="off" />
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite" style="display:none">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                </div>
                <div id="suggestion-password" style="display: none">
                    <span id="sg-title"></span>
                    <span id="sg-password"></span>
                </div>
            </div>
        </div>
        <div class="field confirm password required" data-container="confirm-password" style="display: block;">
            <label class="label" for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                    data-input="confirm-password" placeholder="**********"
                    autocomplete="off" aria-required="true" data-validate="{required:true, equalTo:'[data-input=new-password]'}"/>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <button type="button" class="profile-cancel"><?= $block->escapeHtml(__('Cancel')) ?></button>
        <button type="submit" class="profile-save primary action"><?= $block->escapeHtml(__('Save')) ?></button>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "*": {
            "Trans_CustomerMyProfile/js/password": {
                "formSelector": "#form-edit-password",
                "currentPassSelector": "#form-edit-password input[name=current_password]",
                "newPasswordSelector": "#form-edit-password input[name=password]",
                "newRePasswordSelector": "#form-edit-password input[name=password_confirmation]",
                "email": "<?= $block->getCustomer()->getEmail(); ?>",
                "resetButtonSelector": "#form-edit-password button.profile-cancel",
                "passMsg": "#form-edit-password .pass-msg"
            }
        }
    }
</script>
