<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Store\Block\Switcher $block */
?>
<?php if (count($block->getStores())>1) : ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
        <div class="actions options switcher-options">
            <ul class="switcher-dropdown">
                <?php foreach ($block->getStores() as $_lang) : ?>
                    <?php $cssClasses =  $_lang->getId() == $block->getCurrentStoreId() ? ' is-active' : '' ?>
                    <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option<?= $cssClasses ?>">
                        <a href="<?= $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($_lang)) ?>">
                            <?= $block->escapeHtml($_lang->getName()) ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
