<?php
/**
 * @project    ct-corp-transmart
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author     Duc Nguyen Hoang <ducnh2@smartosc.com>
 * @copyright  Copyright © 2020 SmartOSC. All rights reserved.
 * @url        http://www.smartosc.com
 */

/** @var \Mirasvit\Blog\Block\Sidebar\Search $block */
?>
<div class="inspireMe-post-search review-search">
    <div class="control">
        <a class="btn-search-item" href="#"><span class="apl-ic_search"></span></a>
        <form id="form-search-list-item" method="get" action="<?= $block->getSearchUrl() ?>">
            <label for="input-search"/>
            <input id="input-search" type="text" name="q" value="<?= $block->escapeHtmlAttr($block->getSearchValue())?>"
                   placeholder="<?= $block->escapeHtml(__('What would you like to read ?'))?>"
                   class="input-text required-entry" maxlength="128" role="combobox" aria-haspopup="false"
                   aria-autocomplete="both" autocomplete="off" aria-expanded="true"/>
        </form>
    </div>
</div>
