<?php
/**
 * @project    ct-corp-transmart
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author     Duc Nguyen Hoang <ducnh2@smartosc.com>
 * @copyright  Copyright © 2020 SmartOSC. All rights reserved.
 * @url        http://www.smartosc.com
 */

/** @var \Mirasvit\Blog\Block\Post\PostList\Toolbar $block */
$currentDirection= $block->getCurrentDirection();
?>
<div class="sortby-dropdown inspire-post-sortby">
    <span class="action toggle" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" aria-haspopup="true">
        <span>
            <?= $block->escapeHtml(__('Sort by:')) ?>
            <?php
                if ($currentDirection === 'desc') {
                    echo __('Recent');
                } elseif ($currentDirection === 'asc') {
                    echo __('Previous');
                }
                ?>
        </span>
    </span>
    <ul class="dropdown" data-role="sorter">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) : ?>
            <li class="checkbox-custom <?= ($_key === $block->getCurrentDirection() ? 'checked' : '')?>"
                id="order-<?= $block->escapeHtmlAttr($_key) ?>"
                data-value="<?= $block->escapeHtmlAttr($_key) ?>">
                <span class="checkbox-label"><?= $block->escapeHtml($_order) ?></span>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
