<?php

/**
 * @category  SM
 * @package   SM_Catalog
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 * @author    Logan Ta <phuongtt2@smartosc.com>
 *
 * @copyright 2020 Copyright (c) SmartOSC. All rights reserved.
 * @url http://www.smartosc.com/
 */

?>
<div class="buynow-button">
    <button type="submit"
            title="<?= /* @escapeNotVerified */ __('Buy Now') ?>"
            id="product-buy-now"
            class="action tocart"
            data-mage-init='
            {
                "SM_Catalog/js/buy-now": {
                    "form": "#product_addtocart_form"
                }
            }
            '
            data-gtm-pdp="buy-now-pdp">
        <?= /* @escapeNotVerified */ __('Buy Now') ?>
    </button>
</div>
